// client/src/views/settings/UsageRules.vue
<template>
  <div class="usage-rules-page">
    <SettingsPageLayout title="使用规范">
      <div class="usage-rules__intro">
        <p class="usage-rules__paragraph">本规范依据《中华人民共和国民法典》《中华人民共和国网络安全法》《中华人民共和国个人信息保护法》《互联网信息服务管理办法》等相关法律法规制定，旨在规范用户使用本 APP 的行为，保障平台运营秩序、用户合法权益及数据安全。凡注册、登录、使用本 APP 的自然人、法人或其他组织（以下统称「用户」），均视为已阅读、理解并同意本规范全部内容；若用户不同意本规范，应立即停止使用本 APP。</p>
        <p class="usage-rules__paragraph">本规范由【吉林省爱智汇人工智能科技有限公司】（以下统称「平台方」）制定并负责解释，平台方可根据法律法规更新、平台运营需要对本规范进行修订，修订后的规范将通过 APP 内公示、弹窗等方式通知用户，公示期满后即生效，用户继续使用本 APP 视为同意修订后的内容。</p>
      </div>

      <section class="usage-rules__section">
        <div class="usage-rules__card">
          <h2 class="usage-rules__title">一、账号使用规则</h2>
          <p class="usage-rules__paragraph">用户需通过本 APP 官方指定渠道（手机号 / 第三方授权等）注册账号，注册时应提供真实、准确、完整的身份信息及联系方式，若信息发生变更，需及时在 APP 内更新。因虚假、失效信息导致的账号使用问题、权益损失，由用户自行承担。</p>
          <p class="usage-rules__paragraph">账号所有权归平台方所有，用户仅获得账号的有限使用权，仅限本人使用，禁止以出租、出借、售卖、转让、赠与等方式处分账号，禁止将账号交由他人代为操作。若发生上述行为，平台方可冻结 / 注销账号，由此产生的一切损失由用户承担。</p>
          <p class="usage-rules__paragraph">用户需妥善保管账号密码、验证码、人脸识别信息等登录凭证，对账号下的所有操作、行为及产生的后果承担全部责任。因用户自身原因（如密码泄露、验证码告知他人）导致账号被盗、被冒用的，平台方不承担赔偿责任；用户发现账号异常应立即联系平台客服并申请冻结，平台方将配合采取合理补救措施。</p>
          <p class="usage-rules__paragraph">禁止恶意注册、使用账号，包括但不限于：批量注册账号、利用外挂 / 脚本自动注册账号、使用非本人真实信息注册账号、以违规牟利为目的注册多账号等，平台方可对上述违规账号采取限制功能、冻结、注销等措施，并保留追究法律责任的权利。</p>
          <p class="usage-rules__paragraph">账号连续 180 天未登录且无任何有效操作，平台方可根据运营需要对账号进行清理，清理前将通过预留联系方式通知用户，清理后账号内的未提现资产、未使用权益等将按本规范相关条款处理。</p>
        </div>
      </section>

      <section class="usage-rules__section">
        <div class="usage-rules__card">
          <h2 class="usage-rules__title">二、核心使用行为准则</h2>
          <h3 class="usage-rules__subtitle">（一）允许的行为</h3>
          <p class="usage-rules__paragraph">用户可在本 APP 功能范围内，依法、合规使用本 APP 提供的服务，包括但不限于信息浏览、内容发布、交易支付、互动交流等，同时享有本规范及平台相关规则约定的合法权益。</p>
          <h3 class="usage-rules__subtitle">（二）禁止的行为（红线条款）</h3>
          <p class="usage-rules__paragraph">用户不得利用本 APP 从事任何违反法律法规、损害平台方 / 其他用户合法权益、破坏平台运营秩序的行为，包括但不限于：</p>
          <p class="usage-rules__paragraph">违反国家政治、安全、公序良俗相关规定：发布 / 传播涉政、涉黄、涉赌、涉毒、涉恐、涉邪教内容，宣扬暴力、极端主义、民族歧视、地域歧视等，损害国家利益、社会公共利益。</p>
          <p class="usage-rules__paragraph">从事违法犯罪活动：利用本 APP 进行诈骗、洗钱、非法集资、倒卖个人信息、网络攻击、传播计算机病毒等，或为违法犯罪活动提供便利。</p>
          <p class="usage-rules__paragraph">破坏平台技术体系：使用外挂、破解版、第三方辅助工具、脚本等篡改本 APP 代码、绕过平台验证、劫持平台数据，干扰 APP 正常运行，或利用平台技术漏洞牟利、获取不正当权益。</p>
          <p class="usage-rules__paragraph">实施恶意操作：批量刷屏、刷赞、刷流量、刷评论，恶意投诉、诬告陷害其他用户 / 商家，利用平台活动「薅羊毛」、恶意套现，批量发送广告、垃圾信息、引流外链等。</p>
          <p class="usage-rules__paragraph">侵犯他人合法权益：辱骂、诽谤、恐吓、人肉搜索其他用户，盗用他人头像、昵称、作品、商标、专利等知识产权 / 人格权，泄露他人隐私、联系方式、商业秘密等。</p>
          <p class="usage-rules__paragraph">破坏平台运营生态：组织、煽动其他用户抵制平台、聚众闹事，与其他用户串通实施违规行为，冒用平台名义对外宣传、开展活动，或利用平台进行恶意竞争。其他违反法律法规、本规范及平台专项规则的行为。</p>
          <p class="usage-rules__paragraph">用户若实施上述禁止行为，平台方可根据违规情节轻重，采取警告、限流、限制 APP 功能、冻结账号资产、暂停账号使用、注销账号等措施，同时有权追回用户通过违规行为获取的不正当权益；若造成平台方 / 其他用户损失的，用户需承担赔偿责任；情节严重涉嫌犯罪的，平台方将向公安机关报案，追究其刑事责任。</p>
        </div>
      </section>

      <section class="usage-rules__section">
        <div class="usage-rules__card">
          <h2 class="usage-rules__title">三、内容发布与传播规则</h2>
          <p class="usage-rules__paragraph">本条款适用于所有在本 APP 内发布、传播文字、图片、视频、音频、链接等各类信息的用户（含普通用户、商家、创作者），若用户无内容发布权限，本条款自动适配其信息传播行为（如转发、评论）。</p>
          <p class="usage-rules__paragraph">用户发布的内容需为本人原创或已获得合法授权，保证内容的真实性、合法性，不得抄袭、盗用他人作品，不得侵犯任何第三方的知识产权、人格权等合法权益。若发布的内容涉及第三方权益，用户需提前取得授权，并承担因授权瑕疵导致的全部责任。</p>
          <p class="usage-rules__paragraph">禁止发布 / 传播虚假、误导性内容：包括但不限于虚假广告、谣言、虚假中奖信息、夸大宣传的商品 / 服务信息、伪造的资质 / 证明文件等。</p>
          <p class="usage-rules__paragraph">禁止发布 / 传播违规商业信息：包括但不限于无资质的医疗、金融、教育、保健品推广，非法外汇、虚拟货币交易信息，未经平台允许的线下引流、商业合作信息等。</p>
          <p class="usage-rules__paragraph">禁止发布 / 传播危害平台用户身心健康的内容：包括但不限于血腥、暴力、惊悚、低俗色情内容，诱导未成年人不良行为的内容等。</p>
          <p class="usage-rules__paragraph">平台方对用户发布的内容享有合理的审核权，可根据法律法规、本规范对内容进行筛选、审核、屏蔽、删除，对违规内容发布者采取本规范约定的处罚措施；用户对内容审核结果有异议的，可向平台客服申请复核。用户发布的内容仅代表其个人观点，与平台方无关；若内容违反法律法规、损害第三方权益，由发布者自行承担全部责任，平台方在接到合法通知后，将及时采取删除、屏蔽等必要措施。</p>
        </div>
      </section>

      <section class="usage-rules__section">
        <div class="usage-rules__card">
          <h2 class="usage-rules__title">四、权限与个人信息使用规则</h2>
          <p class="usage-rules__paragraph">平台方严格遵守《个人信息保护法》等相关法律法规，坚持最小必要、用户授权、安全保障的原则收集、使用、存储用户个人信息，同时保障用户对个人信息的查询、更正、删除、撤回授权等法定权利。</p>
          <p class="usage-rules__paragraph">权限获取：本 APP 将根据功能实现需要，向用户申请必要的系统权限（如定位、相机、麦克风、通讯录、存储等），所有权限申请均由用户主动授权，平台方不会强制要求用户授权非必要权限，用户可在手机系统或 APP 内的「设置 - 权限管理」中随时撤回、调整授权。</p>
          <p class="usage-rules__paragraph">信息收集：平台方仅收集实现 APP 功能所需的个人信息，包括但不限于注册手机号、登录密码、身份认证信息、设备信息、使用行为数据等，不收集与功能无关的敏感信息。</p>
          <p class="usage-rules__paragraph">信息使用：用户个人信息仅用于本 APP 的功能实现、服务优化、安全保障，包括但不限于账号登录、交易验证、客服服务、个性化推荐等，平台方不会将用户个人信息出售、出租给任何第三方；确需向第三方提供的，平台方将对第三方进行合规审核，并要求其承担信息保护责任，同时提前向用户告知并取得同意。</p>
          <p class="usage-rules__paragraph">信息安全：平台方将采取符合行业标准的技术防护措施（如加密存储、访问控制、数据备份等）保障用户个人信息安全，防止信息泄露、篡改、丢失；若发生信息安全事件，平台方将立即采取补救措施，并按相关法律法规要求及时通知用户、向监管部门报告。</p>
          <p class="usage-rules__paragraph">用户信息权利：用户可在 APP 内的「我的 - 设置 - 账号管理」等入口查询、更正、删除本人的个人信息，可申请注销账号并要求平台方删除相关信息（法律法规另有规定的除外）；平台方将在收到用户申请后的 7 个工作日内处理，并反馈处理结果。</p>
          <p class="usage-rules__paragraph">未成年人信息保护：本 APP 将落实未成年人保护相关规定，对未成年人的个人信息收集、使用进行严格限制，禁止向未成年人展示违规内容、诱导未成年人消费；若发现未成年人冒用成年人信息使用 APP，平台方可限制其功能使用，并联系法定监护人核实处理。</p>
        </div>
      </section>

      <section class="usage-rules__section">
        <div class="usage-rules__card">
          <h2 class="usage-rules__title">五、付费与交易规则</h2>
          <p class="usage-rules__paragraph">付费项目：本 APP 内的付费内容（如会员、智汇值、课程、虚拟道具）、商品 / 服务均标注明确价格、有效期、使用规则，价格调整将提前公示，用户付费前应仔细阅读相关说明，付费行为视为同意该项目的使用规则。</p>
          <p class="usage-rules__paragraph">支付方式：用户可通过平台官方指定的支付渠道（如微信支付、支付宝等）完成付费 / 交易，平台方不认可任何非官方支付渠道的交易行为，因非官方交易导致的损失由用户自行承担。</p>
          <p class="usage-rules__paragraph">退款政策：虚拟商品 / 服务（如会员、充值智汇值、线上课程）一经购买，除存在质量问题、平台故障或法律法规另有规定外，不支持无理由退款；若因平台原因导致无法使用，平台方可为用户办理退款或更换等值服务。实物商品遵循《消费者权益保护法》相关规定，支持七天无理由退货（法律另有规定的除外），退货时商品需保持完好，运费承担规则按商品详情页约定执行。</p>
          <p class="usage-rules__paragraph">退款申请：用户可在 APP 内的「我的 - 订单 / 付费记录」等入口提交退款申请，平台方将在 7 个工作日内审核，审核通过后按支付路径原路返还，退款到账时间以支付渠道规则为准。</p>
          <p class="usage-rules__paragraph">交易安全：禁止利用本 APP 的交易功能进行虚假交易、套现、洗钱等违规行为，平台方可对异常交易进行冻结、核实，核实期间将暂停相关交易功能，核实无误后恢复使用。</p>
          <p class="usage-rules__paragraph">资产保障：用户账号内的充值余额、智汇值、虚拟资产、优惠券等均仅限本人使用，不得转让、提现（另有约定的除外）；账号冻结、注销后，未使用的资产将按本规范相关条款处理，因用户违规导致账号被处理的，资产不予退还。</p>
        </div>
      </section>

      <section class="usage-rules__section">
        <div class="usage-rules__card">
          <h2 class="usage-rules__title">六、用户与平台方的权责界定</h2>
          <h3 class="usage-rules__subtitle">（一）平台方的权利与义务</h3>
          <p class="usage-rules__paragraph">权利：依据本规范及相关规则，对用户的使用行为、发布内容进行审核、管理，对违规用户采取相应处罚措施；根据法律法规更新、平台运营需要，调整 APP 功能、更新服务规则、修订本规范；在必要情况下（如配合监管部门调查、保障平台安全），限制、暂停部分用户的 APP 使用权限，或中断部分服务；法律法规及本规范约定的其他权利。</p>
          <p class="usage-rules__paragraph">义务：保障 APP 的正常运行，及时修复技术故障、优化服务体验；严格保护用户的个人信息和数据安全，履行信息保护义务；为用户提供便捷的客服渠道（如在线客服、客服电话、意见反馈入口），及时处理用户的咨询、投诉、申诉，在 7 个工作日内反馈处理结果；依法、合规向用户提供服务，保障用户的合法权益；法律法规及本规范约定的其他义务。</p>
          <h3 class="usage-rules__subtitle">（二）用户的权利与义务</h3>
          <p class="usage-rules__paragraph">权利：在本 APP 功能范围内，依法使用平台提供的各项服务，享有公平、公正的使用体验；对个人信息享有查询、更正、删除、撤回授权等权利；对平台的服务、规则提出建议和意见，对违规行为进行投诉、举报；法律法规及本规范约定的其他权利。</p>
          <p class="usage-rules__paragraph">义务：严格遵守本规范及平台的各项专项规则，依法、合规使用 APP；对自己的账号操作、行为及产生的后果承担全部责任，妥善保管账号及个人信息；配合平台方的合规审核、安全验证、违规调查等工作；不得利用平台的服务损害平台方 / 其他用户的合法权益；法律法规及本规范约定的其他义务。</p>
          <h3 class="usage-rules__subtitle">（三）免责条款</h3>
          <p class="usage-rules__paragraph">因不可抗力（如地震、洪水、火灾、网络故障、服务器故障、政府监管措施等）导致平台方无法正常提供服务，或用户产生损失的，平台方不承担赔偿责任，但将在不可抗力发生后及时采取补救措施，并通知用户。</p>
          <p class="usage-rules__paragraph">因用户自身原因（如密码泄露、信息虚假、操作失误、未及时更新信息）导致的账号问题、权益损失，平台方不承担赔偿责任。本 APP 内的第三方链接、广告、内容仅代表第三方观点，平台方仅提供展示服务，不承担担保责任。平台方根据法律法规、监管要求或本规范对用户账号、内容、资产采取处理措施的，因处理措施产生的合理损失，平台方不承担赔偿责任。法律法规规定的其他免责情形。</p>
        </div>
      </section>

      <section class="usage-rules__section">
        <div class="usage-rules__card">
          <h2 class="usage-rules__title">七、违规处理与申诉规则</h2>
          <p class="usage-rules__paragraph">平台方对用户违规行为的认定，以 APP 内的使用记录、数据信息、第三方投诉证据等为依据，违规处理决定将通过 APP 内弹窗、消息通知、预留联系方式等方式告知用户。</p>
          <p class="usage-rules__paragraph">用户对违规处理决定有异议的，可在收到处理通知后的 7 个工作日内，通过 APP 内的「申诉入口」或客服渠道提交申诉申请，并提供相关证明材料；平台方将在收到申诉后的 7 个工作日内复核，并将复核结果告知用户。</p>
          <p class="usage-rules__paragraph">复核结果为撤销处罚的，平台方将立即恢复用户的账号功能、资产权益；复核结果为维持处罚的，用户不得再次以同一理由申诉，平台方的处理决定为最终结果。用户逾期未申诉的，视为认可平台方的违规处理决定，处理决定将正式生效。</p>
        </div>
      </section>

      <section class="usage-rules__section">
        <div class="usage-rules__card">
          <h2 class="usage-rules__title">八、账号注销规则</h2>
          <p class="usage-rules__paragraph">用户可在 APP 内的「我的 - 设置 - 账号注销/注销说明」中主动申请注销账号，注销前需完成账号内的资产提现、订单结算、债务清偿等事宜，注销申请提交后，平台方将在 7 个工作日内审核，审核通过后账号将被永久注销，无法恢复。</p>
          <p class="usage-rules__paragraph">账号注销后，平台方将按照法律法规要求删除用户的个人信息（法律法规另有规定需留存的除外），账号内的未提现资产、未使用权益将自动作废，平台方不承担返还责任。</p>
          <p class="usage-rules__paragraph">若用户账号存在违规行为、未结清的交易 / 债务、未处理的投诉 / 申诉，平台方可拒绝其注销申请，直至用户处理完毕相关事宜。</p>
        </div>
      </section>

      <section class="usage-rules__section">
        <div class="usage-rules__card">
          <h2 class="usage-rules__title">九、争议解决</h2>
          <p class="usage-rules__paragraph">用户与平台方之间因本 APP 使用产生的任何争议，应首先通过友好协商解决；协商不成的，任何一方均有权向平台方住所地有管辖权的人民法院提起诉讼。</p>
          <p class="usage-rules__paragraph">本规范的订立、履行、解释及争议解决，均适用中华人民共和国法律（港澳台地区法律除外）。</p>
        </div>
      </section>

      <section class="usage-rules__section">
        <div class="usage-rules__card">
          <h2 class="usage-rules__title">十、其他条款</h2>
          <p class="usage-rules__paragraph">本规范为智汇社（AI智汇社）APP 用户使用的核心规则，平台方制定的专项规则（如会员规则、活动规则、分销与提现规则等）均为本规范的补充条款，与本规范具有同等法律效力；若专项规则与本规范不一致，以专项规则为准（专项规则违反法律法规的除外）。</p>
          <p class="usage-rules__paragraph">本规范中的未尽事宜，平台方将通过官方公告、APP 内通知等方式补充，补充内容自公示之日起生效。</p>
          <p class="usage-rules__paragraph">本规范自 2025 年 2 月 4 日起正式生效。</p>
          <div class="usage-rules__footer">
            <span>制定方：吉林省爱智汇人工智能科技有限公司</span>
            <span>公司地址：吉林省长春市高新区越达路107号人工智能人才孵化基地</span>
            <span>客服电话：19944894487</span>
            <span>官方邮箱：502319984@qq.com</span>
          </div>
        </div>
      </section>
    </SettingsPageLayout>
  </div>
</template>

<script setup lang="ts">
import SettingsPageLayout from './SettingsPageLayout.vue'
</script>

<style lang="scss" scoped>
@use '@/styles/_breakpoints.scss' as bp;

.usage-rules-page {
  min-height: 100vh;
}

.usage-rules__intro {
  background-color: var(--el-bg-color);
  border: var(--unified-border);
  border-radius: var(--global-border-radius);
  padding: 14px 12px;
  margin-bottom: 16px;

  @include bp.min-width('tablet') {
    padding: 18px 16px;
    margin-bottom: 20px;
  }
}

.usage-rules__section {
  margin-bottom: 16px;

  @include bp.min-width('tablet') {
    margin-bottom: 20px;
  }
}

.usage-rules__card {
  background-color: var(--el-bg-color);
  border: var(--unified-border);
  border-radius: var(--global-border-radius);
  padding: 14px 12px;

  @include bp.min-width('tablet') {
    padding: 18px 16px;
  }
}

.usage-rules__title {
  font-size: 16px;
  font-weight: 600;
  color: var(--el-text-color-primary);
  margin: 0 0 12px;
  line-height: 1.4;

  @include bp.min-width('tablet') {
    font-size: 17px;
    margin-bottom: 14px;
  }
}

.usage-rules__subtitle {
  font-size: 14px;
  font-weight: 600;
  color: var(--el-text-color-primary);
  margin: 12px 0 8px;

  @include bp.min-width('tablet') {
    font-size: 15px;
  }
}

.usage-rules__paragraph {
  font-size: 13px;
  color: var(--el-text-color-regular);
  line-height: 1.75;
  text-align: justify;
  margin: 0 0 10px;

  @include bp.min-width('tablet') {
    font-size: 14px;
    margin-bottom: 12px;
  }
}

.usage-rules__intro .usage-rules__paragraph:last-child {
  margin-bottom: 0;
}

.usage-rules__card .usage-rules__paragraph:last-of-type {
  margin-bottom: 0;
}

.usage-rules__footer {
  font-size: 12px;
  color: var(--el-text-color-secondary);
  line-height: 1.8;
  margin-top: 16px;
  padding-top: 12px;
  border-top: 1px solid var(--el-border-color-extra-light);
  display: flex;
  flex-direction: column;

  @include bp.min-width('tablet') {
    font-size: 13px;
    margin-top: 20px;
    padding-top: 14px;
  }

  span {
    display: block;
    margin-bottom: 4px;
  }

  span:last-child {
    margin-bottom: 0;
  }
}
</style>

// apps/miniapp-taro/src/pages/about/usage-rules/index.tsx
import { View, Text, ScrollView } from '@tarojs/components'
import Taro, { useDidShow } from '@tarojs/taro'
import { useCallback } from 'react'
import { useI18n } from '@/i18n'

interface UsageBlock {
  subtitle?: string
  text: string
}

interface UsageSection {
  title: string
  blocks: UsageBlock[]
}

const FOOTER_ITEMS = [
  '制定方：吉林省爱智汇人工智能科技有限公司',
  '公司地址：吉林省长春市高新区越达路107号人工智能人才孵化基地',
  '客服电话：19944894487',
  '官方邮箱：[REDACTED-EMAIL]',
]

export default function UsageRules() {
  const { t } = useI18n()
  const tt = useCallback(
    (k: string, fb: string) => {
      const v = t(k)
      return v === k ? fb : v
    },
    [t],
  )

  useDidShow(() => {
    Taro.setNavigationBarTitle({ title: tt('about.usageRules.title', '使用规范') })
  })

  const introParagraphs = [
    tt(
      'about.usageRules.introP1',
      '本规范依据《中华人民共和国民法典》《中华人民共和国网络安全法》《中华人民共和国个人信息保护法》《互联网信息服务管理办法》等相关法律法规制定，旨在规范用户使用本 APP 的行为，保障平台运营秩序、用户合法权益及数据安全。凡注册、登录、使用本 APP 的自然人、法人或其他组织（以下统称「用户」），均视为已阅读、理解并同意本规范全部内容；若用户不同意本规范，应立即停止使用本 APP。',
    ),
    tt(
      'about.usageRules.introP2',
      '本规范由【吉林省爱智汇人工智能科技有限公司】（以下统称「平台方」）制定并负责解释，平台方可根据法律法规更新、平台运营需要对本规范进行修订，修订后的规范将通过 APP 内公示、弹窗等方式通知用户，公示期满后即生效，用户继续使用本 APP 视为同意修订后的内容。',
    ),
  ]

  const sections: UsageSection[] = [
    {
      title: tt('about.usageRules.s1.title', '一、账号使用规则'),
      blocks: [
        {
          text: tt(
            'about.usageRules.s1.p1',
            '用户需通过本 APP 官方指定渠道（手机号 / 第三方授权等）注册账号，注册时应提供真实、准确、完整的身份信息及联系方式，若信息发生变更，需及时在 APP 内更新。因虚假、失效信息导致的账号使用问题、权益损失，由用户自行承担。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s1.p2',
            '账号所有权归平台方所有，用户仅获得账号的有限使用权，仅限本人使用，禁止以出租、出借、售卖、转让、赠与等方式处分账号，禁止将账号交由他人代为操作。若发生上述行为，平台方可冻结 / 注销账号，由此产生的一切损失由用户承担。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s1.p3',
            '用户需妥善保管账号密码、验证码、人脸识别信息等登录凭证，对账号下的所有操作、行为及产生的后果承担全部责任。因用户自身原因（如密码泄露、验证码告知他人）导致账号被盗、被冒用的，平台方不承担赔偿责任；用户发现账号异常应立即联系平台客服并申请冻结，平台方将配合采取合理补救措施。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s1.p4',
            '禁止恶意注册、使用账号，包括但不限于：批量注册账号、利用外挂 / 脚本自动注册账号、使用非本人真实信息注册账号、以违规牟利为目的注册多账号等，平台方可对上述违规账号采取限制功能、冻结、注销等措施，并保留追究法律责任的权利。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s1.p5',
            '账号连续 180 天未登录且无任何有效操作，平台方可根据运营需要对账号进行清理，清理前将通过预留联系方式通知用户，清理后账号内的未提现资产、未使用权益等将按本规范相关条款处理。',
          ),
        },
      ],
    },
    {
      title: tt('about.usageRules.s2.title', '二、核心使用行为准则'),
      blocks: [
        {
          subtitle: tt('about.usageRules.s2.sub1', '（一）允许的行为'),
          text: tt(
            'about.usageRules.s2.p1',
            '用户可在本 APP 功能范围内，依法、合规使用本 APP 提供的服务，包括但不限于信息浏览、内容发布、交易支付、互动交流等，同时享有本规范及平台相关规则约定的合法权益。',
          ),
        },
        {
          subtitle: tt('about.usageRules.s2.sub2', '（二）禁止的行为（红线条款）'),
          text: tt(
            'about.usageRules.s2.p2',
            '用户不得利用本 APP 从事任何违反法律法规、损害平台方 / 其他用户合法权益、破坏平台运营秩序的行为，包括但不限于：',
          ),
        },
        {
          text: tt(
            'about.usageRules.s2.p3',
            '违反国家政治、安全、公序良俗相关规定：发布 / 传播涉政、涉黄、涉赌、涉毒、涉恐、涉邪教内容，宣扬暴力、极端主义、民族歧视、地域歧视等，损害国家利益、社会公共利益。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s2.p4',
            '从事违法犯罪活动：利用本 APP 进行诈骗、洗钱、非法集资、倒卖个人信息、网络攻击、传播计算机病毒等，或为违法犯罪活动提供便利。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s2.p5',
            '破坏平台技术体系：使用外挂、破解版、第三方辅助工具、脚本等篡改本 APP 代码、绕过平台验证、劫持平台数据，干扰 APP 正常运行，或利用平台技术漏洞牟利、获取不正当权益。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s2.p6',
            '实施恶意操作：批量刷屏、刷赞、刷流量、刷评论，恶意投诉、诬告陷害其他用户 / 商家，利用平台活动「薅羊毛」、恶意套现，批量发送广告、垃圾信息、引流外链等。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s2.p7',
            '侵犯他人合法权益：辱骂、诽谤、恐吓、人肉搜索其他用户，盗用他人头像、昵称、作品、商标、专利等知识产权 / 人格权，泄露他人隐私、联系方式、商业秘密等。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s2.p8',
            '破坏平台运营生态：组织、煽动其他用户抵制平台、聚众闹事，与其他用户串通实施违规行为，冒用平台名义对外宣传、开展活动，或利用平台进行恶意竞争。其他违反法律法规、本规范及平台专项规则的行为。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s2.p9',
            '用户若实施上述禁止行为，平台方可根据违规情节轻重，采取警告、限流、限制 APP 功能、冻结账号资产、暂停账号使用、注销账号等措施，同时有权追回用户通过违规行为获取的不正当权益；若造成平台方 / 其他用户损失的，用户需承担赔偿责任；情节严重涉嫌犯罪的，平台方将向公安机关报案，追究其刑事责任。',
          ),
        },
      ],
    },
    {
      title: tt('about.usageRules.s3.title', '三、内容发布与传播规则'),
      blocks: [
        {
          text: tt(
            'about.usageRules.s3.p1',
            '本条款适用于所有在本 APP 内发布、传播文字、图片、视频、音频、链接等各类信息的用户（含普通用户、商家、创作者），若用户无内容发布权限，本条款自动适配其信息传播行为（如转发、评论）。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s3.p2',
            '用户发布的内容需为本人原创或已获得合法授权，保证内容的真实性、合法性，不得抄袭、盗用他人作品，不得侵犯任何第三方的知识产权、人格权等合法权益。若发布的内容涉及第三方权益，用户需提前取得授权，并承担因授权瑕疵导致的全部责任。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s3.p3',
            '禁止发布 / 传播虚假、误导性内容：包括但不限于虚假广告、谣言、虚假中奖信息、夸大宣传的商品 / 服务信息、伪造的资质 / 证明文件等。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s3.p4',
            '禁止发布 / 传播违规商业信息：包括但不限于无资质的医疗、金融、教育、保健品推广，非法外汇、虚拟货币交易信息，未经平台允许的线下引流、商业合作信息等。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s3.p5',
            '禁止发布 / 传播危害平台用户身心健康的内容：包括但不限于血腥、暴力、惊悚、低俗色情内容，诱导未成年人不良行为的内容等。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s3.p6',
            '平台方对用户发布的内容享有合理的审核权，可根据法律法规、本规范对内容进行筛选、审核、屏蔽、删除，对违规内容发布者采取本规范约定的处罚措施；用户对内容审核结果有异议的，可向平台客服申请复核。用户发布的内容仅代表其个人观点，与平台方无关；若内容违反法律法规、损害第三方权益，由发布者自行承担全部责任，平台方在接到合法通知后，将及时采取删除、屏蔽等必要措施。',
          ),
        },
      ],
    },
    {
      title: tt('about.usageRules.s4.title', '四、权限与个人信息使用规则'),
      blocks: [
        {
          text: tt(
            'about.usageRules.s4.p1',
            '平台方严格遵守《个人信息保护法》等相关法律法规，坚持最小必要、用户授权、安全保障的原则收集、使用、存储用户个人信息，同时保障用户对个人信息的查询、更正、删除、撤回授权等法定权利。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s4.p2',
            '权限获取：本 APP 将根据功能实现需要，向用户申请必要的系统权限（如定位、相机、麦克风、通讯录、存储等），所有权限申请均由用户主动授权，平台方不会强制要求用户授权非必要权限，用户可在手机系统或 APP 内的「设置 - 权限管理」中随时撤回、调整授权。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s4.p3',
            '信息收集：平台方仅收集实现 APP 功能所需的个人信息，包括但不限于注册手机号、登录密码、身份认证信息、设备信息、使用行为数据等，不收集与功能无关的敏感信息。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s4.p4',
            '信息使用：用户个人信息仅用于本 APP 的功能实现、服务优化、安全保障，包括但不限于账号登录、交易验证、客服服务、个性化推荐等，平台方不会将用户个人信息出售、出租给任何第三方；确需向第三方提供的，平台方将对第三方进行合规审核，并要求其承担信息保护责任，同时提前向用户告知并取得同意。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s4.p5',
            '信息安全：平台方将采取符合行业标准的技术防护措施（如加密存储、访问控制、数据备份等）保障用户个人信息安全，防止信息泄露、篡改、丢失；若发生信息安全事件，平台方将立即采取补救措施，并按相关法律法规要求及时通知用户、向监管部门报告。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s4.p6',
            '用户信息权利：用户可在 APP 内的「我的 - 设置 - 账号管理」等入口查询、更正、删除本人的个人信息，可申请注销账号并要求平台方删除相关信息（法律法规另有规定的除外）；平台方将在收到用户申请后的 7 个工作日内处理，并反馈处理结果。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s4.p7',
            '未成年人信息保护：本 APP 将落实未成年人保护相关规定，对未成年人的个人信息收集、使用进行严格限制，禁止向未成年人展示违规内容、诱导未成年人消费；若发现未成年人冒用成年人信息使用 APP，平台方可限制其功能使用，并联系法定监护人核实处理。',
          ),
        },
      ],
    },
    {
      title: tt('about.usageRules.s5.title', '五、付费与交易规则'),
      blocks: [
        {
          text: tt(
            'about.usageRules.s5.p1',
            '付费项目：本 APP 内的付费内容（如会员、智汇值、课程、虚拟道具）、商品 / 服务均标注明确价格、有效期、使用规则，价格调整将提前公示，用户付费前应仔细阅读相关说明，付费行为视为同意该项目的使用规则。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s5.p2',
            '支付方式：用户可通过平台官方指定的支付渠道（如微信支付、支付宝等）完成付费 / 交易，平台方不认可任何非官方支付渠道的交易行为，因非官方交易导致的损失由用户自行承担。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s5.p3',
            '退款政策：虚拟商品 / 服务（如会员、充值智汇值、线上课程）一经购买，除存在质量问题、平台故障或法律法规另有规定外，不支持无理由退款；若因平台原因导致无法使用，平台方可为用户办理退款或更换等值服务。实物商品遵循《消费者权益保护法》相关规定，支持七天无理由退货（法律另有规定的除外），退货时商品需保持完好，运费承担规则按商品详情页约定执行。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s5.p4',
            '退款申请：用户可在 APP 内的「我的 - 订单 / 付费记录」等入口提交退款申请，平台方将在 7 个工作日内审核，审核通过后按支付路径原路返还，退款到账时间以支付渠道规则为准。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s5.p5',
            '交易安全：禁止利用本 APP 的交易功能进行虚假交易、套现、洗钱等违规行为，平台方可对异常交易进行冻结、核实，核实期间将暂停相关交易功能，核实无误后恢复使用。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s5.p6',
            '资产保障：用户账号内的充值余额、智汇值、虚拟资产、优惠券等均仅限本人使用，不得转让、提现（另有约定的除外）；账号冻结、注销后，未使用的资产将按本规范相关条款处理，因用户违规导致账号被处理的，资产不予退还。',
          ),
        },
      ],
    },
    {
      title: tt('about.usageRules.s6.title', '六、用户与平台方的权责界定'),
      blocks: [
        {
          subtitle: tt('about.usageRules.s6.sub1', '（一）平台方的权利与义务'),
          text: tt(
            'about.usageRules.s6.p1',
            '权利：依据本规范及相关规则，对用户的使用行为、发布内容进行审核、管理，对违规用户采取相应处罚措施；根据法律法规更新、平台运营需要，调整 APP 功能、更新服务规则、修订本规范；在必要情况下（如配合监管部门调查、保障平台安全），限制、暂停部分用户的 APP 使用权限，或中断部分服务；法律法规及本规范约定的其他权利。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s6.p2',
            '义务：保障 APP 的正常运行，及时修复技术故障、优化服务体验；严格保护用户的个人信息和数据安全，履行信息保护义务；为用户提供便捷的客服渠道（如在线客服、客服电话、意见反馈入口），及时处理用户的咨询、投诉、申诉，在 7 个工作日内反馈处理结果；依法、合规向用户提供服务，保障用户的合法权益；法律法规及本规范约定的其他义务。',
          ),
        },
        {
          subtitle: tt('about.usageRules.s6.sub2', '（二）用户的权利与义务'),
          text: tt(
            'about.usageRules.s6.p3',
            '权利：在本 APP 功能范围内，依法使用平台提供的各项服务，享有公平、公正的使用体验；对个人信息享有查询、更正、删除、撤回授权等权利；对平台的服务、规则提出建议和意见，对违规行为进行投诉、举报；法律法规及本规范约定的其他权利。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s6.p4',
            '义务：严格遵守本规范及平台的各项专项规则，依法、合规使用 APP；对自己的账号操作、行为及产生的后果承担全部责任，妥善保管账号及个人信息；配合平台方的合规审核、安全验证、违规调查等工作；不得利用平台的服务损害平台方 / 其他用户的合法权益；法律法规及本规范约定的其他义务。',
          ),
        },
        {
          subtitle: tt('about.usageRules.s6.sub3', '（三）免责条款'),
          text: tt(
            'about.usageRules.s6.p5',
            '因不可抗力（如地震、洪水、火灾、网络故障、服务器故障、政府监管措施等）导致平台方无法正常提供服务，或用户产生损失的，平台方不承担赔偿责任，但将在不可抗力发生后及时采取补救措施，并通知用户。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s6.p6',
            '因用户自身原因（如密码泄露、信息虚假、操作失误、未及时更新信息）导致的账号问题、权益损失，平台方不承担赔偿责任。本 APP 内的第三方链接、广告、内容仅代表第三方观点，平台方仅提供展示服务，不承担担保责任。平台方根据法律法规、监管要求或本规范对用户账号、内容、资产采取处理措施的，因处理措施产生的合理损失，平台方不承担赔偿责任。法律法规规定的其他免责情形。',
          ),
        },
      ],
    },
    {
      title: tt('about.usageRules.s7.title', '七、违规处理与申诉规则'),
      blocks: [
        {
          text: tt(
            'about.usageRules.s7.p1',
            '平台方对用户违规行为的认定，以 APP 内的使用记录、数据信息、第三方投诉证据等为依据，违规处理决定将通过 APP 内弹窗、消息通知、预留联系方式等方式告知用户。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s7.p2',
            '用户对违规处理决定有异议的，可在收到处理通知后的 7 个工作日内，通过 APP 内的「申诉入口」或客服渠道提交申诉申请，并提供相关证明材料；平台方将在收到申诉后的 7 个工作日内复核，并将复核结果告知用户。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s7.p3',
            '复核结果为撤销处罚的，平台方将立即恢复用户的账号功能、资产权益；复核结果为维持处罚的，用户不得再次以同一理由申诉，平台方的处理决定为最终结果。用户逾期未申诉的，视为认可平台方的违规处理决定，处理决定将正式生效。',
          ),
        },
      ],
    },
    {
      title: tt('about.usageRules.s8.title', '八、账号注销规则'),
      blocks: [
        {
          text: tt(
            'about.usageRules.s8.p1',
            '用户可在 APP 内的「我的 - 设置 - 账号注销/注销说明」中主动申请注销账号，注销前需完成账号内的资产提现、订单结算、债务清偿等事宜，注销申请提交后，平台方将在 7 个工作日内审核，审核通过后账号将被永久注销，无法恢复。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s8.p2',
            '账号注销后，平台方将按照法律法规要求删除用户的个人信息（法律法规另有规定需留存的除外），账号内的未提现资产、未使用权益将自动作废，平台方不承担返还责任。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s8.p3',
            '若用户账号存在违规行为、未结清的交易 / 债务、未处理的投诉 / 申诉，平台方可拒绝其注销申请，直至用户处理完毕相关事宜。',
          ),
        },
      ],
    },
    {
      title: tt('about.usageRules.s9.title', '九、争议解决'),
      blocks: [
        {
          text: tt(
            'about.usageRules.s9.p1',
            '用户与平台方之间因本 APP 使用产生的任何争议，应首先通过友好协商解决；协商不成的，任何一方均有权向平台方住所地有管辖权的人民法院提起诉讼。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s9.p2',
            '本规范的订立、履行、解释及争议解决，均适用中华人民共和国法律（港澳台地区法律除外）。',
          ),
        },
      ],
    },
    {
      title: tt('about.usageRules.s10.title', '十、其他条款'),
      blocks: [
        {
          text: tt(
            'about.usageRules.s10.p1',
            '本规范为智汇社（AI智汇社）APP 用户使用的核心规则，平台方制定的专项规则（如会员规则、活动规则、分销与提现规则等）均为本规范的补充条款，与本规范具有同等法律效力；若专项规则与本规范不一致，以专项规则为准（专项规则违反法律法规的除外）。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s10.p2',
            '本规范中的未尽事宜，平台方将通过官方公告、APP 内通知等方式补充，补充内容自公示之日起生效。',
          ),
        },
        {
          text: tt(
            'about.usageRules.s10.p3',
            '本规范自 2025 年 2 月 4 日起正式生效。',
          ),
        },
      ],
    },
  ]

  return (
    <ScrollView className="h-screen bg-background" scrollY>
      <View className="px-[24rpx] pt-[24rpx] pb-[60rpx]">
        <View className="mb-[32rpx] py-[28rpx] px-[24rpx] bg-card rounded-[16rpx] flex flex-col gap-[16rpx]">
          {introParagraphs.map((p, i) => (
            <Text key={i} className="block text-[26rpx] text-muted-foreground leading-[1.75] text-justify">
              {p}
            </Text>
          ))}
        </View>

        {sections.map((section, sIdx) => (
          <View key={sIdx} className="mb-[32rpx] py-[28rpx] px-[24rpx] bg-card rounded-[16rpx]">
            <Text className="block text-[32rpx] font-semibold text-foreground mb-[20rpx] leading-[1.4]">{section.title}</Text>
            {section.blocks.map((block, bIdx) => (
              <View key={bIdx} className="mb-[16rpx]">
                {block.subtitle ? (
                  <Text className="block text-[28rpx] font-semibold text-foreground mb-[12rpx] mt-[8rpx]">{block.subtitle}</Text>
                ) : null}
                <Text className="block text-[26rpx] text-muted-foreground leading-[1.75] text-justify">{block.text}</Text>
              </View>
            ))}
            {sIdx === sections.length - 1 ? (
              <View className="mt-[24rpx] pt-[20rpx] flex flex-col gap-[8rpx]">
                {FOOTER_ITEMS.map((item, fIdx) => (
                  <Text key={fIdx} className="block text-[24rpx] text-muted-foreground leading-[1.8]">
                    {item}
                  </Text>
                ))}
              </View>
            ) : null}
          </View>
        ))}
      </View>
    </ScrollView>
  )
}
