// apps/miniapp-taro/src/pages/circle/index.tsx
import { View, Text, Image } from '@tarojs/components'
import Taro, { useReachBottom } from '@tarojs/taro'
import { useState, useCallback, useEffect } from 'react'
import { getCircleList, type Circle } from '@/api'
import './index.css'

export default function CircleIndexPage() {
  const [list, setList] = useState<Circle[]>([])
  const [loading, setLoading] = useState(false)
  const [tab, setTab] = useState('recommend')
  const [page, setPage] = useState(1)
  const [hasMore, setHasMore] = useState(true)

  const load = useCallback(async (reset = false) => {
    if (loading) return
    let curPage = page
    if (reset) { curPage = 1; setHasMore(true); setList([]); setPage(1) }
    if (!hasMore && !reset) return
    setLoading(true)
    try {
      const res = await getCircleList({ page: curPage, pageSize: 10 })
      const newList = res.list || []
      setList(prev => reset ? newList : [...prev, ...newList])
      setHasMore((reset ? newList.length : list.length + newList.length) < res.total)
      setPage(curPage + 1)
    } finally {
      setLoading(false)
    }
  }, [loading, page, hasMore, list.length])

  const switchTab = useCallback((t: string) => {
    setTab(t)
    load(true)
  }, [load])

  const goDetail = useCallback((id: string | number) => {
    Taro.navigateTo({ url: `/pages/circle/detail?id=${id}` })
  }, [])

  const goCreate = useCallback(() => {
    Taro.navigateTo({ url: '/pages/circle/create' })
  }, [])

  useReachBottom(() => load())

  useEffect(() => {
    load(true)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <View className="page">
      <View className="tabs">
        <Text className={`tab${tab === 'recommend' ? ' active' : ''}`} onClick={() => switchTab('recommend')}>推荐</Text>
        <Text className={`tab${tab === 'follow' ? ' active' : ''}`} onClick={() => switchTab('follow')}>关注</Text>
        <Text className={`tab${tab === 'hot' ? ' active' : ''}`} onClick={() => switchTab('hot')}>热门</Text>
      </View>

      {list.length ? (
        <View className="list">
          {list.map(c => (
            <View key={c.id} className="item" onClick={() => goDetail(c.id)}>
              <View className="user">
                <Image className="avatar" src={c.avatar || '/static/default-avatar.png'} mode="aspectFill" />
                <Text className="name">{c.author}</Text>
                <Text className="time">{c.createTime}</Text>
              </View>
              <Text className="title">{c.title}</Text>
              <Text className="content">{c.content}</Text>
              {c.images?.length ? (
                <View className="images">
                  {c.images.slice(0, 3).map((img, i) => (
                    <Image key={i} className="img" src={img} mode="aspectFill" />
                  ))}
                </View>
              ) : null}
              <View className="actions">
                <Text className="action">♡ {c.likes || 0}</Text>
                <Text className="action">💬 {c.comments || 0}</Text>
              </View>
            </View>
          ))}
        </View>
      ) : null}

      {!loading && !list.length ? (
        <View className="empty"><Text>暂无内容</Text></View>
      ) : null}

      <View className="fab" onClick={goCreate}>+</View>
    </View>
  )
}

// apps/miniapp/pages/circle/index.vue
<template>
  <view class="page">
    <view class="tabs">
      <text class="tab" :class="{ active: tab === 'recommend' }" @tap="switchTab('recommend')">推荐</text>
      <text class="tab" :class="{ active: tab === 'follow' }" @tap="switchTab('follow')">关注</text>
      <text class="tab" :class="{ active: tab === 'hot' }" @tap="switchTab('hot')">热门</text>
    </view>
    <view class="list" v-if="list.length">
      <view class="item" v-for="c in list" :key="c.id" @tap="goDetail(c.id)">
        <view class="user">
          <image class="avatar" :src="c.avatar || '/static/default-avatar.png'" mode="aspectFill" />
          <text class="name">{{ c.author }}</text>
          <text class="time">{{ c.createTime }}</text>
        </view>
        <text class="title">{{ c.title }}</text>
        <text class="content">{{ c.content }}</text>
        <view class="images" v-if="c.images?.length">
          <image class="img" v-for="(img, i) in c.images.slice(0, 3)" :key="i" :src="img" mode="aspectFill" />
        </view>
        <view class="actions">
          <text class="action">♡ {{ c.likes || 0 }}</text>
          <text class="action">💬 {{ c.comments || 0 }}</text>
        </view>
      </view>
    </view>
    <view class="empty" v-if="!loading && !list.length"><text>暂无内容</text></view>
    <view class="fab" @tap="goCreate">+</view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onReachBottom } from '@dcloudio/uni-app'
import { getCircleList, type Circle } from '@/api'

const list = ref<Circle[]>([])
const loading = ref(false)
const tab = ref('recommend')
const page = ref(1)
const hasMore = ref(true)

async function load(reset = false) {
  if (loading.value) return
  if (reset) { page.value = 1; hasMore.value = true; list.value = [] }
  if (!hasMore.value) return
  loading.value = true
  try {
    const res = await getCircleList({ page: page.value, pageSize: 10 })
    list.value.push(...(res.list || []))
    hasMore.value = list.value.length < res.total
    page.value++
  } finally { loading.value = false }
}
function switchTab(t: string) { tab.value = t; load(true) }
function goDetail(id: string | number) { uni.navigateTo({ url: `/pages/circle/detail?id=${id}` }) }
function goCreate() { uni.navigateTo({ url: '/pages/circle/create' }) }
onReachBottom(() => load())
load()
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; padding-bottom: 120rpx; }
.tabs { display: flex; background: #fff; position: sticky; top: 0; z-index: 1; }
.tab { flex: 1; text-align: center; font-size: 28rpx; color: #666; padding: 24rpx 0; }
.tab.active { color: #007aff; font-weight: 600; }
.list { padding: 24rpx; }
.item { background: #fff; border-radius: 16rpx; padding: 24rpx; margin-bottom: 24rpx; }
.user { display: flex; align-items: center; }
.avatar { width: 60rpx; height: 60rpx; border-radius: 50%; background: #f5f5f5; }
.name { margin-left: 16rpx; font-size: 26rpx; color: #333; font-weight: 600; }
.time { margin-left: auto; font-size: 22rpx; color: #999; }
.title { display: block; font-size: 30rpx; color: #333; font-weight: 600; margin: 16rpx 0; }
.content { font-size: 26rpx; color: #666; line-height: 1.6; }
.images { display: flex; gap: 8rpx; margin-top: 16rpx; }
.img { width: 200rpx; height: 200rpx; border-radius: 8rpx; background: #f5f5f5; }
.actions { display: flex; gap: 32rpx; margin-top: 24rpx; padding-top: 16rpx; border-top: 2rpx solid #f5f5f5; }
.action { font-size: 24rpx; color: #999; }
.empty { text-align: center; padding: 120rpx 0; color: #999; }
.fab { position: fixed; right: 40rpx; bottom: 60rpx; width: 100rpx; height: 100rpx; line-height: 100rpx; text-align: center; background: #007aff; color: #fff; border-radius: 50%; font-size: 60rpx; box-shadow: 0 4rpx 20rpx rgba(0,122,255,.4); }
</style>
