// client/src/open-platform/components/common/VirtualList.vue
<template>
  <div class="virtual-list" :style="{ height: containerHeight + 'px' }">
    <div
      class="virtual-list-container"
      :style="{ height: totalHeight + 'px' }"
      @scroll="handleScroll"
      ref="containerRef"
    >
      <div
        class="virtual-list-content"
        :style="{ transform: `translateY(${offsetY}px)` }"
      >
        <div
          v-for="item in visibleItems"
          :key="getItemKey(item)"
          class="virtual-list-item"
          :style="{ height: itemHeight + 'px' }"
        >
          <slot :item="item" :index="item.index" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'

interface VirtualListItem {
  id?: string | number
  index?: number
  [key: string]: any
}

interface Props {
  items: VirtualListItem[]
  itemHeight: number
  containerHeight: number
  getItemKey?: (item: VirtualListItem) => string | number
}

const props = withDefaults(defineProps<Props>(), {
  getItemKey: (item: VirtualListItem) => item.id ?? item.index ?? 0,
})

const containerRef = ref<HTMLElement>()
const scrollTop = ref(0)

// 计算可见区域
const visibleStart = computed(() => {
  return Math.floor(scrollTop.value / props.itemHeight)
})

const visibleEnd = computed(() => {
  const visibleCount = Math.ceil(props.containerHeight / props.itemHeight)
  return Math.min(visibleStart.value + visibleCount + 1, props.items.length)
})

const visibleItems = computed(() => {
  return props.items
    .slice(visibleStart.value, visibleEnd.value)
    .map((item: any, idx: number) => ({
      ...(item as Record<string, unknown>),
      index: visibleStart.value + idx,
    }))
})

const offsetY = computed(() => {
  return visibleStart.value * props.itemHeight
})

const totalHeight = computed(() => {
  return props.items.length * props.itemHeight
})

// 滚动处理
const handleScroll = (e: Event) => {
  const target = e.target as HTMLElement
  scrollTop.value = target.scrollTop
}

</script>

<style scoped lang="scss">
.virtual-list {
  overflow: hidden;

  .virtual-list-container {
    overflow: hidden auto;
  }

  .virtual-list-content {
    position: relative;
  }

  .virtual-list-item {
    box-sizing: border-box;
  }
}
</style>

// apps/web/src/components/feature-center/VirtualList.tsx
'use client'

import * as React from 'react'

export interface VirtualListProps<T> {
  items: T[]
  itemKey: (item: T) => string
  itemHeight: number
  className?: string
  /** 可视区域高度，默认 600 */
  viewportHeight?: number
  children: (item: T) => React.ReactNode
}

/**
 * 虚拟列表组件，仅渲染可视区域的条目，适用于长列表。
 * 通过 scrollTop 计算 startIndex/endIndex，绝对定位条目。
 */
export function VirtualList<T>({
  items,
  itemKey,
  itemHeight,
  className,
  viewportHeight = 600,
  children,
}: VirtualListProps<T>) {
  const [scrollTop, setScrollTop] = React.useState(0)
  const containerRef = React.useRef<HTMLDivElement | null>(null)

  const totalHeight = items.length * itemHeight
  const startIndex = Math.max(0, Math.floor(scrollTop / itemHeight) - 4)
  const visibleCount = Math.ceil(viewportHeight / itemHeight) + 8
  const endIndex = Math.min(items.length, startIndex + visibleCount)
  const offsetY = startIndex * itemHeight

  const handleScroll = React.useCallback((e: React.UIEvent<HTMLDivElement>) => {
    setScrollTop(e.currentTarget.scrollTop)
  }, [])

  const visible = items.slice(startIndex, endIndex)

  return (
    <div
      ref={containerRef}
      onScroll={handleScroll}
      className={'relative overflow-auto ' + (className ?? '')}
      style={{ height: viewportHeight, maxHeight: viewportHeight }}
    >
      <div style={{ height: totalHeight, position: 'relative' }}>
        <div style={{ transform: `translateY(${offsetY}px)` }}>
          {visible.map((item) => (
            <div key={itemKey(item)} style={{ height: itemHeight }} className="mb-3 px-1">
              {children(item)}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
