// apps/miniapp/pages/member/coupon-list.vue
<template>
  <view class="page">
    <view class="list" v-if="list.length">
      <view class="coupon" v-for="c in list" :key="c.id">
        <view class="coupon-left">
          <text class="c-amt">{{ c.amount }}</text>
          <text class="c-unit">元</text>
        </view>
        <view class="coupon-right">
          <text class="c-title">{{ c.title }}</text>
          <text class="c-thres">满{{ c.threshold }}可用</text>
          <text class="c-time">有效期至 {{ c.expireTime }}</text>
        </view>
        <view class="coupon-btn" @tap="onReceive(c.id)">领取</view>
      </view>
    </view>
    <view class="empty" v-else-if="!loading"><text>暂无可领取优惠券</text></view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getCouponList } from '@/api'

const list = ref<Array<{ id: string; title: string; amount: number; threshold: number; expireTime: string; status: string }>>([])
const loading = ref(true)

async function load() {
  try { list.value = (await getCouponList({ status: 'available' })).list || [] } finally { loading.value = false }
}
function onReceive(_id: string) {
  uni.showToast({ title: '领取成功', icon: 'success' })
  load()
}
onShow(load)
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; padding: 24rpx 32rpx; }
.coupon { display: flex; background: #fff; border-radius: 16rpx; overflow: hidden; margin-bottom: 24rpx; }
.coupon-left { width: 180rpx; background: linear-gradient(135deg, #ff9a3c, #ff6e3c); color: #fff; display: flex; align-items: center; justify-content: center; }
.c-amt { font-size: 56rpx; font-weight: 700; }
.c-unit { font-size: 24rpx; margin-left: 8rpx; }
.coupon-right { flex: 1; padding: 24rpx; }
.c-title { display: block; font-size: 28rpx; color: #333; font-weight: 600; }
.c-thres { display: block; font-size: 22rpx; color: #999; margin-top: 8rpx; }
.c-time { display: block; font-size: 22rpx; color: #999; margin-top: 8rpx; }
.coupon-btn { width: 120rpx; display: flex; align-items: center; justify-content: center; background: #ff6e3c; color: #fff; font-size: 26rpx; }
.empty { text-align: center; padding: 120rpx 0; color: #999; }
</style>

// apps/miniapp-taro/src/pages/member/coupon-list.tsx
import { View, Text, Button } from '@tarojs/components'
import Taro, { useDidShow } from '@tarojs/taro'
import { useState, useCallback } from 'react'
import { getCouponList } from '@/api'
import { useI18n } from '@/i18n'

interface Coupon {
  id: string
  title: string
  amount: number
  threshold: number
  expireTime: string
  status: string
}

export default function CouponListPage() {
  const { t } = useI18n()
  const [list, setList] = useState<Coupon[]>([])
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const res = await getCouponList({ status: 'available' })
      setList(res.list || [])
    } finally {
      setLoading(false)
    }
  }, [])

  useDidShow(() => load())

  const onReceive = (_id: string) => {
    Taro.showToast({ title: t('member.couponList.received'), icon: 'success' })
    load()
  }

  return (
    <View className="min-h-screen bg-background p-[12px]">
      {list.map(c => (
        <View key={c.id} className="bg-card rounded-[8px] mb-[12px] flex overflow-hidden">
          <View className="bg-gradient-to-r from-[#00f2ff] to-[#8b5cf6] w-[180rpx] flex flex-col items-center justify-center py-[24rpx]">
            <View className="flex items-baseline">
              <Text className="text-[60rpx] text-white font-bold">{c.amount}</Text>
              <Text className="text-[26rpx] text-white ml-[4rpx]">{t('member.couponList.unit')}</Text>
            </View>
            <Text className="text-[22rpx] text-white mt-[4rpx]">{t('member.couponList.coupon')}</Text>
          </View>
          <View className="flex-1 px-[20rpx] py-[20rpx] flex flex-col justify-between">
            <View>
              <Text className="block text-[30rpx] text-foreground font-semibold">{c.title}</Text>
              <Text className="block text-[24rpx] text-muted-foreground mt-[8rpx]">{t('member.couponList.threshold', { threshold: c.threshold })}</Text>
              <Text className="block text-[22rpx] text-muted-foreground mt-[4rpx]">{t('member.couponList.expireTime', { time: c.expireTime })}</Text>
            </View>
            <Button
              className="self-end text-[24rpx] text-white bg-primary rounded-[24rpx] px-[24rpx] py-[4rpx] leading-[40rpx]"
              onClick={() => onReceive(c.id)}
            >
              {t('member.couponList.receive')}
            </Button>
          </View>
        </View>
      ))}
      {!loading && !list.length ? (
        <View className="text-center py-[120px] text-muted-foreground">
          <Text>{t('member.couponList.empty')}</Text>
        </View>
      ) : null}
    </View>
  )
}
