// apps/miniapp-taro/src/pages/pay/index.tsx
import { View, Text, Button } from '@tarojs/components'
import Taro, { useRouter } from '@tarojs/taro'
import { useState, useEffect } from 'react'
import { pay } from '@/api'
import { useI18n } from '@/i18n'

export default function PayIndex() {
  const { t } = useI18n()
  const router = useRouter()
  const [orderNo, setOrderNo] = useState('')
  const [amount, setAmount] = useState(0)
  const [payType, setPayType] = useState<'wechat' | 'balance' | 'alipay'>('wechat')

  const methods = [
    { value: 'wechat' as const, name: t('pay.wechat'), icon: '微', color: '#09bb07' },
    { value: 'alipay' as const, name: t('pay.alipay'), icon: '支', color: '#1677ff' },
    { value: 'balance' as const, name: t('pay.balance'), icon: '余', color: '#ff9a3c' },
  ]

  useEffect(() => {
    setOrderNo(router.params.orderNo || '')
    setAmount(Number(router.params.amount) || 0)
  }, [router.params.orderNo, router.params.amount])

  const onPay = async () => {
    if (!orderNo) {
      Taro.showToast({ title: t('pay.orderAbnormal'), icon: 'none' })
      return
    }
    try {
      const res = await pay({ orderNo, payType })
      if (res.success) {
        Taro.redirectTo({ url: `/pages/pay/result?orderNo=${orderNo}` })
      } else if (res.payUrl) {
        if (process.env.TARO_ENV === 'h5') {
          window.location.href = res.payUrl
        }
      }
    } catch {
      // ignore
    }
  }

  return (
    <View className="min-h-screen bg-[#f7f8fa] pb-[120rpx]">
      <View className="m-[24rpx] p-[32rpx] bg-white rounded-[16rpx]">
        <View className="text-center">
          <Text className="block text-[26rpx] text-[#999]">{t('pay.orderAmount')}</Text>
          <Text className="block text-[60rpx] text-[#dd524d] font-bold mt-[12rpx]">¥{amount}</Text>
        </View>
      </View>
      <View className="m-[24rpx] p-[32rpx] bg-white rounded-[16rpx]">
        <View className="text-[28rpx] text-[#333] font-semibold mb-[24rpx]">
          {t('pay.selectMethod')}
        </View>
        {methods.map((m) => (
          <View
            key={m.value}
            className="flex items-center py-[24rpx] border-b-[2rpx] border-[#f5f5f5]"
            onClick={() => setPayType(m.value)}
          >
            <View
              className="w-[60rpx] h-[60rpx] leading-[60rpx] text-center bg-[#f5f5f5] rounded-full text-[28rpx]"
              style={{ color: m.color }}
            >
              {m.icon}
            </View>
            <Text className="flex-1 ml-[24rpx] text-[28rpx] text-[#333]">{m.name}</Text>
            <View
              className={`w-[36rpx] h-[36rpx] rounded-full border-[2rpx] ${payType === m.value ? 'bg-[#07c160] border-[#07c160]' : 'border-[#ccc]'}`}
            />
          </View>
        ))}
      </View>
      <Button
        className="fixed bottom-[32rpx] left-[32rpx] right-[32rpx] bg-[#07c160] text-white rounded-[40rpx] text-[32rpx]"
        onClick={onPay}
      >
        {t('pay.confirm')} ¥{amount}
      </Button>
    </View>
  )
}

// apps/miniapp/pages/pay/index.vue
<template>
  <view class="page">
    <view class="card">
      <view class="order-info">
        <text class="o-title">订单金额</text>
        <text class="o-amount">¥{{ amount }}</text>
      </view>
    </view>
    <view class="card">
      <view class="card-title">选择支付方式</view>
      <view class="pay-method" v-for="m in methods" :key="m.value" @tap="payType = m.value">
        <view class="pm-icon" :style="{ color: m.color }">{{ m.icon }}</view>
        <text class="pm-name">{{ m.name }}</text>
        <view class="radio" :class="{ active: payType === m.value }"></view>
      </view>
    </view>
    <button class="btn" @tap="onPay">确认支付 ¥{{ amount }}</button>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { pay } from '@/api'

const orderNo = ref('')
const amount = ref(0)
const payType = ref<'wechat' | 'balance' | 'alipay'>('wechat')
const methods = [
  { value: 'wechat' as const, name: '微信支付', icon: '微', color: '#09bb07' },
  { value: 'alipay' as const, name: '支付宝', icon: '支', color: '#1677ff' },
  { value: 'balance' as const, name: '余额支付', icon: '余', color: '#ff9a3c' },
]

onLoad((q: any) => { orderNo.value = q.orderNo || ''; amount.value = Number(q.amount) || 0 })

async function onPay() {
  if (!orderNo.value) return uni.showToast({ title: '订单异常', icon: 'none' })
  try {
    const res = await pay({ orderNo: orderNo.value, payType: payType.value })
    if (res.success) {
      uni.redirectTo({ url: `/pages/pay/result?orderNo=${orderNo.value}` })
    } else if (res.payUrl) {
      // #ifdef H5
      window.location.href = res.payUrl
      // #endif
    }
  } catch (e) {}
}
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; padding-bottom: 120rpx; }
.card { margin: 24rpx; padding: 32rpx; background: #fff; border-radius: 16rpx; }
.order-info { text-align: center; }
.o-title { display: block; font-size: 26rpx; color: #999; }
.o-amount { display: block; font-size: 60rpx; color: #dd524d; font-weight: 700; margin-top: 12rpx; }
.card-title { font-size: 28rpx; color: #333; font-weight: 600; margin-bottom: 24rpx; }
.pay-method { display: flex; align-items: center; padding: 24rpx 0; border-bottom: 2rpx solid #f5f5f5; }
.pm-icon { width: 60rpx; height: 60rpx; line-height: 60rpx; text-align: center; background: #f5f5f5; border-radius: 50%; font-size: 28rpx; }
.pm-name { flex: 1; margin-left: 24rpx; font-size: 28rpx; color: #333; }
.radio { width: 36rpx; height: 36rpx; border: 2rpx solid #ccc; border-radius: 50%; }
.radio.active { background: #007aff; border-color: #007aff; position: relative; }
.radio.active::after { content: '✓'; color: #fff; font-size: 22rpx; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); }
.btn { position: fixed; bottom: 32rpx; left: 32rpx; right: 32rpx; background: #007aff; color: #fff; border-radius: 40rpx; font-size: 32rpx; }
</style>
