// client/miniapp/src/components/ModelConfigDialog/selecter.vue
<template>
    <view style="width: 100%;box-sizing: border-box;">
        <view class="selecter_body scroll-x" v-if="type == 'scale'">
            <view style="width: 100%;overflow-x: auto;">
                <view class="image_item" :class="{ 'active': value === index, 'disabled': desc && desc.includes('水印') && isVip === 0 }" v-for="(item, index) in options" :key="index" @click="!(desc && desc.includes('水印') && isVip === 0) && select(item, index)">
                    <view :class="item ? getItemIconView(item) : ''" :style="{ borderColor: value === index ? '#0105ff' : '#000000' }"></view>
                    <text class="text" :style="{ color: value === index ? '#0105ff' : '#000000' }">{{ item }}</text>
                </view>
            </view>
        </view>

        <view class="selecter_body scroll-x" v-else-if="type == 'video'">
            <view style="width: 100%;overflow-x: auto;">
                <view class="video_item" :class="{ 'active': value === '480P' }" @click="selectVideo('480P')">
                    <text class="text" :style="{ color: value === '480P' ? '#0105ff' : '#000000' }">标清 480p</text>
                    <text class="small">（640×480）</text>
                </view>
                <view class="video_item" :class="{ 'active': value === '720P' }" @click="selectVideo('720P')">
                    <text class="text" :style="{ color: value === '720P' ? '#0105ff' : '#000000' }">超清 720p</text>
                    <text class="small">（1280×720）</text>
                </view>
                <view class="video_item" :class="{ 'active': value === '1080P' }" @click="selectVideo('1080P')">
                    <text class="text" :style="{ color: value === '1080P' ? '#0105ff' : '#000000' }">高清 1080p</text>
                    <text class="small">（1920×1080）</text>
                </view>
            </view>
        </view>
        <view class="selecter_body scroll-x" v-else-if="type == 'voice'">
            <view style="width: 100%;overflow-x: auto;">
                <view class="s_i_n" :class="{ 'active': value === index }" v-for="(item, index) in options" :key="index" @click="select(item, index)">
                    <text class="text" :style="{ color: value === index ? '#0105ff' : '#000000' }">{{ item.name }}</text>
                </view>
            </view>
        </view>
        <view class="selecter_body scroll-x" v-else-if="type == 'ratio'">
            <view style="width: 100%;overflow-x: auto;">
                <view v-if="!selectedSizeIndex">
                    <view class="s_i_n" :class="{ 'active': selectedSizeIndex === index }" v-for="(item, index) in options" :key="index" @click="selectSize(item, index)">
                        <text class="text" :style="{ color: selectedSizeIndex === index ? '#0105ff' : '#000000' }">{{ Object.keys(item)[0] }}</text>
                    </view>
                </view>
                <view v-else>
                    <view class="back_button" @click="resetRatioSelection">
                        <text class="text">← 返回</text>
                    </view>
                    <view class="size_label">
                        <text class="text">{{ Object.keys(selectedSize)[0] }}</text>
                    </view>
                    <view class="s_i_n" :class="{ 'active': value === index }" v-for="(item, index) in getCurrentRatioOptions()" :key="index" @click="selectRatio(item, index)">
                        <text class="text" :style="{ color: value === index ? '#0105ff' : '#000000' }">{{ Object.keys(item)[0] }} ({{ Object.values(item)[0] }})</text>
                    </view>
                </view>
            </view>
            <view v-if="selectedRatio" class="selected_value">
                <text class="text">已选择: {{ Object.keys(selectedSize)[0] }} - {{ Object.keys(selectedRatio)[0] }} ({{ Object.values(selectedRatio)[0] }})</text>
            </view>
        </view>
        <view class="selecter_body scroll-x" v-else>
            <view style="width: 100%;overflow-x: auto;">
                <view class="s_i_n" :class="{ 'active': value === index }" v-for="(item, index) in options" :key="index" @click="select(item, index)">
                    <text class="text" :style="{ color: value === index ? '#0105ff' : '#000000' }">{{ isObject(item) ? item.desc : item }}</text>
                </view>
            </view>
        </view>
    </view>
</template>
<script setup>
import { ref, watch, onMounted } from 'vue';

const props = defineProps({
    type: String,
    options: Array,
    defaultVal: String,
    isVip: {
        type: Number,
        default: 0
    },
    desc: String
});

const emit = defineEmits(['change']);

const value = ref('');
const selectedSizeIndex = ref(null);
const selectedSize = ref(null);
const selectedRatio = ref(null);

onMounted(() => {
    if (props.type === 'ratio') {
        return;
    }
    
    if (props.options && props.options.length > 0 && value.value === '') {
        value.value = 0;
        emit('change', isObject(props.options[0]) ? props.options[0].value : props.options[0], 0);
    }
});

watch(
    () => props.defaultVal,
    (n) => {
        if (n) {
            if (props.type === 'ratio') {
                return;
            }
            
            for (let i = 0; i < props.options.length; i++) {
                if (props.options[i] == n) {
                    value.value = i;
                    break;
                }
            }
        }
    },
    { immediate: true }
);

watch(
    () => props.options,
    (newOptions) => {
        if (props.type === 'ratio') {
            return;
        }
        
        if (newOptions && newOptions.length > 0 && value.value === '') {
            value.value = 0;
            emit('change', isObject(newOptions[0]) ? newOptions[0].value : newOptions[0], 0);
        }
    },
    { immediate: true, deep: true }
);

function isObject(val) {
    return val !== null && typeof val === 'object' && !Array.isArray(val);
}

function selectSize(item, index) {
    selectedSizeIndex.value = index;
    selectedSize.value = item;
    value.value = '';
    selectedRatio.value = null;
}

function selectRatio(item, index) {
    value.value = index;
    selectedRatio.value = item;
    const sizeKey = Object.keys(selectedSize.value)[0];
    const ratioKey = Object.keys(item)[0];
    const resolution = item[ratioKey];
    
    emit('change', {
        size: sizeKey,
        ratio: ratioKey,
        resolution: resolution,
        fullData: item
    }, index);
}

function getCurrentRatioOptions() {
    if (!selectedSize.value) return [];
    const sizeKey = Object.keys(selectedSize.value)[0];
    return selectedSize.value[sizeKey];
}

function resetRatioSelection() {
    selectedSizeIndex.value = null;
    selectedSize.value = null;
    selectedRatio.value = null;
    value.value = '';
}

function selectVideo(val) {
    try {
        value.value = val;
        emit('change', val);
    } catch (error) {
        emit('change', val);
    }
}

function select(item, index) {
    if (value.value === index) {
        value.value = '';
        emit('change', '', 0);
    } else {
        value.value = index;
        emit('change', isObject(item) ? item.value : item, index);
    }
}

function getItemIconView(str) {
    if (!str) {
        return '';
    }
    if (str == '1:1') {
        return 'aa';
    }
    let arr = str.split(":");
    if (arr[0] < arr[1]) {
        return 'bc';
    }
    if (arr[0] > arr[1]) {
        return 'cb';
    }
}
</script>
<style lang="scss" scoped>
.selecter_body {
    width: 100%;
    box-sizing: border-box;
    display: flex;
    align-items: center;
    white-space: nowrap;
    
    &.scroll-x {
        justify-content: space-between;
    }

    > view {
        display: flex;
        align-items: center;
        white-space: nowrap;
    }

    .image_item {
        min-width: auto;
        width: auto;
        padding: 0 14rpx;
        height: 50rpx;
        border-radius: 10rpx;
        background-color: rgba(218, 218, 218, 0.37);
        display: flex;
        align-items: center;
        justify-content: center;
        border: 1rpx solid;
        margin-right: 21rpx;
        flex-shrink: 0;

        .aa {
            width: 33rpx;
            height: 33rpx;
            border: 1rpx solid;
            margin-right: 16rpx;
            border-radius: 10rpx;
        }

        .bc {
            width: 26rpx;
            height: 35rpx;
            border: 1rpx solid;
            margin-right: 16rpx;
            border-radius: 10rpx;
        }

        .cb {
            width: 39rpx;
            height: 29rpx;
            border: 1rpx solid;
            margin-right: 16rpx;
            border-radius: 10rpx;
        }

        .ef {
            width: 39rpx;
            height: 26rpx;
            border: 1rpx solid;
            margin-right: 16rpx;
            border-radius: 10rpx;
        }

        .fe {
            width: 18rpx;
            height: 39rpx;
            border: 1rpx solid;
            margin-right: 16rpx;
            border-radius: 10rpx;
        }
    }

    .video_item {
        min-width: auto;
        width: auto;
        padding: 0 21rpx;
        height: 65rpx;
        border-radius: 10rpx;
        background: rgba(218, 218, 218, 0.37);
        display: flex;
        align-items: center;
        justify-content: center;
        margin-right: 21rpx;
        border: 1rpx solid;
        flex-shrink: 0;
    }

    .s_i_n {
        border-radius: 10rpx;
        background-color: rgba(218, 218, 218, 0.37);
        display: flex;
        align-items: center;
        justify-content: center;
        min-width: auto;
        width: auto;
        padding: 0 14rpx;
        height: 50rpx;
        border: 1rpx solid;
        box-sizing: border-box;
        margin-right: 21rpx;
        flex-shrink: 0;
    }

    .text {
        font-family: Source Han Sans !important;
        font-size: 29rpx;
        font-weight: normal;
        color: #000000;
        line-height: 50rpx;
    }

    .small {
        font-family: Source Han Sans !important;
        font-size: 21rpx;
        font-weight: normal;
        color: #C4C4C4 !important;
        margin-top: 3rpx;
        margin-left: 5rpx;
    }
    
    .back_button {
        min-width: auto;
        width: auto;
        padding: 0 21rpx;
        height: 50rpx;
        border-radius: 10rpx;
        background-color: rgba(218, 218, 218, 0.37);
        display: flex;
        align-items: center;
        justify-content: center;
        margin-right: 21rpx;
        border: 1rpx solid #999;
        flex-shrink: 0;
        
        .text {
            font-family: Source Han Sans !important;
            font-size: 29rpx;
            font-weight: normal;
            color: #666;
            line-height: 50rpx;
        }
    }
    
    .size_label {
        min-width: auto;
        width: auto;
        padding: 0 21rpx;
        height: 50rpx;
        border-radius: 10rpx;
        background-color: rgba(81, 141, 253, 0.2);
        display: flex;
        align-items: center;
        justify-content: center;
        margin-right: 21rpx;
        border: 1rpx solid #518dfd;
        flex-shrink: 0;
        
        .text {
            font-family: Source Han Sans !important;
            font-size: 29rpx;
            font-weight: bold;
            color: #518dfd;
            line-height: 50rpx;
        }
    }
    
    .selected_value {
        width: 100%;
        padding: 13rpx 21rpx;
        margin-top: 21rpx;
        border-radius: 10rpx;
        background-color: rgba(81, 141, 253, 0.1);
        border: 1rpx solid #518dfd;
        box-sizing: border-box;
        
        .text {
            font-family: Source Han Sans !important;
            font-size: 31rpx;
            font-weight: bold;
            color: #518dfd;
            line-height: 1.5;
        }
    }
}

.active {
    backdrop-filter: blur(10rpx);
    border-color: #518dfd !important;
    background-color: #d9e6fd !important;
}

.disabled {
    opacity: 0.5;
    cursor: not-allowed;
    pointer-events: none;
}
</style>

// apps/miniapp-taro/src/components/Selecter.tsx
import { useState, useEffect } from 'react'
import { View, Text, ScrollView } from '@tarojs/components'

/**
 * 通用选择器 — 对齐原项目 ModelConfigDialog/selecter.vue
 * 5 种 type:
 * - 'scale': 比例尺寸(1:1 / 4:3 / 16:9 等,带 icon 视觉)
 * - 'video': 视频分辨率(480P / 720P / 1080P)
 * - 'voice': 音色选择(name 字段)
 * - 'ratio': 二级选择(先选 1K/2K/4K 尺寸,再选比例)
 * - 默认:普通数组或 {desc,value} 对象数组
 */

export type SelecterType = 'scale' | 'video' | 'ratio' | 'voice' | ''

export interface SelecterOption {
  name?: string
  desc?: string
  value?: string | number
  [key: string]: unknown
}

export interface SelecterProps {
  type?: SelecterType
  options: Array<string | SelecterOption | Record<string, unknown>>
  defaultVal?: string
  desc?: string
  isVip?: number
  onChange?: (val: unknown, index?: number) => void
}

const isObject = (v: unknown): v is SelecterOption =>
  v !== null && typeof v === 'object' && !Array.isArray(v)

// 获取对象第一个 key
const firstKey = (obj: Record<string, unknown> | null | undefined): string => {
  if (!obj) return ''
  const keys = Object.keys(obj)
  return keys.length > 0 ? (keys[0] as string) : ''
}

// 通过比例字符串返回 icon 的宽高 class
const getRatioIconStyle = (str: string): { width: string; height: string } => {
  if (!str) return { width: '33rpx', height: '33rpx' }
  if (str === '1:1') return { width: '33rpx', height: '33rpx' }
  const arr = str.split(':')
  const a = Number(arr[0])
  const b = Number(arr[1])
  if (a < b) return { width: '26rpx', height: '35rpx' }
  if (a > b) return { width: '39rpx', height: '29rpx' }
  return { width: '33rpx', height: '33rpx' }
}

const ITEM_BASE = 'flex items-center justify-center px-2 h-[50rpx] rounded-[10rpx] mr-[21rpx] flex-shrink-0 border'
const ITEM_BG = 'bg-muted/40'

export default function Selecter({
  type = '',
  options,
  defaultVal,
  desc,
  isVip = 0,
  onChange,
}: SelecterProps) {
  const [value, setValue] = useState<number | string>('')
  const [selectedSizeIndex, setSelectedSizeIndex] = useState<number | null>(null)
  const [selectedSize, setSelectedSize] = useState<Record<string, unknown> | null>(null)
  const [selectedRatio, setSelectedRatio] = useState<Record<string, unknown> | null>(null)

  // 默认选中第一个(ratio 类型除外)
  useEffect(() => {
    if (type === 'ratio') return
    if (options && options.length > 0 && value === '') {
      setValue(0)
      const first = options[0]
      onChange?.(isObject(first) ? first.value : first, 0)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [options, type])

  // defaultVal 变化时同步选中
  useEffect(() => {
    if (!defaultVal || type === 'ratio') return
    for (let i = 0; i < options.length; i++) {
      // eslint-disable-next-line eqeqeq
      if (options[i] == defaultVal) {
        setValue(i)
        break
      }
    }
  }, [defaultVal, options, type])

  const select = (item: string | SelecterOption | Record<string, unknown>, index: number) => {
    if (value === index) {
      setValue('')
      onChange?.('', 0)
    } else {
      setValue(index)
      onChange?.(isObject(item) ? item.value : item, index)
    }
  }

  const selectVideo = (val: string) => {
    setValue(val)
    onChange?.(val)
  }

  // ratio 类型:选尺寸
  const selectSize = (item: Record<string, unknown>, index: number) => {
    setSelectedSizeIndex(index)
    setSelectedSize(item)
    setValue('')
    setSelectedRatio(null)
  }

  // ratio 类型:选比例
  const selectRatio = (item: Record<string, unknown>, index: number) => {
    setValue(index)
    setSelectedRatio(item)
    const sizeKey = selectedSize ? firstKey(selectedSize) : ''
    const ratioKey = firstKey(item)
    const resolution = (item as Record<string, string>)[ratioKey]
    onChange?.({ size: sizeKey, ratio: ratioKey, resolution, fullData: item }, index)
  }

  const getCurrentRatioOptions = (): Array<Record<string, unknown>> => {
    if (!selectedSize) return []
    const sizeKey = firstKey(selectedSize)
    return (selectedSize as Record<string, Array<Record<string, unknown>>>)[sizeKey] || []
  }

  const resetRatioSelection = () => {
    setSelectedSizeIndex(null)
    setSelectedSize(null)
    setSelectedRatio(null)
    setValue('')
  }

  // 水印 desc + 非 VIP 时禁用
  const isDisabled = ():
 boolean => !!(desc && desc.includes('水印') && isVip === 0)

  // ===== type='scale':比例尺寸选择(带 icon) =====
  if (type === 'scale') {
    return (
      <ScrollView scrollX className="w-full whitespace-nowrap">
        <View className="flex items-center w-full">
          {options.map((item, index) => {
            const str = String(item)
            const iconStyle = getRatioIconStyle(str)
            const active = value === index
            return (
              <View
                key={index}
                className={`${ITEM_BASE} ${ITEM_BG} ${isDisabled() ? 'opacity-50 pointer-events-none' : ''}`}
                style={{ borderColor: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
                onClick={() => !isDisabled() && select(item, index)}
              >
                <View
                  className="mr-2 border rounded-[10rpx]"
                  style={{ ...iconStyle, borderColor: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
                />
                <Text
                  className="text-[29rpx] leading-[50rpx]"
                  style={{ color: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
                >
                  {str}
                </Text>
              </View>
            )
          })}
        </View>
      </ScrollView>
    )
  }

  // ===== type='video':视频分辨率选择 =====
  if (type === 'video') {
    const items = [
      { label: '标清 480p', sub: '（640×480）', val: '480P' },
      { label: '超清 720p', sub: '（1280×720）', val: '720P' },
      { label: '高清 1080p', sub: '（1920×1080）', val: '1080P' },
    ]
    return (
      <ScrollView scrollX className="w-full whitespace-nowrap">
        <View className="flex items-center w-full">
          {items.map((it) => {
            const active = value === it.val
            return (
              <View
                key={it.val}
                className={`${ITEM_BASE} ${ITEM_BG} h-[65rpx] px-[21rpx]`}
                style={{ borderColor: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
                onClick={() => selectVideo(it.val)}
              >
                <Text
                  className="text-[29rpx]"
                  style={{ color: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
                >
                  {it.label}
                </Text>
                <Text className="text-[21rpx] text-muted-foreground ml-1 mt-[3rpx]">{it.sub}</Text>
              </View>
            )
          })}
        </View>
      </ScrollView>
    )
  }

  // ===== type='voice':音色选择 =====
  if (type === 'voice') {
    return (
      <ScrollView scrollX className="w-full whitespace-nowrap">
        <View className="flex items-center w-full">
          {options.map((item, index) => {
            const name = isObject(item) ? item.name || '' : String(item)
            const active = value === index
            return (
              <View
                key={index}
                className={`${ITEM_BASE} ${ITEM_BG}`}
                onClick={() => select(item, index)}
              >
                <Text
                  className="text-[29rpx] leading-[50rpx]"
                  style={{ color: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
                >
                  {name}
                </Text>
              </View>
            )
          })}
        </View>
      </ScrollView>
    )
  }

  // ===== type='ratio':二级选择(尺寸 → 比例) =====
  if (type === 'ratio') {
    return (
      <View className="w-full">
        <ScrollView scrollX className="w-full whitespace-nowrap">
          {!selectedSize ? (
            <View className="flex items-center w-full">
              {options.map((item, index) => {
                const obj = item as Record<string, unknown>
                const label = firstKey(obj)
                const active = selectedSizeIndex === index
                return (
                  <View
                    key={index}
                    className={`${ITEM_BASE} ${ITEM_BG}`}
                    style={{ borderColor: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
                    onClick={() => selectSize(obj, index)}
                  >
                    <Text
                      className="text-[29rpx] leading-[50rpx]"
                      style={{ color: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
                    >
                      {label}
                    </Text>
                  </View>
                )
              })}
            </View>
          ) : (
            <View className="flex items-center w-full">
              <View
                className={`${ITEM_BASE} border-muted-foreground`}
                onClick={resetRatioSelection}
              >
                <Text className="text-[29rpx] leading-[50rpx] text-muted-foreground">← 返回</Text>
              </View>
              <View
                className={`${ITEM_BASE}`}
                style={{ background: 'rgba(81, 141, 253, 0.2)', borderColor: 'var(--color-primary)' }}
              >
                <Text
                  className="text-[29rpx] leading-[50rpx] font-bold"
                  style={{ color: 'var(--color-primary)' }}
                >
                  {firstKey(selectedSize)}
                </Text>
              </View>
              {getCurrentRatioOptions().map((item, index) => {
                const ratioKey = firstKey(item)
                const resolution = (item as Record<string, string>)[ratioKey]
                const active = value === index
                return (
                  <View
                    key={index}
                    className={`${ITEM_BASE} ${ITEM_BG}`}
                    style={{ borderColor: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
                    onClick={() => selectRatio(item, index)}
                  >
                    <Text
                      className="text-[29rpx] leading-[50rpx]"
                      style={{ color: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
                    >
                      {ratioKey} ({resolution})
                    </Text>
                  </View>
                )
              })}
            </View>
          )}
        </ScrollView>
        {selectedRatio && (
          <View
            className="w-full px-[21rpx] py-[13rpx] mt-[21rpx] rounded-[10rpx]"
            style={{ background: 'rgba(81, 141, 253, 0.1)', border: '1px solid var(--color-primary)' }}
          >
            <Text className="text-[31rpx] font-bold" style={{ color: 'var(--color-primary)' }}>
              已选择: {firstKey(selectedSize)} - {firstKey(selectedRatio)} (
              {(selectedRatio as Record<string, string>)[firstKey(selectedRatio)]})
            </Text>
          </View>
        )}
        {/* 占位避免 selectedRatio 为 null 时 TS 报错 */}
        {!selectedRatio && null}
      </View>
    )
  }

  // ===== 默认:普通数组或对象数组 =====
  return (
    <ScrollView scrollX className="w-full whitespace-nowrap">
      <View className="flex items-center w-full">
        {options.map((item, index) => {
          const label = isObject(item) ? item.desc || '' : String(item)
          const active = value === index
          return (
            <View
              key={index}
              className={`${ITEM_BASE} ${ITEM_BG}`}
              onClick={() => select(item, index)}
            >
              <Text
                className="text-[29rpx] leading-[50rpx]"
                style={{ color: active ? 'var(--color-primary)' : 'var(--color-foreground)' }}
              >
                {label}
              </Text>
            </View>
          )
        })}
      </View>
    </ScrollView>
  )
}
