// client/miniapp/src/components/ModelConfigDialog/selecter.vue
<template>
    <view style="width: 100%;box-sizing: border-box;">
        <view class="selecter_body scroll-x" v-if="type == 'scale'">
            <view style="width: 100%;overflow-x: auto;">
                <view class="image_item" :class="{ 'active': value === index, 'disabled': desc && desc.includes('水印') && isVip === 0 }" v-for="(item, index) in options" :key="index" @click="!(desc && desc.includes('水印') && isVip === 0) && select(item, index)">
                    <view :class="item ? getItemIconView(item) : ''" :style="{ borderColor: value === index ? '#0105ff' : '#000000' }"></view>
                    <text class="text" :style="{ color: value === index ? '#0105ff' : '#000000' }">{{ item }}</text>
                </view>
            </view>
        </view>

        <view class="selecter_body scroll-x" v-else-if="type == 'video'">
            <view style="width: 100%;overflow-x: auto;">
                <view class="video_item" :class="{ 'active': value === '480P' }" @click="selectVideo('480P')">
                    <text class="text" :style="{ color: value === '480P' ? '#0105ff' : '#000000' }">标清 480p</text>
                    <text class="small">（640×480）</text>
                </view>
                <view class="video_item" :class="{ 'active': value === '720P' }" @click="selectVideo('720P')">
                    <text class="text" :style="{ color: value === '720P' ? '#0105ff' : '#000000' }">超清 720p</text>
                    <text class="small">（1280×720）</text>
                </view>
                <view class="video_item" :class="{ 'active': value === '1080P' }" @click="selectVideo('1080P')">
                    <text class="text" :style="{ color: value === '1080P' ? '#0105ff' : '#000000' }">高清 1080p</text>
                    <text class="small">（1920×1080）</text>
                </view>
            </view>
        </view>
        <view class="selecter_body scroll-x" v-else-if="type == 'voice'">
            <view style="width: 100%;overflow-x: auto;">
                <view class="s_i_n" :class="{ 'active': value === index }" v-for="(item, index) in options" :key="index" @click="select(item, index)">
                    <text class="text" :style="{ color: value === index ? '#0105ff' : '#000000' }">{{ item.name }}</text>
                </view>
            </view>
        </view>
        <view class="selecter_body scroll-x" v-else-if="type == 'ratio'">
            <view style="width: 100%;overflow-x: auto;">
                <view v-if="!selectedSizeIndex">
                    <view class="s_i_n" :class="{ 'active': selectedSizeIndex === index }" v-for="(item, index) in options" :key="index" @click="selectSize(item, index)">
                        <text class="text" :style="{ color: selectedSizeIndex === index ? '#0105ff' : '#000000' }">{{ Object.keys(item)[0] }}</text>
                    </view>
                </view>
                <view v-else>
                    <view class="back_button" @click="resetRatioSelection">
                        <text class="text">← 返回</text>
                    </view>
                    <view class="size_label">
                        <text class="text">{{ Object.keys(selectedSize)[0] }}</text>
                    </view>
                    <view class="s_i_n" :class="{ 'active': value === index }" v-for="(item, index) in getCurrentRatioOptions()" :key="index" @click="selectRatio(item, index)">
                        <text class="text" :style="{ color: value === index ? '#0105ff' : '#000000' }">{{ Object.keys(item)[0] }} ({{ Object.values(item)[0] }})</text>
                    </view>
                </view>
            </view>
            <view v-if="selectedRatio" class="selected_value">
                <text class="text">已选择: {{ Object.keys(selectedSize)[0] }} - {{ Object.keys(selectedRatio)[0] }} ({{ Object.values(selectedRatio)[0] }})</text>
            </view>
        </view>
        <view class="selecter_body scroll-x" v-else>
            <view style="width: 100%;overflow-x: auto;">
                <view class="s_i_n" :class="{ 'active': value === index }" v-for="(item, index) in options" :key="index" @click="select(item, index)">
                    <text class="text" :style="{ color: value === index ? '#0105ff' : '#000000' }">{{ isObject(item) ? item.desc : item }}</text>
                </view>
            </view>
        </view>
    </view>
</template>
<script setup>
import { ref, watch, onMounted } from 'vue';

const props = defineProps({
    type: String,
    options: Array,
    defaultVal: String,
    isVip: {
        type: Number,
        default: 0
    },
    desc: String
});

const emit = defineEmits(['change']);

const value = ref('');
const selectedSizeIndex = ref(null);
const selectedSize = ref(null);
const selectedRatio = ref(null);

onMounted(() => {
    if (props.type === 'ratio') {
        return;
    }
    
    if (props.options && props.options.length > 0 && value.value === '') {
        value.value = 0;
        emit('change', isObject(props.options[0]) ? props.options[0].value : props.options[0], 0);
    }
});

watch(
    () => props.defaultVal,
    (n) => {
        if (n) {
            if (props.type === 'ratio') {
                return;
            }
            
            for (let i = 0; i < props.options.length; i++) {
                if (props.options[i] == n) {
                    value.value = i;
                    break;
                }
            }
        }
    },
    { immediate: true }
);

watch(
    () => props.options,
    (newOptions) => {
        if (props.type === 'ratio') {
            return;
        }
        
        if (newOptions && newOptions.length > 0 && value.value === '') {
            value.value = 0;
            emit('change', isObject(newOptions[0]) ? newOptions[0].value : newOptions[0], 0);
        }
    },
    { immediate: true, deep: true }
);

function isObject(val) {
    return val !== null && typeof val === 'object' && !Array.isArray(val);
}

function selectSize(item, index) {
    selectedSizeIndex.value = index;
    selectedSize.value = item;
    value.value = '';
    selectedRatio.value = null;
}

function selectRatio(item, index) {
    value.value = index;
    selectedRatio.value = item;
    const sizeKey = Object.keys(selectedSize.value)[0];
    const ratioKey = Object.keys(item)[0];
    const resolution = item[ratioKey];
    
    emit('change', {
        size: sizeKey,
        ratio: ratioKey,
        resolution: resolution,
        fullData: item
    }, index);
}

function getCurrentRatioOptions() {
    if (!selectedSize.value) return [];
    const sizeKey = Object.keys(selectedSize.value)[0];
    return selectedSize.value[sizeKey];
}

function resetRatioSelection() {
    selectedSizeIndex.value = null;
    selectedSize.value = null;
    selectedRatio.value = null;
    value.value = '';
}

function selectVideo(val) {
    try {
        value.value = val;
        emit('change', val);
    } catch (error) {
        emit('change', val);
    }
}

function select(item, index) {
    if (value.value === index) {
        value.value = '';
        emit('change', '', 0);
    } else {
        value.value = index;
        emit('change', isObject(item) ? item.value : item, index);
    }
}

function getItemIconView(str) {
    if (!str) {
        return '';
    }
    if (str == '1:1') {
        return 'aa';
    }
    let arr = str.split(":");
    if (arr[0] < arr[1]) {
        return 'bc';
    }
    if (arr[0] > arr[1]) {
        return 'cb';
    }
}
</script>
<style lang="scss" scoped>
.selecter_body {
    width: 100%;
    box-sizing: border-box;
    display: flex;
    align-items: center;
    white-space: nowrap;
    
    &.scroll-x {
        justify-content: space-between;
    }

    > view {
        display: flex;
        align-items: center;
        white-space: nowrap;
    }

    .image_item {
        min-width: auto;
        width: auto;
        padding: 0 14rpx;
        height: 50rpx;
        border-radius: 10rpx;
        background-color: rgba(218, 218, 218, 0.37);
        display: flex;
        align-items: center;
        justify-content: center;
        border: 1rpx solid;
        margin-right: 21rpx;
        flex-shrink: 0;

        .aa {
            width: 33rpx;
            height: 33rpx;
            border: 1rpx solid;
            margin-right: 16rpx;
            border-radius: 10rpx;
        }

        .bc {
            width: 26rpx;
            height: 35rpx;
            border: 1rpx solid;
            margin-right: 16rpx;
            border-radius: 10rpx;
        }

        .cb {
            width: 39rpx;
            height: 29rpx;
            border: 1rpx solid;
            margin-right: 16rpx;
            border-radius: 10rpx;
        }

        .ef {
            width: 39rpx;
            height: 26rpx;
            border: 1rpx solid;
            margin-right: 16rpx;
            border-radius: 10rpx;
        }

        .fe {
            width: 18rpx;
            height: 39rpx;
            border: 1rpx solid;
            margin-right: 16rpx;
            border-radius: 10rpx;
        }
    }

    .video_item {
        min-width: auto;
        width: auto;
        padding: 0 21rpx;
        height: 65rpx;
        border-radius: 10rpx;
        background: rgba(218, 218, 218, 0.37);
        display: flex;
        align-items: center;
        justify-content: center;
        margin-right: 21rpx;
        border: 1rpx solid;
        flex-shrink: 0;
    }

    .s_i_n {
        border-radius: 10rpx;
        background-color: rgba(218, 218, 218, 0.37);
        display: flex;
        align-items: center;
        justify-content: center;
        min-width: auto;
        width: auto;
        padding: 0 14rpx;
        height: 50rpx;
        border: 1rpx solid;
        box-sizing: border-box;
        margin-right: 21rpx;
        flex-shrink: 0;
    }

    .text {
        font-family: Source Han Sans !important;
        font-size: 29rpx;
        font-weight: normal;
        color: #000000;
        line-height: 50rpx;
    }

    .small {
        font-family: Source Han Sans !important;
        font-size: 21rpx;
        font-weight: normal;
        color: #C4C4C4 !important;
        margin-top: 3rpx;
        margin-left: 5rpx;
    }
    
    .back_button {
        min-width: auto;
        width: auto;
        padding: 0 21rpx;
        height: 50rpx;
        border-radius: 10rpx;
        background-color: rgba(218, 218, 218, 0.37);
        display: flex;
        align-items: center;
        justify-content: center;
        margin-right: 21rpx;
        border: 1rpx solid #999;
        flex-shrink: 0;
        
        .text {
            font-family: Source Han Sans !important;
            font-size: 29rpx;
            font-weight: normal;
            color: #666;
            line-height: 50rpx;
        }
    }
    
    .size_label {
        min-width: auto;
        width: auto;
        padding: 0 21rpx;
        height: 50rpx;
        border-radius: 10rpx;
        background-color: rgba(81, 141, 253, 0.2);
        display: flex;
        align-items: center;
        justify-content: center;
        margin-right: 21rpx;
        border: 1rpx solid #518dfd;
        flex-shrink: 0;
        
        .text {
            font-family: Source Han Sans !important;
            font-size: 29rpx;
            font-weight: bold;
            color: #518dfd;
            line-height: 50rpx;
        }
    }
    
    .selected_value {
        width: 100%;
        padding: 13rpx 21rpx;
        margin-top: 21rpx;
        border-radius: 10rpx;
        background-color: rgba(81, 141, 253, 0.1);
        border: 1rpx solid #518dfd;
        box-sizing: border-box;
        
        .text {
            font-family: Source Han Sans !important;
            font-size: 31rpx;
            font-weight: bold;
            color: #518dfd;
            line-height: 1.5;
        }
    }
}

.active {
    backdrop-filter: blur(10rpx);
    border-color: #518dfd !important;
    background-color: #d9e6fd !important;
}

.disabled {
    opacity: 0.5;
    cursor: not-allowed;
    pointer-events: none;
}
</style>

// packages/app/src/components/Selecter.tsx
import { useState, useEffect, useCallback } from 'react'
import type { CSSProperties } from 'react'
import { getTokens, type AppThemeTokens, type AppThemeMode } from '../theme/tokens'

/**
 * 通用选择器 — 跨端共享层。
 *
 * 对齐原项目 ModelConfigDialog/selecter.vue。5 种 type:
 * - 'scale': 比例尺寸(1:1 / 4:3 / 16:9 等,带 icon 视觉)
 * - 'video': 视频分辨率(480P / 720P / 1080P)
 * - 'voice': 音色选择(name 字段)
 * - 'ratio': 二级选择(先选 1K/2K/4K 尺寸,再选比例)
 * - 默认:普通数组或 {desc,value} 对象数组
 *
 * 平台无关:不依赖 @tarojs/* 或 react-native,ScrollView → div + overflowX:auto。
 */
export type SelecterType = 'scale' | 'video' | 'ratio' | 'voice' | ''

export interface SelecterOption {
  name?: string
  desc?: string
  value?: string | number
  [key: string]: unknown
}

export interface SelecterProps {
  type?: SelecterType
  options: Array<string | SelecterOption | Record<string, unknown>>
  defaultVal?: string
  desc?: string
  isVip?: number
  onChange?: (val: unknown, index?: number) => void
  /** 已解析主题,默认 'light' */
  colorScheme?: AppThemeMode
}

const isObject = (v: unknown): v is SelecterOption =>
  v !== null && typeof v === 'object' && !Array.isArray(v)

const firstKey = (obj: Record<string, unknown> | null | undefined): string => {
  if (!obj) return ''
  const keys = Object.keys(obj)
  return keys.length > 0 ? (keys[0] ?? '') : ''
}

const getRatioIconSize = (str: string): { width: number; height: number } => {
  if (!str) return { width: 16, height: 16 }
  if (str === '1:1') return { width: 16, height: 16 }
  const arr = str.split(':')
  const a = Number(arr[0])
  const b = Number(arr[1])
  if (Number.isFinite(a) && Number.isFinite(b)) {
    if (a < b) return { width: 13, height: 18 }
    if (a > b) return { width: 20, height: 15 }
  }
  return { width: 16, height: 16 }
}

// ===== 样式(view/text 分离) =====

const viewStyles = {
  scroll: (): CSSProperties => ({
    width: '100%',
    overflowX: 'auto',
    whiteSpace: 'nowrap',
  }),
  inner: (): CSSProperties => ({
    display: 'inline-flex',
    alignItems: 'center',
  }),
  ratioRoot: (): CSSProperties => ({ width: '100%' }),
  ratioSelected: (tk: AppThemeTokens): CSSProperties => ({
    width: '100%',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 6,
    paddingBottom: 6,
    marginTop: 10,
    borderRadius: 12,
    backgroundColor: tk.surface.muted,
  }),
  item: (
    tk: AppThemeTokens,
    active: boolean,
    disabled: boolean,
    extra?: CSSProperties,
  ): CSSProperties => ({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 8,
    paddingRight: 8,
    height: 25,
    borderRadius: 12,
    marginRight: 10,
    flexShrink: 0,
    border: `1px solid ${active ? tk.brand.DEFAULT : tk.text.primary}`,
    backgroundColor: tk.surface.light,
    opacity: disabled ? 0.5 : 1,
    pointerEvents: disabled ? 'none' : 'auto',
    cursor: disabled ? 'not-allowed' : 'pointer',
    ...extra,
  }),
  ratioIcon: (tk: AppThemeTokens, active: boolean, w: number, h: number): CSSProperties => ({
    marginRight: 8,
    border: `1px solid ${active ? tk.brand.DEFAULT : tk.text.primary}`,
    width: w,
    height: h,
    borderRadius: 5,
  }),
  backBtn: (): CSSProperties => ({
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 8,
    paddingRight: 8,
    height: 25,
    borderRadius: 12,
    marginRight: 10,
    flexShrink: 0,
    border: '1px solid',
    cursor: 'pointer',
  }),
  sizeLabel: (): CSSProperties => ({
    display: 'inline-flex',
    alignItems: 'center',
    paddingLeft: 8,
    paddingRight: 8,
    height: 25,
    marginRight: 10,
    flexShrink: 0,
  }),
}

const textStyles = {
  item: (tk: AppThemeTokens, active: boolean): CSSProperties => ({
    fontSize: 14,
    lineHeight: '25px',
    color: active ? tk.brand.DEFAULT : tk.text.primary,
  }),
  videoItem: (tk: AppThemeTokens, active: boolean): CSSProperties => ({
    fontSize: 14,
    color: active ? tk.brand.DEFAULT : tk.text.primary,
  }),
  videoSub: (tk: AppThemeTokens): CSSProperties => ({
    fontSize: 10,
    color: tk.text.secondary,
    marginLeft: 4,
    marginTop: 1,
  }),
  backText: (tk: AppThemeTokens): CSSProperties => ({
    fontSize: 14,
    lineHeight: '25px',
    color: tk.text.secondary,
  }),
  sizeLabel: (): CSSProperties => ({
    fontSize: 14,
    lineHeight: '25px',
    fontWeight: 700,
  }),
  ratioSelected: (tk: AppThemeTokens): CSSProperties => ({
    fontSize: 15,
    fontWeight: 700,
    color: tk.brand.DEFAULT,
  }),
}

export function Selecter({
  type = '',
  options,
  defaultVal,
  desc,
  isVip = 0,
  onChange,
  colorScheme = 'light',
}: SelecterProps) {
  const tk = getTokens(colorScheme)
  const [value, setValue] = useState<number | string>('')
  const [selectedSizeIndex, setSelectedSizeIndex] = useState<number | null>(null)
  const [selectedSize, setSelectedSize] = useState<Record<string, unknown> | null>(null)
  const [selectedRatio, setSelectedRatio] = useState<Record<string, unknown> | null>(null)

  // 默认选中第一个(ratio 类型除外)
  useEffect(() => {
    if (type === 'ratio') return
    if (options && options.length > 0 && value === '') {
      setValue(0)
      const first = options[0]
      onChange?.(isObject(first) ? first.value : first, 0)
    }
  }, [options, type, onChange, value])

  // defaultVal 变化时同步选中
  useEffect(() => {
    if (!defaultVal || type === 'ratio') return
    for (let i = 0; i < options.length; i += 1) {
      // eslint-disable-next-line eqeqeq
      if (options[i] == defaultVal) {
        setValue(i)
        break
      }
    }
  }, [defaultVal, options, type])

  const select = useCallback(
    (item: string | SelecterOption | Record<string, unknown>, index: number) => {
      if (value === index) {
        setValue('')
        onChange?.('', 0)
      } else {
        setValue(index)
        onChange?.(isObject(item) ? item.value : item, index)
      }
    },
    [onChange, value],
  )

  const selectVideo = useCallback(
    (val: string) => {
      setValue(val)
      onChange?.(val)
    },
    [onChange],
  )

  const selectSize = useCallback((item: Record<string, unknown>, index: number) => {
    setSelectedSizeIndex(index)
    setSelectedSize(item)
    setValue('')
    setSelectedRatio(null)
  }, [])

  const selectRatio = useCallback(
    (item: Record<string, unknown>, index: number) => {
      setValue(index)
      setSelectedRatio(item)
      const sizeKey = selectedSize ? firstKey(selectedSize) : ''
      const ratioKey = firstKey(item)
      const resolution = (item as Record<string, string>)[ratioKey]
      onChange?.({ size: sizeKey, ratio: ratioKey, resolution, fullData: item }, index)
    },
    [onChange, selectedSize],
  )

  const getCurrentRatioOptions = (): Array<Record<string, unknown>> => {
    if (!selectedSize) return []
    const sizeKey = firstKey(selectedSize)
    return (selectedSize as Record<string, Array<Record<string, unknown>>>)[sizeKey] || []
  }

  const resetRatioSelection = useCallback(() => {
    setSelectedSizeIndex(null)
    setSelectedSize(null)
    setSelectedRatio(null)
    setValue('')
  }, [])

  const isDisabled = (): boolean => !!(desc && desc.includes('水印') && isVip === 0)

  // ===== type='scale' =====
  if (type === 'scale') {
    return (
      <div style={viewStyles.scroll()}>
        <div style={viewStyles.inner()}>
          {options.map((item, index) => {
            const str = String(item)
            const iconSize = getRatioIconSize(str)
            const active = value === index
            const disabled = isDisabled()
            return (
              <div
                key={index}
                role="button"
                tabIndex={0}
                style={viewStyles.item(tk, active, disabled)}
                onClick={() => !disabled && select(item, index)}
                onKeyDown={(e) => {
                  if ((e.key === 'Enter' || e.key === ' ') && !disabled) {
                    e.preventDefault()
                    select(item, index)
                  }
                }}
              >
                <span style={viewStyles.ratioIcon(tk, active, iconSize.width, iconSize.height)} />
                <span style={textStyles.item(tk, active)}>{str}</span>
              </div>
            )
          })}
        </div>
      </div>
    )
  }

  // ===== type='video' =====
  if (type === 'video') {
    const items: Array<{ label: string; sub: string; val: string }> = [
      { label: '标清 480p', sub: '(640×480)', val: '480P' },
      { label: '超清 720p', sub: '(1280×720)', val: '720P' },
      { label: '高清 1080p', sub: '(1920×1080)', val: '1080P' },
    ]
    return (
      <div style={viewStyles.scroll()}>
        <div style={viewStyles.inner()}>
          {items.map((it) => {
            const active = value === it.val
            return (
              <div
                key={it.val}
                role="button"
                tabIndex={0}
                style={viewStyles.item(tk, active, false, {
                  height: 32,
                  paddingLeft: 10,
                  paddingRight: 10,
                })}
                onClick={() => selectVideo(it.val)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault()
                    selectVideo(it.val)
                  }
                }}
              >
                <span style={textStyles.videoItem(tk, active)}>{it.label}</span>
                <span style={textStyles.videoSub(tk)}>{it.sub}</span>
              </div>
            )
          })}
        </div>
      </div>
    )
  }

  // ===== type='voice' =====
  if (type === 'voice') {
    return (
      <div style={viewStyles.scroll()}>
        <div style={viewStyles.inner()}>
          {options.map((item, index) => {
            const name = isObject(item) ? item.name || '' : String(item)
            const active = value === index
            return (
              <div
                key={index}
                role="button"
                tabIndex={0}
                style={viewStyles.item(tk, active, false)}
                onClick={() => select(item, index)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault()
                    select(item, index)
                  }
                }}
              >
                <span style={textStyles.item(tk, active)}>{name}</span>
              </div>
            )
          })}
        </div>
      </div>
    )
  }

  // ===== type='ratio' =====
  if (type === 'ratio') {
    return (
      <div style={viewStyles.ratioRoot()}>
        <div style={viewStyles.scroll()}>
          {!selectedSize ? (
            <div style={viewStyles.inner()}>
              {options.map((item, index) => {
                const obj = item as Record<string, unknown>
                const label = firstKey(obj)
                const active = selectedSizeIndex === index
                return (
                  <div
                    key={index}
                    role="button"
                    tabIndex={0}
                    style={viewStyles.item(tk, active, false)}
                    onClick={() => selectSize(obj, index)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' || e.key === ' ') {
                        e.preventDefault()
                        selectSize(obj, index)
                      }
                    }}
                  >
                    <span style={textStyles.item(tk, active)}>{label}</span>
                  </div>
                )
              })}
            </div>
          ) : (
            <div style={viewStyles.inner()}>
              <div
                role="button"
                tabIndex={0}
                style={{ ...viewStyles.backBtn(), borderColor: tk.gray[500] }}
                onClick={resetRatioSelection}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault()
                    resetRatioSelection()
                  }
                }}
              >
                <span style={textStyles.backText(tk)}>← 返回</span>
              </div>
              <div style={viewStyles.sizeLabel()}>
                <span style={{ ...textStyles.sizeLabel(), color: tk.brand.DEFAULT }}>
                  {firstKey(selectedSize)}
                </span>
              </div>
              {getCurrentRatioOptions().map((item, index) => {
                const ratioKey = firstKey(item)
                const resolution = (item as Record<string, string>)[ratioKey]
                const active = value === index
                return (
                  <div
                    key={index}
                    role="button"
                    tabIndex={0}
                    style={viewStyles.item(tk, active, false)}
                    onClick={() => selectRatio(item, index)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' || e.key === ' ') {
                        e.preventDefault()
                        selectRatio(item, index)
                      }
                    }}
                  >
                    <span style={textStyles.item(tk, active)}>
                      {ratioKey} ({resolution})
                    </span>
                  </div>
                )
              })}
            </div>
          )}
        </div>
        {selectedRatio ? (
          <div style={viewStyles.ratioSelected(tk)}>
            <span style={textStyles.ratioSelected(tk)}>
              已选择: {firstKey(selectedSize)} - {firstKey(selectedRatio)} (
              {(selectedRatio as Record<string, string>)[firstKey(selectedRatio)]})
            </span>
          </div>
        ) : null}
      </div>
    )
  }

  // ===== 默认 =====
  return (
    <div style={viewStyles.scroll()}>
      <div style={viewStyles.inner()}>
        {options.map((item, index) => {
          const label = isObject(item) ? item.desc || '' : String(item)
          const active = value === index
          return (
            <div
              key={index}
              role="button"
              tabIndex={0}
              style={viewStyles.item(tk, active, false)}
              onClick={() => select(item, index)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault()
                  select(item, index)
                }
              }}
            >
              <span style={textStyles.item(tk, active)}>{label}</span>
            </div>
          )
        })}
      </div>
    </div>
  )
}
