// apps/miniapp/pages/exam/answer.vue
<template>
  <view class="page">
    <view class="header">
      <text class="timer">{{ formatTime(remain) }}</text>
      <text class="progress">{{ currentIdx + 1 }}/{{ questions.length }}</text>
    </view>
    <view class="question" v-if="current">
      <text class="q-title">{{ currentIdx + 1 }}. {{ current.title }}</text>
      <view class="options">
        <view class="option" v-for="(opt, i) in current.options" :key="i" :class="{ active: answers[current.id] === i }" @tap="select(i)">
          <view class="opt-radio">{{ ['A', 'B', 'C', 'D'][i] }}</view>
          <text class="opt-text">{{ opt }}</text>
        </view>
      </view>
    </view>
    <view class="footer">
      <button class="btn" v-if="currentIdx > 0" @tap="prev">上一题</button>
      <button class="btn primary" v-if="currentIdx < questions.length - 1" @tap="next">下一题</button>
      <button class="btn primary" v-else @tap="onSubmit">交卷</button>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed, onUnmounted } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { getExamDetail, submitExam } from '@/api'

const questions = ref<Array<{ id: string; title: string; options: string[] }>>([])
const currentIdx = ref(0)
const answers = ref<Record<string, number>>({})
const remain = ref(0)
const examId = ref('')
let timer: any = null

const current = computed(() => questions.value[currentIdx.value])

onLoad(async (q: any) => {
  examId.value = q.id
  try {
    const exam = await getExamDetail(q.id)
    questions.value = exam.questions || []
    remain.value = exam.duration * 60
    timer = setInterval(() => {
      remain.value--
      if (remain.value <= 0) onSubmit()
    }, 1000)
  } catch (e) {}
})
onUnmounted(() => clearInterval(timer))

function formatTime(s: number) {
  const m = Math.floor(s / 60)
  const sec = s % 60
  return `${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}`
}
function select(i: number) { answers.value[current.value.id] = i }
function prev() { if (currentIdx.value > 0) currentIdx.value-- }
function next() { if (currentIdx.value < questions.value.length - 1) currentIdx.value++ }

async function onSubmit() {
  clearInterval(timer)
  try {
    const res = await submitExam({ examId: examId.value, answers: answers.value })
    uni.redirectTo({ url: `/pages/exam/result?id=${examId.value}&score=${res.score}&pass=${res.pass}` })
  } catch (e) {}
}
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.header { display: flex; justify-content: space-between; padding: 24rpx 32rpx; background: #fff; }
.timer { font-size: 32rpx; color: #dd524d; font-weight: 700; }
.progress { font-size: 26rpx; color: #666; }
.question { margin: 24rpx; padding: 32rpx; background: #fff; border-radius: 16rpx; }
.q-title { font-size: 32rpx; color: #333; font-weight: 600; line-height: 1.6; }
.options { margin-top: 32rpx; }
.option { display: flex; align-items: center; padding: 24rpx; border: 2rpx solid #eee; border-radius: 12rpx; margin-bottom: 16rpx; }
.option.active { border-color: #007aff; background: #e6f0ff; }
.opt-radio { width: 56rpx; height: 56rpx; line-height: 56rpx; text-align: center; border: 2rpx solid #ccc; border-radius: 50%; font-size: 26rpx; color: #666; }
.option.active .opt-radio { border-color: #007aff; background: #007aff; color: #fff; }
.opt-text { flex: 1; margin-left: 24rpx; font-size: 28rpx; color: #333; }
.footer { position: fixed; bottom: 32rpx; left: 32rpx; right: 32rpx; display: flex; gap: 24rpx; }
.btn { flex: 1; background: #fff; color: #333; border-radius: 40rpx; font-size: 30rpx; }
.btn.primary { background: #007aff; color: #fff; }
</style>

// apps/miniapp-taro/src/pages/exam/answer.tsx
import { logger } from '@/utils/logger'
import { View, Text, Input, Textarea, Button } from '@tarojs/components'
import Taro, { useRouter } from '@tarojs/taro'
import { useState, useEffect, useMemo, useCallback, useRef } from 'react'
import {
  getExamPaper,
  getExamQuestions,
  submitExam,
  startExamRecord,
  type QuestionType,
} from '@/api'
import { useI18n } from '@/i18n'

interface Question {
  id: string
  title: string
  type: QuestionType
  options?: string[]
}

type AnswerValue = number | number[] | string | boolean

export default function ExamAnswer() {
  const { t, tList } = useI18n()
  const router = useRouter()
  const [questions, setQuestions] = useState<Question[]>([])
  const [currentIdx, setCurrentIdx] = useState(0)
  const [answers, setAnswers] = useState<Record<string, AnswerValue>>({})
  const [remain, setRemain] = useState(0)
  const recordIdRef = useRef('')
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const submittedRef = useRef(false)
  const onSubmitRef = useRef<() => void>(() => {})

  const judgmentOptions = tList('exam.answer.judgmentOptions')
  const current = useMemo(() => questions[currentIdx], [questions, currentIdx])

  const formatTime = useCallback((s: number) => {
    const m = Math.floor(s / 60)
    const sec = s % 60
    return `${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')}`
  }, [])

  const onSubmit = useCallback(async () => {
    if (submittedRef.current) return
    submittedRef.current = true
    if (timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }
    try {
      const arr = Object.entries(answers).map(([questionId, answer]) => ({ questionId, answer }))
      const res = await submitExam({ recordId: recordIdRef.current, answers: arr })
      Taro.redirectTo({
        url: `/pages/exam/result?id=${recordIdRef.current}&score=${res.result.score}&pass=${res.result.isPassed}`,
      })
    } catch {
      submittedRef.current = false
    }
  }, [answers])

  onSubmitRef.current = onSubmit

  useEffect(() => {
    const id = router.params.id
    if (!id) return
    Promise.all([getExamPaper(id), getExamQuestions(id), startExamRecord(id)])
      .then(([{ paper }, { list }, { record }]) => {
        recordIdRef.current = record.id
        setQuestions((list || []) as unknown as Question[])
        setRemain((paper.duration || 0) * 60)
        timerRef.current = setInterval(() => {
          setRemain((prev) => {
            if (prev <= 1) {
              onSubmitRef.current()
              return 0
            }
            return prev - 1
          })
        }, 1000)
      })
      .catch((e) => {
        logger.error('unknown', '考试加载', e)
        Taro.showToast({ title: t('exam.answer.loadFailed'), icon: 'none' })
      })
    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current)
        timerRef.current = null
      }
    }
  }, [router.params.id, t])

  const select = useCallback(
    (val: AnswerValue) => {
      if (!current) return
      const id = current.id
      setAnswers((prev) => {
        if (current.type === 'multi_choice') {
          const arr = Array.isArray(prev[id]) ? (prev[id] as number[]) : []
          const idx = val as number
          return {
            ...prev,
            [id]: arr.includes(idx) ? arr.filter((n) => n !== idx) : [...arr, idx],
          }
        }
        return { ...prev, [id]: val }
      })
    },
    [current],
  )

  const prev = useCallback(() => {
    setCurrentIdx((idx) => (idx > 0 ? idx - 1 : idx))
  }, [])

  const next = useCallback(() => {
    setCurrentIdx((idx) => (idx < questions.length - 1 ? idx + 1 : idx))
  }, [questions.length])

  const renderAnswer = () => {
    if (!current) return null
    const ans = answers[current.id]
    if (current.type === 'fill_blank') {
      return (
        <Input
          className="w-full text-sm text-foreground p-3 border border-[var(--color-border)] rounded-xl"
          type="text"
          placeholder={t('exam.answer.answerPlaceholder')}
          value={typeof ans === 'string' ? ans : ''}
          onInput={(e) => select(e.detail.value)}
        />
      )
    }
    if (current.type === 'subjective') {
      return (
        <Textarea
          className="w-full text-sm text-foreground p-3 border border-[var(--color-border)] rounded-xl min-h-[320rpx]"
          placeholder={t('exam.answer.answerPlaceholder')}
          value={typeof ans === 'string' ? ans : ''}
          onInput={(e) => select(e.detail.value)}
          maxlength={1000}
        />
      )
    }
    const opts = current.type === 'judgment' ? judgmentOptions : current.options || []
    const isMulti = current.type === 'multi_choice'
    return opts.map((opt, i) => {
      const selected = isMulti
        ? Array.isArray(ans) && (ans as number[]).includes(i)
        : current.type === 'judgment'
          ? ans === (i === 0)
          : ans === i
      const val: AnswerValue = current.type === 'judgment' ? i === 0 : i
      return (
        <View
          key={i}
          className={`flex items-center p-3 border rounded-xl mb-2 ${
            selected ? 'border-primary bg-[var(--color-muted)]' : 'border-[var(--color-border)]'
          }`}
          onClick={() => select(val)}
        >
          <View
            className={`w-7 h-7 leading-7 text-center border text-sm ${
              isMulti ? 'rounded-md' : 'rounded-md'
            } ${
              selected
                ? 'border-primary bg-primary text-white'
                : 'border-[#ccc] text-muted-foreground'
            }`}
          >
            {current.type === 'judgment' ? (i === 0 ? '√' : '×') : String.fromCharCode(65 + i)}
          </View>
          <Text className="flex-1 ml-3 text-sm text-foreground">{opt}</Text>
        </View>
      )
    })
  }

  return (
    <View className="min-h-screen bg-background">
      <View className="flex justify-between p-3 bg-card">
        <Text className="text-base text-[#dd524d] font-bold">{formatTime(remain)}</Text>
        <Text className="text-sm text-muted-foreground">
          {currentIdx + 1}/{questions.length}
        </Text>
      </View>

      {current && (
        <View className="m-3 p-4 bg-card rounded-2xl">
          <Text className="text-base text-foreground font-semibold leading-relaxed">
            {currentIdx + 1}. {current.title}
          </Text>
          <View className="mt-4">{renderAnswer()}</View>
        </View>
      )}

      <View className="fixed bottom-4 left-4 right-4 flex gap-3">
        {currentIdx > 0 && (
          <Button className="flex-1 bg-card text-foreground rounded-md text-sm" onClick={prev}>
            {t('exam.answer.prev')}
          </Button>
        )}
        {currentIdx < questions.length - 1 ? (
          <Button className="flex-1 bg-primary text-white rounded-md text-sm" onClick={next}>
            {t('exam.answer.next')}
          </Button>
        ) : (
          <Button className="flex-1 bg-primary text-white rounded-md text-sm" onClick={onSubmit}>
            {t('exam.answer.submit')}
          </Button>
        )}
      </View>
    </View>
  )
}
