// client/miniapp/src/pages/login-app/login.vue
<template>
  <view class="container-ali" @click="handleContainerClick">
    <view class="container1">
      <view class="container-box">
        <!-- 顶部 Logo -->
        <view class="top_box">
          <view class="logobox">
            <image class="logo" src="/static/images/sqlogo.svg" mode="aspectFit" />
          </view>
          <view class="titlebox">
            <image class="titlebox-image" src="https://test.aizhs.top/minio/sys-mini/loginengtext.png" mode=""></image>
            <image class="titlebox-image1" src="https://test.aizhs.top/minio/sys-mini/loginzhtext.png" mode=""></image>
          </view>
        </view>

        <!-- 登录表单 -->
        <view class="center_box">
          <!-- 登录方式切换 -->
          <view class="select-box">
            <view class="login-type-tabs">
              <view class="login-type-tab" :class="{ 'login-type-tab-active': loginType === 'phone' }" @tap.stop="loginType = 'phone'">
                <text>手机号验证码登录</text>
              </view>
              <view class="login-type-tab" :class="{ 'login-type-tab-active': loginType === 'password' }" @tap.stop="loginType = 'password'">
                <text>手机号密码登录</text>
              </view>
            </view>
          </view>

          <!-- 手机号输入 -->
          <view class="input-wbox" v-if="loginType === 'phone'">
            <view :class="['input-nbox', isPhoneFocused ? 'input-nbox-focused' : '']">
              <view class="input-box">
                <view class="input-icon phone">
                  <image class="phoneimg" src="https://test.aizhs.top/minio/sys-mini/phone-fill.png" mode=""></image>
                </view>
                <input class="input iponeinput input-text" type="text" placeholder="手机号码"
                  placeholder-style="color:#6B6980" v-model="phoneNumber"
                  @focusin="isPhoneFocused = true" @focusout="isPhoneFocused = false" />
              </view>
            </view>
          </view>

          <!-- 账号输入（密码登录） -->
          <view class="input-wbox" v-if="loginType === 'password'">
            <view :class="['input-nbox', isAccountFocused ? 'input-nbox-focused' : '']">
              <view class="input-box">
                <view class="input-icon pwd">
                  <image class="accountimg" src="https://test.aizhs.top/minio/sys-mini/account0.png" mode=""></image>
                </view>
                <input class="input iponeinput input-text" type="text" placeholder="手机号码"
                  placeholder-style="color:#6B6980" v-model="accountValue"
                  @focusin="isAccountFocused = true" @focusout="isAccountFocused = false" />
              </view>
            </view>
          </view>

          <!-- 验证码输入 -->
          <view class="input-wbox" v-if="loginType === 'phone'">
            <view :class="['input-nbox', isCodeFocused ? 'input-nbox-focused' : '']">
              <view class="input-box">
                <view class="input-icon code">
                  <image class="codeimg" src="https://test.aizhs.top/minio/sys-mini/code.png" mode=""></image>
                </view>
                <input class="input iponeinput input-text" type="number" maxlength="6" placeholder="验证码"
                  placeholder-style="color:#6B6980" v-model="verificationCode"
                  @focusin="isCodeFocused = true" @focusout="isCodeFocused = false" />
                <view class="send-code-btn" :class="{ 'code-disabled': codeBtnDisabled }" @tap.stop="sendCode">
                  <text>{{ codeBtnText }}</text>
                </view>
              </view>
            </view>
          </view>

          <!-- 密码输入 -->
          <view class="input-wbox" v-if="loginType === 'password'">
            <view :class="['input-nbox', isPasswordFocused ? 'input-nbox-focused' : '']">
              <view class="input-box">
                <view class="input-icon pwd">
                  <image class="pwdimg" src="https://test.aizhs.top/minio/sys-mini/pwd0.png" mode=""></image>
                </view>
                <input class="input iponeinput input-text" :type="showPassword ? 'text' : 'password'" placeholder="密码"
                  placeholder-style="color:#6B6980" v-model="password"
                  @focusin="isPasswordFocused = true" @focusout="isPasswordFocused = false" />
              </view>
            </view>
          </view>

          <!-- 登录按钮 -->
          <view class="login-btn" @tap.stop="handleLogin">
            <text class="login-btn-text">{{ isLogging ? '登录中...' : '登录' }}</text>
          </view>

          <!-- 其他登录方式 -->
          <view class="other-login">
            <view class="wechat-login" @tap="handleWechatLogin">
              <image class="wechat-icon" src="/static/images/wechat.png" mode=""></image>
              <text>微信登录</text>
            </view>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useUserStore } from '@/store/modules/user'
import { sendTextMsg, userLogin, pwdLogin } from '@/service/login.js'

const userStore = useUserStore()

// 登录类型
const loginType = ref<'phone' | 'password'>('phone')

// 手机号验证码登录
const phoneNumber = ref('')
const verificationCode = ref('')
const isPhoneFocused = ref(false)
const isCodeFocused = ref(false)

// 密码登录
const accountValue = ref('')
const password = ref('')
const isAccountFocused = ref(false)
const isPasswordFocused = ref(false)
const showPassword = ref(false)

// 验证码按钮状态
const codeBtnText = ref('获取验证码')
const codeBtnDisabled = ref(false)
let codeTimer: ReturnType<typeof setTimeout> | null = null

// 登录状态
const isLogging = ref(false)

// 发送验证码
async function sendCode() {
  if (codeBtnDisabled.value) return
  
  if (!phoneNumber.value) {
    uni.showToast({ title: '请输入手机号', icon: 'none' })
    return
  }

  try {
    const res = await sendTextMsg(phoneNumber.value, 1, '')
    const code = res?.data?.code
    const ok = code === 200 || code === '200' || code === 0
    if (!ok) {
      throw new Error(res?.data?.message || '发送失败')
    }
    uni.showToast({ title: '验证码已发送', icon: 'success' })

    // 倒计时
    codeBtnDisabled.value = true
    let seconds = 60
    codeBtnText.value = `${seconds}s`

    codeTimer = setInterval(() => {
      seconds--
      if (seconds <= 0) {
        clearInterval(codeTimer!)
        codeBtnDisabled.value = false
        codeBtnText.value = '获取验证码'
      } else {
        codeBtnText.value = `${seconds}s`
      }
    }, 1000)
  } catch (error) {
    uni.showToast({ title: error?.message || '发送失败', icon: 'none' })
  }
}

// 登录
async function handleLogin() {
  if (isLogging.value) return
  
  if (loginType.value === 'phone') {
    if (!phoneNumber.value) {
      uni.showToast({ title: '请输入手机号', icon: 'none' })
      return
    }
    if (!verificationCode.value) {
      uni.showToast({ title: '请输入验证码', icon: 'none' })
      return
    }
  } else {
    if (!accountValue.value) {
      uni.showToast({ title: '请输入手机号', icon: 'none' })
      return
    }
    if (!password.value) {
      uni.showToast({ title: '请输入密码', icon: 'none' })
      return
    }
  }

  isLogging.value = true
  
  try {
    let res
    if (loginType.value === 'phone') {
      res = await userLogin(phoneNumber.value, '', verificationCode.value)
    } else {
      res = await pwdLogin(accountValue.value, password.value)
    }
    const code = res?.data?.code
    const ok = code === 200 || code === '200' || code === 0
    if (!ok) {
      throw new Error(res?.data?.message || '登录失败')
    }
    // 保存登录信息
    const loginData = res?.data?.data || {}
    uni.setStorageSync('data', loginData)
    if (loginData.thirdPartyAccounts?.accessToken) {
      uni.setStorageSync('token', loginData.thirdPartyAccounts.accessToken)
    }
    uni.showToast({ title: '登录成功', icon: 'success' })

    // 跳转到主页
    setTimeout(() => {
      uni.reLaunch({ url: '/pages/table/aiIndex/ai_index' })
    }, 1500)
  } catch (error) {
    uni.showToast({ title: error?.message || '登录失败', icon: 'none' })
  } finally {
    isLogging.value = false
  }
}

// 微信登录
async function handleWechatLogin() {
  try {
    const loginRes = await uni.login({ provider: 'weixin' })
    if (loginRes.code) {
      // TODO: 调用微信登录 API
      uni.showToast({ title: '微信登录成功', icon: 'success' })
    }
  } catch (error) {
    uni.showToast({ title: '微信登录失败', icon: 'none' })
  }
}

function handleContainerClick() {
  // 点击容器
}
</script>

<style lang="scss" scoped>
.container-ali {
  min-height: 100vh;
  background: #fff;
}

.container1 {
  padding: 0 40rpx;
}

.top_box {
  padding-top: 150rpx;
  text-align: center;
}

.logobox {
  margin-bottom: 30rpx;
}

.logo {
  width: 160rpx;
  height: 160rpx;
}

.titlebox {
  margin-bottom: 60rpx;
}

.titlebox-image {
  width: 310rpx;
  height: 37rpx;
  display: block;
  margin: 0 auto 10rpx;
}

.titlebox-image1 {
  width: 312rpx;
  height: 66rpx;
  display: block;
  margin: 0 auto;
}

.login-type-tabs {
  display: flex;
  justify-content: center;
  margin-bottom: 40rpx;
}

.login-type-tab {
  padding: 16rpx 30rpx;
  font-size: 28rpx;
  color: #666;
  border-bottom: 4rpx solid transparent;
  
  &.login-type-tab-active {
    color: #000;
    font-weight: bold;
    border-bottom-color: #000;
  }
}

.input-wbox {
  margin-bottom: 24rpx;
}

.input-nbox {
  border: 2rpx solid #e5e5e5;
  border-radius: 16rpx;
  padding: 20rpx;
  transition: all 0.3s;
  
  &.input-nbox-focused {
    border-color: #000;
  }
}

.input-box {
  display: flex;
  align-items: center;
}

.input-icon {
  width: 40rpx;
  height: 40rpx;
  margin-right: 16rpx;
  
  image {
    width: 100%;
    height: 100%;
  }
}

.input {
  flex: 1;
  height: 60rpx;
  font-size: 32rpx;
}

.send-code-btn {
  padding: 10rpx 20rpx;
  background: #f5f5f5;
  border-radius: 8rpx;
  font-size: 24rpx;
  color: #333;
  
  &.code-disabled {
    color: #999;
  }
}

.login-btn {
  margin-top: 40rpx;
  padding: 24rpx;
  background: #000;
  border-radius: 12rpx;
  text-align: center;
}

.login-btn-text {
  color: #fff;
  font-size: 32rpx;
  font-weight: bold;
}

.other-login {
  margin-top: 60rpx;
  text-align: center;
}

.wechat-login {
  display: inline-flex;
  align-items: center;
  padding: 20rpx 40rpx;
  background: #07c160;
  border-radius: 12rpx;
  color: #fff;
  font-size: 28rpx;
  
  .wechat-icon {
    width: 40rpx;
    height: 40rpx;
    margin-right: 10rpx;
  }
}
</style>

// apps/miniapp-taro/src/pages/login/login.tsx
import { View, Text, Input } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { useState, useMemo, useRef, useEffect } from 'react'
import { useUserStore } from '@/stores/user'
import { sendSmsCode, loginBySms, loginByPassword, loginByWechat } from '@/api'

export default function Login() {
  const { setAuth } = useUserStore()
  const [loginType, setLoginType] = useState<'phone' | 'password'>('phone')
  const [phone, setPhone] = useState('')
  const [code, setCode] = useState('')
  const [password, setPassword] = useState('')
  const [isLogging, setIsLogging] = useState(false)
  const [countdown, setCountdown] = useState(0)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  const codeBtnText = useMemo(() => (countdown > 0 ? `${countdown}s` : '获取验证码'), [countdown])
  const codeBtnDisabled = useMemo(() => countdown > 0 || phone.length !== 11, [countdown, phone])

  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current)
    }
  }, [])

  async function sendCode() {
    if (codeBtnDisabled) return
    try {
      await sendSmsCode(phone)
      Taro.showToast({ title: '验证码已发送', icon: 'success' })
      setCountdown(60)
      timerRef.current = setInterval(() => {
        setCountdown(prev => {
          if (prev <= 1 && timerRef.current) {
            clearInterval(timerRef.current)
            timerRef.current = null
          }
          return prev <= 1 ? 0 : prev - 1
        })
      }, 1000)
    } catch (e) {
      // 错误已由 request 统一提示
    }
  }

  async function handleLogin() {
    if (isLogging) return
    if (phone.length !== 11) {
      Taro.showToast({ title: '请输入正确手机号', icon: 'none' })
      return
    }
    setIsLogging(true)
    try {
      const res =
        loginType === 'phone'
          ? await loginBySms(phone, code)
          : await loginByPassword(phone, password)
      setAuth(res.token, res.user)
      Taro.showToast({ title: '登录成功', icon: 'success' })
      setTimeout(() => Taro.reLaunch({ url: '/pages/index/index' }), 600)
    } catch (e) {
      // 错误已统一提示
    } finally {
      setIsLogging(false)
    }
  }

  function handleWechatLogin() {
    if (process.env.TARO_ENV === 'weapp') {
      Taro.login({
        success: async (res) => {
          try {
            const data = await loginByWechat(res.code)
            setAuth(data.token, data.user)
            Taro.reLaunch({ url: '/pages/index/index' })
          } catch (e) {
            Taro.showToast({ title: '微信登录失败', icon: 'none' })
          }
        },
      })
    } else {
      Taro.showToast({ title: '请在微信小程序中使用', icon: 'none' })
    }
  }

  return (
    <View className="min-h-screen px-[24px] bg-white">
      {/* 顶部 Logo */}
      <View className="pt-[80px] pb-[40px] text-center">
        <Text className="text-[28px] font-bold text-[#007aff]">智汇AI</Text>
        <Text className="block mt-[8px] text-[13px] text-[#999]">AI 赋能学习与成长</Text>
      </View>

      {/* 登录方式切换 */}
      <View className="flex mb-[24px]">
        <View
          className={`flex-1 text-center py-[10px] text-[15px] border-b-[2px] border-solid ${
            loginType === 'phone'
              ? 'text-[#007aff] font-semibold border-[#007aff]'
              : 'text-[#999] border-transparent'
          }`}
          onClick={() => setLoginType('phone')}
        >
          <Text>验证码登录</Text>
        </View>
        <View
          className={`flex-1 text-center py-[10px] text-[15px] border-b-[2px] border-solid ${
            loginType === 'password'
              ? 'text-[#007aff] font-semibold border-[#007aff]'
              : 'text-[#999] border-transparent'
          }`}
          onClick={() => setLoginType('password')}
        >
          <Text>密码登录</Text>
        </View>
      </View>

      {/* 手机号 */}
      <View className="flex items-center h-[48px] mb-[16px] border-b-[1px] border-solid border-[#eee]">
        <Input
          className="flex-1 h-[48px] text-[15px]"
          type="number"
          maxlength={11}
          placeholder="请输入手机号"
          value={phone}
          onInput={e => setPhone(e.detail.value)}
        />
      </View>

      {/* 验证码 */}
      {loginType === 'phone' ? (
        <View className="flex items-center h-[48px] mb-[16px] border-b-[1px] border-solid border-[#eee]">
          <Input
            className="flex-1 h-[48px] text-[15px]"
            type="number"
            maxlength={6}
            placeholder="请输入验证码"
            value={code}
            onInput={e => setCode(e.detail.value)}
          />
          <View
            className={`px-[10px] text-[13px] ${codeBtnDisabled ? 'text-[#ccc]' : 'text-[#007aff]'}`}
            onClick={sendCode}
          >
            <Text>{codeBtnText}</Text>
          </View>
        </View>
      ) : null}

      {/* 密码 */}
      {loginType === 'password' ? (
        <View className="flex items-center h-[48px] mb-[16px] border-b-[1px] border-solid border-[#eee]">
          <Input
            className="flex-1 h-[48px] text-[15px]"
            password
            placeholder="请输入密码"
            value={password}
            onInput={e => setPassword(e.detail.value)}
          />
        </View>
      ) : null}

      {/* 登录按钮 */}
      <View
        className={`h-[48px] mt-[12px] rounded-[24px] flex items-center justify-center text-white text-[16px] bg-[#007aff] ${
          isLogging ? 'opacity-60' : ''
        }`}
        onClick={handleLogin}
      >
        <Text>{isLogging ? '登录中...' : '登录'}</Text>
      </View>

      {/* 微信登录 */}
      <View className="mt-[24px] text-center text-[14px] text-[#07c160]" onClick={handleWechatLogin}>
        <Text>微信一键登录</Text>
      </View>

      <View className="mt-[30px] text-center text-[11px] text-[#999]">
        <Text>登录即代表同意《用户协议》和《隐私政策》</Text>
      </View>
    </View>
  )
}
