// apps/miniapp-taro/src/pages/distribution/team.tsx
import { View, Text, Image } from '@tarojs/components'
import { useReachBottom } from '@tarojs/taro'
import { useState, useRef, useEffect } from 'react'
import { getDistributionTeam } from '@/api'

interface TeamMember {
  id: string
  nickname: string
  avatar?: string
  joinTime: string
  level: number
}

const PAGE_SIZE = 20

export default function DistributionTeam() {
  const [list, setList] = useState<TeamMember[]>([])
  const [loading, setLoading] = useState(false)
  const pageRef = useRef(1)
  const hasMoreRef = useRef(true)
  const loadingRef = useRef(false)

  const load = async (reset = false) => {
    if (loadingRef.current) return
    if (reset) {
      pageRef.current = 1
      hasMoreRef.current = true
      setList([])
    }
    if (!hasMoreRef.current) return
    loadingRef.current = true
    setLoading(true)
    try {
      const res = await getDistributionTeam({ page: pageRef.current, pageSize: PAGE_SIZE })
      const items = (res.list || []).map((u): TeamMember => ({
        id: u.id,
        nickname: u.nickname || u.username,
        avatar: u.avatar ?? undefined,
        joinTime: u.createdAt,
        level: 1,
      }))
      setList((prev) => (reset ? items : [...prev, ...items]))
      hasMoreRef.current = pageRef.current * PAGE_SIZE < res.total
      pageRef.current++
    } catch {
      // ignore
    } finally {
      loadingRef.current = false
      setLoading(false)
    }
  }

  useEffect(() => {
    load(true)
  }, [])

  useReachBottom(() => {
    load()
  })

  return (
    <View className="min-h-screen bg-[#f7f8fa]">
      {list.length > 0 && (
        <View className="p-[12px]">
          {list.map((m) => (
            <View
              key={m.id}
              className="flex items-center bg-white p-[12px] mb-[12px] rounded-[8px]"
            >
              <Image
                className="w-[40px] h-[40px] rounded-full bg-[#f5f5f5]"
                src={m.avatar || '/static/default-avatar.png'}
                mode="aspectFill"
              />
              <View className="flex-1 ml-[12px]">
                <Text className="block text-[14px] text-[#333]">{m.nickname}</Text>
                <Text className="block text-[12px] text-[#999] mt-[4px]">
                  加入时间：{m.joinTime}
                </Text>
              </View>
              <Text className="text-[14px] text-[#ff6b35] font-semibold">V{m.level}</Text>
            </View>
          ))}
        </View>
      )}
      {list.length === 0 && !loading && (
        <View className="text-center py-[60px] text-[#999]">
          <Text>暂无团队成员</Text>
        </View>
      )}
      {loading && (
        <View className="text-center py-[20px] text-[#999]">
          <Text>加载中...</Text>
        </View>
      )}
    </View>
  )
}

// apps/miniapp/pages/distribution/team.vue
<template>
  <view class="page">
    <view class="summary">团队总人数：{{ total }}</view>
    <view class="list" v-if="list.length">
      <view class="item" v-for="m in list" :key="m.id">
        <image class="avatar" :src="m.avatar || '/static/default-avatar.png'" mode="aspectFill" />
        <view class="item-body">
          <text class="name">{{ m.nickname }}</text>
          <text class="time">加入时间：{{ m.joinTime }}</text>
        </view>
        <text class="level">L{{ m.level }}</text>
      </view>
    </view>
    <view class="empty" v-else-if="!loading"><text>暂无团队成员</text></view>
    <view class="loading" v-if="loading"><text>加载中...</text></view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onReachBottom } from '@dcloudio/uni-app'
import { getDistributionTeam } from '@/api'

const list = ref<Array<{ id: string; nickname: string; avatar?: string; joinTime: string; level: number }>>([])
const loading = ref(false)
const total = ref(0)
const page = ref(1)
const hasMore = ref(true)

async function load(reset = false) {
  if (loading.value) return
  if (reset) { page.value = 1; hasMore.value = true; list.value = [] }
  if (!hasMore.value) return
  loading.value = true
  try {
    const res = await getDistributionTeam({ page: page.value, pageSize: 20 })
    list.value.push(...(res.list || []))
    total.value = res.total
    hasMore.value = list.value.length < res.total
    page.value++
  } finally { loading.value = false }
}
onReachBottom(() => load())
load()
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.summary { padding: 24rpx 32rpx; font-size: 26rpx; color: #666; }
.list { padding: 0 24rpx; }
.item { display: flex; align-items: center; background: #fff; padding: 24rpx; margin-bottom: 24rpx; border-radius: 16rpx; }
.avatar { width: 80rpx; height: 80rpx; border-radius: 50%; background: #f5f5f5; }
.item-body { flex: 1; margin-left: 24rpx; }
.name { display: block; font-size: 28rpx; color: #333; }
.time { display: block; font-size: 22rpx; color: #999; margin-top: 8rpx; }
.level { font-size: 24rpx; color: #ff6e3c; }
.empty, .loading { text-align: center; padding: 120rpx 0; color: #999; }
</style>
