// apps/web/src/components/data/Avatar.tsx
﻿'use client'

import * as React from 'react'
import { cn } from '@/lib/utils'

type AvatarSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl'
type AvatarShape = 'circle' | 'square'

interface AvatarProps {
  src?: string
  fallback?: string
  name?: string
  size?: AvatarSize
  shape?: AvatarShape
  className?: string
}

const sizeMap: Record<AvatarSize, string> = {
  xs: 'h-6 w-6 text-[10px]',
  sm: 'h-8 w-8 text-xs',
  md: 'h-10 w-10 text-sm',
  lg: 'h-12 w-12 text-base',
  xl: 'h-16 w-16 text-xl',
}

export function Avatar({
  src,
  fallback,
  name,
  size = 'md',
  shape = 'circle',
  className,
}: AvatarProps) {
  const [error, setError] = React.useState(false)
  const initials = fallback ?? (name ? name.slice(0, 2) : '?')

  return (
    <span
      className={cn(
        'inline-flex shrink-0 items-center justify-center overflow-hidden bg-muted font-medium text-muted-foreground',
        sizeMap[size],
        shape === 'circle' ? 'rounded-full' : 'rounded-lg',
        className,
      )}
    >
      {src && !error ? (
        <img
          src={src}
          alt={name ?? 'avatar'}
          className="h-full w-full object-cover"
          onError={() => setError(true)}
        />
      ) : (
        initials
      )}
    </span>
  )
}

// client/src/components/ui/avatar/Avatar.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { ref, computed } from 'vue'
import { cn } from '@/lib/utils'

const props = withDefaults(
  defineProps<{
    src?: string
    size?: number | 'default' | 'small' | 'large'
    shape?: 'circle' | 'square'
    icon?: string
    class?: HTMLAttributes['class']
  }>(),
  {
    size: 'default',
    shape: 'circle',
  },
)

const hasError = ref(false)

const sizeClass = computed(() => {
  if (typeof props.size === 'number') return ''
  if (props.size === 'small') return 'h-8 w-8'
  if (props.size === 'large') return 'h-12 w-12'
  return 'h-10 w-10'
})

const sizeStyle = computed(() => {
  if (typeof props.size === 'number') {
    return { width: props.size + 'px', height: props.size + 'px' }
  }
  return {}
})
</script>

<template>
  <span
    :class="
      cn(
        'inline-flex shrink-0 select-none items-center justify-center overflow-hidden bg-muted text-muted-foreground',
        shape === 'circle' ? 'rounded-full' : 'rounded-md',
        sizeClass,
        props.class,
      )
    "
    :style="sizeStyle"
  >
    <img
      v-if="src && !hasError"
      :src="src"
      class="h-full w-full object-cover"
      @error="hasError = true"
    />
    <svg
      v-else
      xmlns="http://www.w3.org/2000/svg"
      class="h-1/2 w-1/2"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  </span>
</template>
