// apps/web/app/(main)/admin/visit-tracking/page.tsx
'use client'

import * as React from 'react'
import { useQuery } from '@tanstack/react-query'
import { Eye, Users, RefreshCw, MapPin, Loader2, Search } from 'lucide-react'
import { eduApi, buildQs } from '@/lib/edu'
import { StatCard } from '@/components/data'
import { BarChart } from '@/components/charts'
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  Button,
  Input,
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from '@ihui/ui'

interface VisitStats {
  pv?: number
  uv?: number
  vv?: number
  ip?: number
  ipNum?: number
  [k: string]: unknown
}
interface TrendItem {
  visitDate?: string
  date?: string
  pv?: number
  uv?: number
  [k: string]: unknown
}
interface VisitRow {
  id?: string | number
  ip?: string
  ipCityName?: string
  city?: string
  url?: string
  referer?: string
  userAgent?: string
  visitDate?: string
  createTime?: string
  [k: string]: unknown
}
interface PageList<T> {
  list?: T[]
  total?: number
}

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString().slice(0, 10)
}

const inputCls =
  'h-9 rounded-md border border-input bg-transparent px-3 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring'

export default function VisitTrackingPage() {
  const [start, setStart] = React.useState(daysAgo(7))
  const [end, setEnd] = React.useState(daysAgo(0))
  const [keyword, setKeyword] = React.useState('')
  const [page, setPage] = React.useState(1)
  const pageSize = 15

  const qs = buildQs({ startTime: start, endTime: end })
  const listQs = buildQs({
    startTime: start,
    endTime: end,
    url: keyword || undefined,
    page,
    pageSize,
  })

  const { data: statsResp, isLoading: ls } = useQuery({
    queryKey: ['visit-tracking', 'stats', start, end],
    queryFn: () => eduApi<{ summary: VisitStats }>(`/api/admin/visit-tracking/summary${qs}`),
  })
  const { data: pvTrend, isLoading: lt } = useQuery({
    queryKey: ['visit-tracking', 'pv', start, end],
    queryFn: () => eduApi<PageList<TrendItem>>(`/api/admin/visit-tracking/day/pv/list${qs}`),
  })
  const { data: uvTrend } = useQuery({
    queryKey: ['visit-tracking', 'uv', start, end],
    queryFn: () => eduApi<PageList<TrendItem>>(`/api/admin/visit-tracking/day/uv/list${qs}`),
  })
  const { data: listData, isLoading: ll } = useQuery({
    queryKey: ['visit-tracking', 'list', start, end, keyword, page],
    queryFn: () => eduApi<PageList<VisitRow>>(`/api/admin/visit-tracking/log/list${listQs}`),
  })

  const trendArr = React.useMemo(() => {
    const pvList = pvTrend?.list ?? []
    const uvList = uvTrend?.list ?? []
    const uvMap = new Map(uvList.map((u) => [u.visitDate ?? u.date ?? '', u.uv ?? 0]))
    return pvList.map((p) => ({
      visitDate: p.visitDate ?? p.date,
      pv: p.pv ?? 0,
      uv: uvMap.get(p.visitDate ?? p.date ?? '') ?? 0,
    }))
  }, [pvTrend, uvTrend])
  const stats = statsResp?.summary
  const trendLabels = trendArr.map((t) => (t.visitDate ?? '').slice(5))
  const pvSeries = trendArr.map((t) => Number(t.pv ?? 0))
  const uvSeries = trendArr.map((t) => Number(t.uv ?? 0))

  const list = listData?.list ?? []
  const total = listData?.total ?? 0
  const totalPages = Math.max(1, Math.ceil(total / pageSize))

  const cards = [
    { title: '总浏览量 PV', value: stats?.pv ?? 0, icon: Eye, loading: ls },
    { title: '总访客数 UV', value: stats?.uv ?? 0, icon: Users, loading: ls },
    { title: '总访问次数 VV', value: stats?.vv ?? 0, icon: RefreshCw, loading: ls },
    { title: 'IP 数', value: stats?.ipNum ?? stats?.ip ?? 0, icon: MapPin, loading: ls },
  ]

  function setRecent(days: number) {
    setStart(daysAgo(days))
    setEnd(daysAgo(0))
    setPage(1)
  }
  function refreshAll() {
    setPage(1)
  }

  return (
    <div className="space-y-6">
      <header className="space-y-1">
        <h1 className="text-2xl font-bold tracking-tight">访问追踪统计</h1>
        <p className="text-sm text-muted-foreground">日期范围筛选 · PV/UV 概览 · 趋势与来源明细</p>
      </header>

      <div className="flex flex-wrap items-center gap-2">
        <span className="text-sm text-muted-foreground">日期范围：</span>
        <Input
          type="date"
          value={start}
          onChange={(e) => setStart(e.target.value)}
          className={`${inputCls} w-40`}
        />
        <span className="text-sm text-muted-foreground">至</span>
        <Input
          type="date"
          value={end}
          onChange={(e) => setEnd(e.target.value)}
          className={`${inputCls} w-40`}
        />
        <Button size="sm" onClick={refreshAll}>
          查询
        </Button>
        <Button variant="outline" size="sm" onClick={() => setRecent(7)}>
          近 7 天
        </Button>
        <Button variant="outline" size="sm" onClick={() => setRecent(30)}>
          近 30 天
        </Button>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        {cards.map((c) => (
          <StatCard
            key={c.title}
            title={c.title}
            value={c.loading ? '—' : c.value}
            icon={c.icon}
            loading={c.loading}
          />
        ))}
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        {(
          [
            { title: '浏览量趋势 (PV)', series: pvSeries, color: 'var(--primary)' },
            { title: '访客数趋势 (UV)', series: uvSeries, color: '#f97316' },
          ] as const
        ).map((c) => (
          <Card key={c.title}>
            <CardHeader className="pb-2">
              <CardTitle className="text-base">{c.title}</CardTitle>
            </CardHeader>
            <CardContent>
              {lt ? (
                <div className="flex items-center justify-center py-10 text-muted-foreground">
                  <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                  加载中...
                </div>
              ) : c.series.length ? (
                <BarChart data={c.series} xAxis={trendLabels} height={240} color={c.color} />
              ) : (
                <p className="py-10 text-center text-sm text-muted-foreground">暂无数据</p>
              )}
            </CardContent>
          </Card>
        ))}
      </div>

      <Card>
        <CardHeader className="pb-2">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <CardTitle className="text-base">访问明细</CardTitle>
            <div className="flex items-center gap-2">
              <Input
                value={keyword}
                onChange={(e) => setKeyword(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && refreshAll()}
                placeholder="输入 IP / 路径搜索"
                className={`${inputCls} w-56`}
              />
              <Button size="sm" variant="outline" onClick={refreshAll}>
                <Search className="h-4 w-4" />
                搜索
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto rounded-lg border">
            <Table>
              <TableHeader className="bg-muted/50">
                <TableRow>
                  <TableHead className="px-3 py-2">IP 地址</TableHead>
                  <TableHead className="px-3 py-2">所在城市</TableHead>
                  <TableHead className="px-3 py-2">访问路径</TableHead>
                  <TableHead className="px-3 py-2">来源</TableHead>
                  <TableHead className="px-3 py-2">访问日期</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody className="divide-y">
                {ll ? (
                  <TableRow>
                    <TableCell colSpan={5} className="px-3 py-8 text-center text-muted-foreground">
                      <Loader2 className="mr-2 inline h-4 w-4 animate-spin" />
                      加载中...
                    </TableCell>
                  </TableRow>
                ) : list.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={5} className="px-3 py-8 text-center text-muted-foreground">
                      暂无数据
                    </TableCell>
                  </TableRow>
                ) : (
                  list.map((row, i) => (
                    <TableRow key={row.id ?? i} className="hover:bg-muted/30">
                      <TableCell className="px-3 py-2 font-mono text-xs">{row.ip ?? '-'}</TableCell>
                      <TableCell className="px-3 py-2">
                        {row.ipCityName ?? row.city ?? '-'}
                      </TableCell>
                      <TableCell
                        className="max-w-[220px] truncate px-3 py-2 text-muted-foreground"
                        title={row.url}
                      >
                        {row.url ?? '-'}
                      </TableCell>
                      <TableCell className="px-3 py-2 text-muted-foreground">
                        {row.referer ?? '-'}
                      </TableCell>
                      <TableCell className="px-3 py-2 text-xs text-muted-foreground">
                        {row.visitDate ?? row.createTime ?? '-'}
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
          {totalPages > 1 && (
            <div className="mt-3 flex items-center justify-end gap-2">
              <Button
                variant="outline"
                size="sm"
                disabled={page <= 1}
                onClick={() => setPage((p) => Math.max(1, p - 1))}
              >
                上一页
              </Button>
              <span className="text-sm text-muted-foreground">
                {page} / {totalPages}
              </span>
              <Button
                variant="outline"
                size="sm"
                disabled={page >= totalPages}
                onClick={() => setPage((p) => p + 1)}
              >
                下一页
              </Button>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

// client/src/views/edu/admin/visit-tracking/index.vue
<template>
  <div class="visit-container">
    <!-- 日期范围筛选 -->
    <div class="head">
      <span class="filter-label">日期范围：</span>
      <div class="flex items-center gap-2">
        <Input
          type="date"
          size="small"
          v-model="dateRange[0]"
          placeholder="开始日期"
          @change="onDateChange"
        />
        <span class="text-muted-foreground">至</span>
        <Input
          type="date"
          size="small"
          v-model="dateRange[1]"
          placeholder="结束日期"
          @change="onDateChange"
        />
      </div>
      <Button variant="default" size="sm" @click="refreshAll">查询</Button>
      <Button variant="outline" size="sm" @click="setRecentDays(7)">近7天</Button>
      <Button variant="outline" size="sm" @click="setRecentDays(30)">近30天</Button>
    </div>

    <!-- 统计概览 -->
    <div class="stat-box">
      <div class="stat-card stat-pv">
        <div class="stat-icon"><View class="h-5 w-5" /></div>
        <div class="stat-info">
          <div class="stat-title">总浏览量 PV</div>
          <div class="stat-value">{{ statistics.pv || 0 }}</div>
        </div>
      </div>
      <div class="stat-card stat-uv">
        <div class="stat-icon"><User class="h-5 w-5" /></div>
        <div class="stat-info">
          <div class="stat-title">总访客数 UV</div>
          <div class="stat-value">{{ statistics.uv || 0 }}</div>
        </div>
      </div>
      <div class="stat-card stat-vv">
        <div class="stat-icon"><DataLine class="h-5 w-5" /></div>
        <div class="stat-info">
          <div class="stat-title">总访问次数 VV</div>
          <div class="stat-value">{{ statistics.vv || 0 }}</div>
        </div>
      </div>
      <div class="stat-card stat-ip">
        <div class="stat-icon"><LocationInformation class="h-5 w-5" /></div>
        <div class="stat-info">
          <div class="stat-title">IP 数</div>
          <div class="stat-value">{{ statistics.ipNum || statistics.ip || 0 }}</div>
        </div>
      </div>
    </div>

    <!-- 趋势图表 -->
    <div class="chart-row">
      <div class="chart-card">
        <div class="chart-header">浏览量趋势 (PV)</div>
        <div class="chart-canvas" ref="pvChartRef"></div>
      </div>
      <div class="chart-card">
        <div class="chart-header">访客数趋势 (UV)</div>
        <div class="chart-canvas" ref="uvChartRef"></div>
      </div>
    </div>

    <!-- 明细列表 -->
    <div class="list-section">
      <div class="list-header">
        <span>访问明细</span>
        <Input
          v-model="listParam.keyword"
          clearable
          size="small"
          placeholder="输入IP/路径搜索"
          class="list-search"
          @keyup.enter="searchList"
        />
        <Button variant="default" size="sm" @click="searchList"><Search />搜索</Button>
      </div>
      <div v-if="listLoading" class="loading-div">加载中...</div>
      <Table class="text-sm" style="width: 100%">
        <TableHeader>
          <TableRow>
            <TableHead class="w-[70px]">ID</TableHead>
            <TableHead class="w-[140px]">IP地址</TableHead>
            <TableHead class="w-[120px]">所在城市</TableHead>
            <TableHead class="min-w-[220px]">访问路径</TableHead>
            <TableHead class="min-w-[160px]">来源</TableHead>
            <TableHead class="min-w-[200px]">浏览器UA</TableHead>
            <TableHead class="w-[120px]">访问日期</TableHead>
            <TableHead class="w-[160px]">访问时间</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow v-for="(row, index) in list" :key="row.id ?? index">
            <TableCell>{{ row.id }}</TableCell>
            <TableCell>{{ row.ip }}</TableCell>
            <TableCell>{{ row.ipCityName || row.city || '-' }}</TableCell>
            <TableCell>{{ row.url }}</TableCell>
            <TableCell>{{ row.referer || '-' }}</TableCell>
            <TableCell>{{ row.userAgent || '-' }}</TableCell>
            <TableCell>{{ row.visitDate }}</TableCell>
            <TableCell>{{ row.createTime }}</TableCell>
          </TableRow>
        </TableBody>
      </Table>
      <page :total="total" :current-change="currentChange" :size-change="sizeChange" :page-size="listParam.size" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick } from 'vue'
import * as echarts from 'echarts'
import Page from '@/components/Page/index.vue'
import { indexApi } from '@/api/edu/admin-api'
import { Search, View, User, DataLine, LocationInformation } from '@/lib/lucide-fallback'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import Button from '@/components/ui/Button.vue'
import { Input } from '@/components/ui/input'

const { getStatistics, getVisitList, getDayPvList, getDayUvList } = indexApi

// 日期工具：返回 N 天前的日期字符串 YYYY-MM-DD
const getDaysAgo = (day: number) => {
  const d = new Date()
  d.setTime(d.getTime() - day * 24 * 60 * 60 * 1000)
  const month = d.getMonth() + 1 < 10 ? '0' + (d.getMonth() + 1) : d.getMonth() + 1
  const date = d.getDate() < 10 ? '0' + d.getDate() : d.getDate()
  return d.getFullYear() + '-' + month + '-' + date
}

// 日期范围
const dateRange = ref<[string, string]>([getDaysAgo(7), getDaysAgo(0)])

const onDateChange = () => {
  refreshAll()
}
const setRecentDays = (days: number) => {
  dateRange.value = [getDaysAgo(days), getDaysAgo(0)]
  refreshAll()
}

// 统计概览
const statistics = ref<any>({})
const loadStatistics = () => {
  const params: any = {
    startDate: dateRange.value[0],
    endDate: dateRange.value[1]
  }
  getStatistics(
    params,
    (res: any) => {
      if (res) statistics.value = res
    },
    true
  )
}

// 明细列表
const list = ref<any[]>([])
const total = ref(0)
const listLoading = ref(true)
const listParam = ref({
  keyword: '',
  size: 20,
  current: 1,
  startDate: dateRange.value[0],
  endDate: dateRange.value[1]
})

const loadList = () => {
  listLoading.value = true
  listParam.value.startDate = dateRange.value[0]
  listParam.value.endDate = dateRange.value[1]
  getVisitList(
    listParam.value,
    (res: any) => {
      listLoading.value = false
      if (!res) return
      list.value = res.list || []
      total.value = res.total || 0
    },
    true
  )
}

const currentChange = (currentPage: number) => {
  listParam.value.current = currentPage
  loadList()
}
const sizeChange = (size: number) => {
  listParam.value.size = size
  loadList()
}
const searchList = () => {
  listParam.value.current = 1
  loadList()
}

// 图表
const pvChartRef = ref<HTMLElement | null>(null)
const uvChartRef = ref<HTMLElement | null>(null)
let pvChart: any = null
let uvChart: any = null

const renderPvChart = (xAxisData: string[], seriesData: number[]) => {
  if (!pvChartRef.value) return
  if (pvChart) {
    pvChart.dispose()
  }
  pvChart = echarts.init(pvChartRef.value)
  pvChart.setOption({
    tooltip: { trigger: 'axis' },
    xAxis: { type: 'category', data: xAxisData, axisLabel: { rotate: 30 } },
    yAxis: { type: 'value' },
    grid: { top: '12%', right: '5%', bottom: '18%', left: '8%' },
    series: [
      {
        name: '浏览量',
        data: seriesData,
        type: 'bar',
        barWidth: '40%',
        itemStyle: {
          color: { type: 'linear', x: 0, y: 0, x2: 0, y2: 1, colorStops: [{ offset: 0, color: '#7D83FF' }, { offset: 1, color: '#3D43C6' }] },
          borderRadius: [6, 6, 0, 0]
        }
      },
      {
        name: '趋势',
        data: seriesData,
        type: 'line',
        smooth: true,
        lineStyle: { color: '#FF6B81', width: 2 },
        itemStyle: { color: '#FF6B81' }
      }
    ]
  })
}

const renderUvChart = (xAxisData: string[], seriesData: number[]) => {
  if (!uvChartRef.value) return
  if (uvChart) {
    uvChart.dispose()
  }
  uvChart = echarts.init(uvChartRef.value)
  uvChart.setOption({
    tooltip: { trigger: 'axis' },
    xAxis: { type: 'category', data: xAxisData, axisLabel: { rotate: 30 } },
    yAxis: { type: 'value' },
    grid: { top: '12%', right: '5%', bottom: '18%', left: '8%' },
    series: [
      {
        name: '访客数',
        data: seriesData,
        type: 'bar',
        barWidth: '40%',
        itemStyle: {
          color: { type: 'linear', x: 0, y: 0, x2: 0, y2: 1, colorStops: [{ offset: 0, color: '#FF8A9B' }, { offset: 1, color: '#FF6B81' }] },
          borderRadius: [6, 6, 0, 0]
        }
      },
      {
        name: '趋势',
        data: seriesData,
        type: 'line',
        smooth: true,
        lineStyle: { color: '#5B8FF9', width: 2 },
        itemStyle: { color: '#5B8FF9' }
      }
    ]
  })
}

const loadTrend = () => {
  const params = { startDate: dateRange.value[0], endDate: dateRange.value[1] }
  const pvXAxis: string[] = []
  const pvSeries: number[] = []
  getDayPvList(
    params,
    (res: any) => {
      if (res && res.length) {
        for (const item of res) {
          pvXAxis.push(item.visitDate)
          pvSeries.push(item.pv || 0)
        }
      }
      renderPvChart(pvXAxis, pvSeries)
    },
    true
  )
  const uvXAxis: string[] = []
  const uvSeries: number[] = []
  getDayUvList(
    params,
    (res: any) => {
      if (res && res.length) {
        for (const item of res) {
          uvXAxis.push(item.visitDate)
          uvSeries.push(item.uv || 0)
        }
      }
      renderUvChart(uvXAxis, uvSeries)
    },
    true
  )
}

// 刷新全部
const refreshAll = () => {
  loadStatistics()
  loadTrend()
  listParam.value.current = 1
  loadList()
}

// resize 处理
const handleResize = () => {
  pvChart && pvChart.resize()
  uvChart && uvChart.resize()
}

onMounted(async () => {
  await nextTick()
  refreshAll()
  window.addEventListener('resize', handleResize)
})

onUnmounted(() => {
  window.removeEventListener('resize', handleResize)
  if (pvChart && !pvChart.isDisposed()) pvChart.dispose()
  pvChart = null
  if (uvChart && !uvChart.isDisposed()) uvChart.dispose()
  uvChart = null
})
</script>

<style scoped lang="scss">
.visit-container {
  margin: 20px;
  .head {
    margin-bottom: 16px;
    display: flex;
    align-items: center;
    gap: 10px;
    .filter-label {
      font-size: 14px;
      color: #606266;
      white-space: nowrap;
    }
  }
}

.stat-box {
  display: flex;
  gap: 16px;
  margin-bottom: 16px;
  flex-wrap: wrap;
  .stat-card {
    flex: 1;
    min-width: 220px;
    background: #fff;
    border-radius: 12px;
    padding: 18px 20px;
    display: flex;
    align-items: center;
    gap: 14px;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.04);
    border: 1px solid #f0f0f0;
    .stat-icon {
      width: 48px;
      height: 48px;
      border-radius: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      color: #fff;
      flex-shrink: 0;
    }
    .stat-info {
      flex: 1;
      .stat-title {
        font-size: 13px;
        color: #909399;
        margin-bottom: 6px;
      }
      .stat-value {
        font-size: 28px;
        font-weight: 600;
        color: #303133;
      }
    }
  }
  .stat-pv .stat-icon {
    background: linear-gradient(135deg, #7f69ff 0%, #b8a9ff 100%);
  }
  .stat-uv .stat-icon {
    background: linear-gradient(135deg, #ff6b81 0%, #ffb3bd 100%);
  }
  .stat-vv .stat-icon {
    background: linear-gradient(135deg, #36d1dc 0%, #5bdeea 100%);
  }
  .stat-ip .stat-icon {
    background: linear-gradient(135deg, #f6a609 0%, #ffd66e 100%);
  }
}

.chart-row {
  display: flex;
  gap: 16px;
  margin-bottom: 16px;
  .chart-card {
    flex: 1;
    background: #fff;
    border-radius: 12px;
    border: 1px solid #f0f0f0;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.04);
    .chart-header {
      padding: 14px 18px;
      font-size: 15px;
      font-weight: 500;
      color: #303133;
    }
    .chart-canvas {
      width: 100%;
      height: 300px;
    }
  }
}

.list-section {
  background: #fff;
  border-radius: 12px;
  border: 1px solid #f0f0f0;
  padding: 16px;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.04);
  .list-header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 12px;
    font-size: 15px;
    font-weight: 500;
    color: #303133;
    .list-search {
      width: 260px;
      margin-left: auto;
    }
  }
}
</style>
