// apps/web/src/components/form/Radio.tsx
'use client'

import { cn } from '@/lib/utils'

export interface RadioOption {
  label: string
  value: string | number
  disabled?: boolean
}

interface RadioProps {
  options: RadioOption[]
  value?: string | number
  onChange?: (value: string | number) => void
  inline?: boolean
  name?: string
  className?: string
}

export function Radio({ options, value, onChange, inline = false, className }: RadioProps) {
  return (
    <div className={cn(inline ? 'flex flex-wrap gap-4' : 'flex flex-col gap-2', className)}>
      {options.map((opt) => {
        const isChecked = value === opt.value
        return (
          <label
            key={opt.value}
            className={cn('inline-flex cursor-pointer items-center gap-2', opt.disabled && 'cursor-not-allowed opacity-50')}
          >
            <span
              onClick={() => !opt.disabled && onChange?.(opt.value)}
              className={cn(
                'flex h-4 w-4 items-center justify-center rounded-full border border-input transition-colors',
                isChecked && 'border-primary',
                'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
              )}
            >
              {isChecked && <span className="h-2 w-2 rounded-full bg-primary" />}
            </span>
            <span className="text-sm">{opt.label}</span>
          </label>
        )
      })}
    </div>
  )
}

// client/src/components/ui/radio/Radio.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { computed } from 'vue'
import { cn } from '@/lib/utils'

const props = withDefaults(
  defineProps<{
    modelValue?: any
    value?: any
    disabled?: boolean
    label?: string
    name?: string
    class?: HTMLAttributes['class']
  }>(),
  {
    disabled: false,
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: any]
  change: [value: any]
}>()

const isChecked = computed(() => props.modelValue === props.value)

const handleChange = () => {
  if (props.disabled) return
  emit('update:modelValue', props.value)
  emit('change', props.value)
}
</script>

<template>
  <label
    :class="
      cn(
        'inline-flex cursor-pointer items-center gap-2',
        disabled && 'cursor-not-allowed opacity-50',
        props.class,
      )
    "
  >
    <span
      :class="
        cn(
          'flex h-4 w-4 items-center justify-center rounded-full border-2 transition-colors',
          isChecked ? 'border-primary' : 'border-input',
        )
      "
      @click="handleChange"
    >
      <span
        v-if="isChecked"
        class="h-2 w-2 rounded-full bg-primary"
      />
    </span>
    <input
      type="radio"
      class="sr-only"
      :name="name"
      :value="value"
      :checked="isChecked"
      :disabled="disabled"
      @change="handleChange"
    />
    <span v-if="label || $slots.default" class="text-sm">
      <slot>{{ label }}</slot>
    </span>
  </label>
</template>
