// client/miniapp/src/pages/table/tools/components/RecentAgents.vue
<template>
  <view class="recent-agents-container">
    <view class="recent-header">
      <text class="recent-title">最近使用</text>
    </view>
    <scroll-view class="recent-scroll" scroll-x="true" show-scrollbar="false">
      <view class="recent-list">
        <view 
          class="recent-item" 
          v-for="(agent, index) in recentAgents" 
          :key="index"
          @click="navigateTo(agent, index)"
          style="border-radius: 25rpx"
        >
          <image 
            class="agent-avatar" 
            :src="agent.agentAvatar || defaultAvatar" 
            mode="aspectFill"
          ></image>
          <text class="agent-name">{{ agent.agentName }}</text>
        </view>
      </view>
    </scroll-view>
  </view>
</template>

<script setup>
import { ref } from 'vue'

const props = defineProps({
  recentAgents: {
    type: Array,
    default: () => []
  }
})

const emit = defineEmits(['agent-click'])

const defaultAvatar = ref('/static/images/agent-avatar.png')

const onAgentClick = (agent) => {
  emit('agent-click', agent)
}

const navigateTo = (item, idx) => {
  const userInfodata = uni.getStorageSync("data");
  if (!userInfodata) {
    uni.showToast({
      title: '请先登录',
      icon: 'none'
    });
    return;
  }
  if(item.type == 3 || item.type == 5){
    return;
  }

  let targetUrl = '/pages/tools/ai_assistant';
  if (item.source === 'n8n') {
    targetUrl = '/pages/tools/ai_assistant_n8n';
  }

  uni.navigateTo({
    url: targetUrl + '?' + '&modelNamea=' + item.agentName + '&pitcha=' + idx + '&agentId=' + item.agentId + '&type=' + item.type
  });
}
</script>

<style lang="scss" scoped>
.recent-agents-container {
  padding: 0;
  background: #fff;
}

.recent-header {
  padding: 0 20rpx 20rpx;
}

.recent-title {
  font-size: 32rpx;
  font-weight: bold;
  color: #333;
  font-family: AlimamaFangYuanTi !important;
}

.recent-scroll {
  width: 100%;
  white-space: nowrap;
}

.recent-list {
  display: flex;
  flex-direction: row;
  padding: 0 10rpx;
}

.recent-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 0 10rpx;
  min-width: 120rpx;
  padding: 20rpx 10rpx;
  border-radius: 16rpx;
  background: #f8f9fa;
  transition: all 0.3s ease;
  
  &:active {
    transform: scale(0.95);
    background: #e9ecef;
  }
}

.agent-avatar {
  width: 80rpx;
  height: 80rpx;
  border-radius: 10rpx;
  margin-bottom: 12rpx;
  background: #ddd;
}

.agent-name {
  font-size: 24rpx;
  color: #666;
  text-align: center;
  max-width: 100rpx;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-family: AlimamaFangYuanTi !important;
}
</style>

// apps/miniapp-taro/src/pages/community/components/RecentAgents.tsx
/**
 * RecentAgents — 最近使用的智能体横向滚动列表
 * 对齐原项目 zhs_app-ZZ Ai-WXMiniVue tools/components/RecentAgents.vue
 */
import { View, Text, ScrollView, Image } from '@tarojs/components'
import Taro from '@tarojs/taro'

export interface RecentAgent {
  id: string
  agentName: string
  agentAvatar: string
  /** 可选:智能体类型 3/5 为付费模型,点击时跳过跳转 */
  type?: number
  /** 可选:来源标识,如 'n8n' 跳转专用页面 */
  source?: string
  agentId?: string
}

export interface RecentAgentsProps {
  recentAgents: RecentAgent[]
}

export default function RecentAgents({ recentAgents }: RecentAgentsProps) {
  if (!recentAgents || recentAgents.length === 0) return null

  function navigateTo(agent: RecentAgent, idx: number) {
    const userData = Taro.getStorageSync('data') as Record<string, unknown> | null
    if (!userData) {
      Taro.showToast({ title: '请先登录', icon: 'none' })
      return
    }
    if (agent.type === 3 || agent.type === 5) {
      return
    }
    const targetUrl = agent.source === 'n8n'
      ? '/pages/tools/ai_assistant_n8n'
      : '/pages/tools/ai_assistant'
    const agentId = agent.agentId || agent.id
    Taro.navigateTo({
      url: `${targetUrl}?modelNamea=${encodeURIComponent(agent.agentName)}&pitcha=${idx}&agentId=${encodeURIComponent(agentId)}&type=${agent.type ?? ''}`,
    })
  }

  return (
    <View className="recent-agents-container">
      <View className="recent-header">
        <Text className="recent-title">最近使用</Text>
      </View>
      <ScrollView scrollX className="recent-scroll" showScrollbar={false}>
        <View className="recent-list">
          {recentAgents.map((agent, index) => (
            <View
              key={agent.id || index}
              className="recent-item"
              onClick={() => navigateTo(agent, index)}
              style={{ borderRadius: '25rpx' }}
            >
              {agent.agentAvatar ? (
                <Image
                  className="agent-avatar"
                  src={agent.agentAvatar}
                  mode="aspectFill"
                />
              ) : (
                <View className="agent-avatar agent-avatar-fallback">
                  <Text className="agent-avatar-fallback-text">
                    {(agent.agentName || '?').charAt(0)}
                  </Text>
                </View>
              )}
              <Text className="agent-name">{agent.agentName}</Text>
            </View>
          ))}
        </View>
      </ScrollView>
    </View>
  )
}
