// apps/miniapp-taro/src/pages/live/detail.tsx
import { View, Text, Image, Video } from '@tarojs/components'
import Taro, { useRouter } from '@tarojs/taro'
import { useState, useEffect, useCallback } from 'react'
import { getLiveDetail, type Live } from '@/api'
import { useI18n } from '@/i18n'

export default function LiveDetail() {
  const { t } = useI18n()
  const router = useRouter()
  const [live, setLive] = useState<Live | null>(null)

  const loadDetail = useCallback(
    async (id: string | number) => {
      try {
        const res = await getLiveDetail(id)
        setLive(res)
      } catch {
        Taro.showToast({ title: t('live.detail.loadFailed'), icon: 'none' })
      }
    },
    [t],
  )

  useEffect(() => {
    const id = router.params.id || ''
    if (id) loadDetail(id)
  }, [router.params.id, loadDetail])

  const enterLive = useCallback(() => {
    Taro.showToast({ title: t('live.detail.connecting'), icon: 'loading' })
  }, [t])

  if (!live) {
    return (
      <View className="flex items-center justify-center h-screen text-[#999]">
        <Text>{t('live.detail.loading')}</Text>
      </View>
    )
  }

  return (
    <View className="min-h-screen">
      {/* 播放区 */}
      <View className="w-full h-[210px] bg-black">
        {live.playUrl ? (
          <Video
            className="w-full h-full"
            src={live.playUrl}
            autoplay
            controls
            objectFit="contain"
          />
        ) : (
          <View className="relative w-full h-full">
            <Image className="w-full h-full opacity-60" src={live.coverUrl} mode="aspectFill" />
            {live.status === 'living' && (
              <View className="absolute inset-0 flex items-center justify-center">
                <View
                  className="px-7 py-2.5 bg-[#dd524d] text-white rounded-md text-sm"
                  onClick={enterLive}
                >
                  <Text>{t('live.detail.enter')}</Text>
                </View>
              </View>
            )}
            {live.status === 'ended' && (
              <View className="absolute inset-0 flex flex-col items-center justify-center text-white text-sm">
                <Text>{t('live.detail.ended')}</Text>
              </View>
            )}
            {live.status === 'upcoming' && (
              <View className="absolute inset-0 flex flex-col items-center justify-center text-white text-sm">
                <Text>{t('live.detail.notStarted')}</Text>
                {live.startTime && (
                  <Text className="mt-2 text-xs opacity-80">{live.startTime}</Text>
                )}
              </View>
            )}
          </View>
        )}
      </View>

      {/* 直播信息 */}
      <View className="p-3">
        <Text className="text-lg text-[#333] font-semibold">{live.title}</Text>
        <View className="flex justify-between mt-2">
          {live.anchor && (
            <Text className="text-sm text-[#07c160]">
              {t('live.detail.anchor', { name: live.anchor })}
            </Text>
          )}
          {live.watchCount !== undefined && (
            <Text className="text-sm text-[#999]">{t('live.viewers', { n: live.watchCount })}</Text>
          )}
        </View>
      </View>
    </View>
  )
}

// apps/miniapp/pages/live/detail.vue
<template>
  <view class="page" v-if="live">
    <!-- 播放区 -->
    <view class="player">
      <video
        v-if="live.playUrl"
        class="video"
        :src="live.playUrl"
        :autoplay="true"
        :controls="true"
        object-fit="contain"
      />
      <view v-else class="player-cover">
        <image class="cover" :src="live.coverUrl" mode="aspectFill" />
        <view class="living-mask" v-if="live.status === 'living'">
          <view class="living-btn" @tap="enterLive"><text>进入直播</text></view>
        </view>
        <view class="ended-tip" v-else-if="live.status === 'ended'">
          <text>直播已结束</text>
        </view>
        <view class="upcoming-tip" v-else>
          <text>直播未开始</text>
          <text class="time" v-if="live.startTime">{{ live.startTime }}</text>
        </view>
      </view>
    </view>

    <!-- 直播信息 -->
    <view class="info">
      <text class="title">{{ live.title }}</text>
      <view class="meta">
        <text class="anchor" v-if="live.anchor">主播：{{ live.anchor }}</text>
        <text class="watch" v-if="live.watchCount !== undefined">{{ live.watchCount }}人观看</text>
      </view>
    </view>
  </view>

  <view class="loading-page" v-else><text>加载中...</text></view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { getLiveDetail, type Live } from '@/api'

const live = ref<Live | null>(null)
const liveId = ref<string | number>('')

onLoad((options) => {
  liveId.value = options?.id || ''
  loadDetail()
})

async function loadDetail() {
  try {
    live.value = await getLiveDetail(liveId.value)
  } catch (e) {
    uni.showToast({ title: '加载失败', icon: 'none' })
  }
}

function enterLive() {
  uni.showToast({ title: '正在连接直播间...', icon: 'loading' })
}
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; }

.player { width: 100%; height: 420rpx; background: #000; }
.video { width: 100%; height: 100%; }
.player-cover { position: relative; width: 100%; height: 100%; }
.cover { width: 100%; height: 100%; opacity: 0.6; }

.living-mask { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; }
.living-btn { padding: 20rpx 56rpx; background: #dd524d; color: #fff; border-radius: 40rpx; font-size: 30rpx; }

.ended-tip, .upcoming-tip { position: absolute; inset: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; color: #fff; font-size: 30rpx; }
.upcoming-tip .time { margin-top: 16rpx; font-size: 26rpx; opacity: 0.8; }

.info { padding: 24rpx 32rpx; }
.title { font-size: 34rpx; color: #333; font-weight: 600; }
.meta { display: flex; justify-content: space-between; margin-top: 16rpx; }
.anchor { font-size: 26rpx; color: #007aff; }
.watch { font-size: 26rpx; color: #999; }

.loading-page { display: flex; align-items: center; justify-content: center; height: 100vh; color: #999; }
</style>
