// apps/miniapp/pages/about/index.vue
<template>
  <view class="page">
    <view class="logo-box" v-if="info.name">
      <image class="logo" :src="info.logo || '/static/logo.png'" mode="aspectFit" />
      <text class="name">{{ info.name }}</text>
      <text class="version">V{{ info.version }}</text>
    </view>
    <view class="card">
      <text class="intro">{{ info.intro }}</text>
    </view>
    <view class="menu">
      <view class="menu-item" @tap="navigate('/pages/about/help')"><text>帮助中心</text><text class="arrow">›</text></view>
      <view class="menu-item" @tap="navigate('/pages/about/protocol')"><text>用户协议</text><text class="arrow">›</text></view>
      <view class="menu-item" @tap="navigate('/pages/about/privacy')"><text>隐私政策</text><text class="arrow">›</text></view>
      <view class="menu-item" @tap="navigate('/pages/about/contact')"><text>联系我们</text><text class="arrow">›</text></view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getAbout } from '@/api'

const info = ref<{ name: string; version: string; intro: string; logo?: string }>({ name: '', version: '', intro: '' })

async function load() {
  try { info.value = await getAbout() } catch (e) {}
}
function navigate(url: string) { uni.navigateTo({ url }) }
onShow(load)
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.logo-box { padding: 80rpx 0; text-align: center; background: #fff; }
.logo { width: 160rpx; height: 160rpx; }
.name { display: block; font-size: 32rpx; color: #333; font-weight: 600; margin-top: 24rpx; }
.version { display: block; font-size: 24rpx; color: #999; margin-top: 8rpx; }
.card { margin: 24rpx; padding: 32rpx; background: #fff; border-radius: 16rpx; }
.intro { font-size: 26rpx; color: #666; line-height: 1.8; }
.menu { margin: 24rpx; background: #fff; border-radius: 16rpx; overflow: hidden; }
.menu-item { display: flex; justify-content: space-between; align-items: center; padding: 32rpx; border-bottom: 2rpx solid #f5f5f5; font-size: 28rpx; color: #333; }
.arrow { color: #ccc; }
</style>

// apps/miniapp-taro/src/pages/about/index.tsx
import { View, Text, Image } from '@tarojs/components'
import Taro, { useDidShow } from '@tarojs/taro'
import { useState, useCallback } from 'react'
import { getAbout } from '@/api'
import './index.css'

interface AboutInfo {
  name: string
  version: string
  intro: string
  logo?: string
}

export default function AboutIndexPage() {
  const [info, setInfo] = useState<AboutInfo>({ name: '', version: '', intro: '' })

  const load = useCallback(async () => {
    try { setInfo(await getAbout()) } catch {}
  }, [])

  const navigate = useCallback((url: string) => {
    Taro.navigateTo({ url })
  }, [])

  useDidShow(() => load())

  return (
    <View className="page">
      {info.name ? (
        <View className="logo-box">
          <Image className="logo" src={info.logo || '/static/logo.png'} mode="aspectFit" />
          <Text className="name">{info.name}</Text>
          <Text className="version">V{info.version}</Text>
        </View>
      ) : null}

      <View className="card">
        <Text className="intro">{info.intro}</Text>
      </View>

      <View className="menu">
        <View className="menu-item" onClick={() => navigate('/pages/about/help')}>
          <Text>帮助中心</Text><Text className="arrow">›</Text>
        </View>
        <View className="menu-item" onClick={() => navigate('/pages/about/protocol')}>
          <Text>用户协议</Text><Text className="arrow">›</Text>
        </View>
        <View className="menu-item" onClick={() => navigate('/pages/about/privacy')}>
          <Text>隐私政策</Text><Text className="arrow">›</Text>
        </View>
        <View className="menu-item" onClick={() => navigate('/pages/about/contact')}>
          <Text>联系我们</Text><Text className="arrow">›</Text>
        </View>
      </View>
    </View>
  )
}
