// apps/miniapp/pages/user/orders.vue
<template>
  <view class="page">
    <!-- 状态筛选 -->
    <view class="tabs">
      <view class="tab" :class="{ active: status === '' }" @tap="switchStatus('')"><text>全部</text></view>
      <view class="tab" :class="{ active: status === 'pending' }" @tap="switchStatus('pending')"><text>待付款</text></view>
      <view class="tab" :class="{ active: status === 'paid' }" @tap="switchStatus('paid')"><text>已付款</text></view>
      <view class="tab" :class="{ active: status === 'cancelled' }" @tap="switchStatus('cancelled')"><text>已取消</text></view>
    </view>

    <!-- 订单列表 -->
    <view class="list" v-if="list.length">
      <view class="card" v-for="item in list" :key="item.id">
        <view class="card-head">
          <text class="order-no">订单号：{{ item.orderNo }}</text>
          <text class="status" :class="item.status">{{ statusText(item.status) }}</text>
        </view>
        <view class="card-body">
          <text class="title">{{ item.title }}</text>
          <text class="type">{{ item.type }}</text>
        </view>
        <view class="card-foot">
          <text class="time">{{ item.createTime }}</text>
          <view class="amount-wrap">
            <text class="amount-symbol">¥</text>
            <text class="amount">{{ item.amount }}</text>
          </view>
          <view class="action-btn" v-if="item.status === 'pending'" @tap="handlePay(item)">
            <text>去支付</text>
          </view>
        </view>
      </view>
    </view>

    <view class="empty" v-if="!loading && !list.length"><text>暂无订单</text></view>
    <view class="loading" v-if="loading"><text>加载中...</text></view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onReachBottom, onPullDownRefresh } from '@dcloudio/uni-app'
import { getOrderList, type Order } from '@/api'

const list = ref<Order[]>([])
const loading = ref(false)
const status = ref('')
const page = ref(1)
const pageSize = 10
const hasMore = ref(true)

function statusText(s: Order['status']) {
  const map: Record<Order['status'], string> = {
    pending: '待付款',
    paid: '已付款',
    cancelled: '已取消',
    refunded: '已退款',
  }
  return map[s] || s
}

function switchStatus(s: string) {
  status.value = s
  load(true)
}

async function load(reset = false) {
  if (loading.value) return
  if (reset) {
    page.value = 1
    hasMore.value = true
    list.value = []
  }
  if (!hasMore.value) return
  loading.value = true
  try {
    const res = await getOrderList({ page: page.value, pageSize, status: status.value })
    list.value.push(...(res.list || []))
    hasMore.value = list.value.length < res.total
    page.value++
  } catch (e) {
    // 统一提示
  } finally {
    loading.value = false
  }
}

function handlePay(item: Order) {
  uni.showToast({ title: `支付订单 ${item.orderNo}`, icon: 'none' })
}

onPullDownRefresh(() => load(true).finally(() => uni.stopPullDownRefresh()))
onReachBottom(() => load())
load()
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; padding: 24rpx 32rpx; }

.tabs { display: flex; margin-bottom: 24rpx; background: #fff; border-radius: 12rpx; }
.tab { flex: 1; text-align: center; padding: 20rpx 0; font-size: 26rpx; color: #666; }
.tab.active { color: #007aff; font-weight: 600; }

.card { background: #fff; border-radius: 16rpx; padding: 24rpx; margin-bottom: 24rpx; }
.card-head { display: flex; justify-content: space-between; align-items: center; }
.order-no { font-size: 24rpx; color: #999; }
.status { font-size: 26rpx; }
.status.paid { color: #4cd964; }
.status.pending { color: #f0ad4e; }
.status.cancelled { color: #999; }
.status.refunded { color: #dd524d; }

.card-body { display: flex; flex-direction: column; margin: 20rpx 0; }
.title { font-size: 30rpx; color: #333; font-weight: 600; }
.type { margin-top: 8rpx; font-size: 24rpx; color: #999; }

.card-foot { display: flex; align-items: center; padding-top: 20rpx; border-top: 1rpx solid #f5f5f5; }
.time { flex: 1; font-size: 24rpx; color: #999; }
.amount-wrap { margin-right: 24rpx; }
.amount-symbol { font-size: 24rpx; color: #dd524d; }
.amount { font-size: 34rpx; color: #dd524d; font-weight: 700; }
.action-btn { padding: 10rpx 32rpx; background: #007aff; color: #fff; border-radius: 30rpx; font-size: 26rpx; }

.empty, .loading { text-align: center; padding: 120rpx 0; color: #999; font-size: 26rpx; }
</style>

// apps/miniapp-taro/src/pkg-user/user/orders.tsx
// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

import { useI18n } from '@/i18n'
import { View, Text } from '@tarojs/components'
import Taro, { usePullDownRefresh, useReachBottom } from '@tarojs/taro'
import { useState, useEffect, useCallback, useRef } from 'react'
import { getOrderList, type Order } from '@/api'
import ThemeRoot from '@/components/ThemeRoot'

const STATUS_COLOR: Record<string, string> = {
  pending: 'bg-[var(--color-warning-amber-light)] text-[var(--color-warning-amber-text)]',
  paid: 'bg-[var(--color-success-light)] text-[var(--color-success-deep-text)]',
  refunding: 'bg-[var(--color-warning-amber-light)] text-[var(--color-warning-amber-text)]',
  refunded: 'bg-[var(--color-muted)] text-[var(--color-text-tertiary)]',
  cancelled: 'bg-[var(--color-danger-light)] text-[var(--color-danger)]',
  completed: 'bg-[var(--color-success-light)] text-[var(--color-success-deep-text)]',
  failed: 'bg-[var(--color-muted)] text-[var(--color-text-tertiary)]',
}

const STATUS_KEY: Record<string, string> = {
  pending: 'order.status.pending',
  paid: 'order.status.paid',
  cancelled: 'order.status.cancelled',
  refunding: 'order.status.refunding',
  refunded: 'order.status.refunded',
  completed: 'order.status.completed',
  failed: 'order.status.failed',
}

export default function Orders() {
  const { t } = useI18n()
  const [list, setList] = useState<Order[]>([])
  const [loading, setLoading] = useState(false)
  const [status, setStatus] = useState('')
  const [page, setPage] = useState(1)
  const [hasMore, setHasMore] = useState(true)
  const pageSize = 10

  const statusText = (s: string) => (STATUS_KEY[s] ? t(STATUS_KEY[s]) : s)

  const load = useCallback(
    async (reset = false) => {
      if (loading) return
      let curPage = page
      let curList = list
      if (reset) {
        curPage = 1
        curList = []
        setList([])
        setHasMore(true)
      }
      if (!hasMore && !reset) return
      setLoading(true)
      try {
        const res = await getOrderList({ page: curPage, pageSize, status })
        const newList = [...curList, ...(res.list || [])]
        setList(newList)
        setHasMore(newList.length < res.total)
        setPage(curPage + 1)
      } catch {
        // 统一提示
      } finally {
        setLoading(false)
      }
    },
    [loading, page, hasMore, status, list, pageSize],
  )

  function switchStatus(s: string) {
    setStatus(s)
    setTimeout(() => load(true), 0)
  }

  function handlePay(item: Order) {
    Taro.navigateTo({ url: `/pkg-shop/pay/index?orderNo=${item.orderNo}&amount=${item.amount}` })
  }

  function goDetail(item: Order) {
    Taro.navigateTo({ url: `/pkg-shop/order/detail?id=${item.id}` })
  }

  const mountedRef = useRef(false)
  useEffect(() => {
    if (mountedRef.current) return
    mountedRef.current = true
    load(true)
  }, [load])

  usePullDownRefresh(() => {
    load(true).finally(() => Taro.stopPullDownRefresh())
  })

  useReachBottom(() => {
    load()
  })

  const tabs = [
    { key: '', label: t('user.orders.tabsAll') },
    { key: 'pending', label: t('user.orders.tabsPending') },
    { key: 'paid', label: t('user.orders.tabsPaid') },
    { key: 'cancelled', label: t('user.orders.tabsCancelled') },
    { key: 'refunded', label: t('order.status.refunded') },
  ]

  return (
    <ThemeRoot>
      {/* 对齐 RN 共享 OrderScreen:tab 药丸(白底/激活品牌底白字 28rpx 圆角 24rpx)+
          订单卡(描边 border.light + 圆角 24rpx + 内边距 24rpx):标题 32rpx/600 + 状态徽章
          (浅底深字 22rpx)+ 单号/时间 22rpx 三级字色 + 金额 36rpx/700 主字色 */}
      <View className="min-h-screen bg-background pb-[20rpx]">
        {/* 状态筛选 */}
        <View className="flex flex-wrap gap-[16rpx] px-[20rpx] py-[16rpx]">
          {tabs.map((tab) => (
            <View
              key={tab.key}
              className={`px-[28rpx] py-[12rpx] rounded-[24rpx] text-[28rpx] ${
                status === tab.key
                  ? 'bg-primary font-semibold text-[var(--color-surface-light)]'
                  : 'bg-card text-muted-foreground'
              }`}
              hoverClass="opacity-60"
              onClick={() => switchStatus(tab.key)}
            >
              <Text>{tab.label}</Text>
            </View>
          ))}
        </View>

        {/* 订单列表 */}
        {list.length > 0 ? (
          <View className="px-[20rpx]">
            {list.map((item) => (
              <View
                key={item.id}
                className="mb-[24rpx] rounded-[24rpx] border border-[var(--color-border)] bg-card p-[24rpx]"
                hoverClass="opacity-60"
                onClick={() => goDetail(item)}
              >
                <View className="flex items-center justify-between gap-[16rpx]">
                  <Text className="flex-1 truncate text-[32rpx] font-semibold text-foreground">
                    {item.title}
                  </Text>
                  <View
                    className={`shrink-0 rounded-[8rpx] px-[12rpx] py-[4rpx] ${
                      STATUS_COLOR[item.status] ||
                      'bg-[var(--color-muted)] text-[var(--color-text-tertiary)]'
                    }`}
                  >
                    <Text className="text-[22rpx]">{statusText(item.status)}</Text>
                  </View>
                </View>
                <View className="mt-[16rpx] flex items-center justify-between">
                  <Text className="text-[22rpx] text-[var(--color-text-tertiary)]">
                    {t('user.orders.orderNo')}
                    {item.orderNo}
                  </Text>
                  <Text className="text-[22rpx] text-[var(--color-text-tertiary)]">
                    {item.createTime}
                  </Text>
                </View>
                <View className="mt-[16rpx] flex items-end justify-between">
                  <Text className="text-[22rpx] text-[var(--color-text-tertiary)]">
                    {item.type}
                  </Text>
                  <View className="flex items-center gap-[24rpx]">
                    <Text className="text-[36rpx] font-bold text-foreground">¥{item.amount}</Text>
                    {item.status === 'pending' ? (
                      <View
                        className="rounded-[24rpx] bg-primary px-[24rpx] py-[12rpx] text-[28rpx] text-[var(--color-surface-light)]"
                        hoverClass="opacity-60"
                        onClick={(e) => {
                          e.stopPropagation()
                          handlePay(item)
                        }}
                      >
                        <Text>{t('user.orders.pay')}</Text>
                      </View>
                    ) : null}
                  </View>
                </View>
              </View>
            ))}
          </View>
        ) : null}

        {!loading && list.length === 0 ? (
          <View className="py-[96rpx] text-center text-[28rpx] text-muted-foreground">
            <Text>{t('user.orders.empty')}</Text>
          </View>
        ) : null}
        {loading ? (
          <View className="py-[96rpx] text-center text-[28rpx] text-muted-foreground">
            <Text>{t('common.loading')}</Text>
          </View>
        ) : null}
      </View>
    </ThemeRoot>
  )
}
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
