// apps/miniapp-taro/src/pages/member/integral.tsx
import { View, Text } from '@tarojs/components'
import { useState, useCallback, useEffect } from 'react'
import { useReachBottom } from '@tarojs/taro'
import { getIntegral } from '@/api'
import './integral.css'

interface IntegralItem {
  id: string
  type: string
  amount: number
  time: string
}

export default function IntegralPage() {
  const [list, setList] = useState<IntegralItem[]>([])
  const [loading, setLoading] = useState(false)
  const [type, setType] = useState<'all' | 'in' | 'out'>('all')
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [hasMore, setHasMore] = useState(true)

  const load = useCallback(async (reset = false) => {
    if (loading) return
    let curPage = page
    if (reset) { curPage = 1; setHasMore(true); setList([]); setPage(1) }
    if (!hasMore && !reset) return
    setLoading(true)
    try {
      const res = await getIntegral({ page: curPage, pageSize: 20 })
      setList(prev => reset ? (res.list || []) : [...prev, ...(res.list || [])])
      setTotal(res.total)
      setHasMore((reset ? (res.list || []).length : list.length + (res.list || []).length) < res.total)
      setPage(curPage + 1)
    } finally { setLoading(false) }
  }, [loading, page, hasMore, list.length])

  const switchType = useCallback((t: 'all' | 'in' | 'out') => {
    setType(t)
    load(true)
  }, [load])

  useReachBottom(() => load())
  useEffect(() => { load(true) }, [])

  return (
    <View className="page">
      <View className="summary">
        <Text className="sum-num">{total}</Text>
        <Text className="sum-label">当前积分</Text>
      </View>
      <View className="tabs">
        <Text className={`tab${type === 'all' ? ' active' : ''}`} onClick={() => switchType('all')}>全部</Text>
        <Text className={`tab${type === 'in' ? ' active' : ''}`} onClick={() => switchType('in')}>收入</Text>
        <Text className={`tab${type === 'out' ? ' active' : ''}`} onClick={() => switchType('out')}>支出</Text>
      </View>
      {list.length ? (
        <View className="list">
          {list.map(it => (
            <View key={it.id} className="item">
              <View className="item-body">
                <Text className="item-title">{it.type}</Text>
                <Text className="item-time">{it.time}</Text>
              </View>
              <Text className={`item-amt${it.amount > 0 ? ' in' : ''}`}>{it.amount > 0 ? '+' : ''}{it.amount}</Text>
            </View>
          ))}
        </View>
      ) : null}
      {!loading && !list.length ? (
        <View className="empty"><Text>暂无记录</Text></View>
      ) : null}
    </View>
  )
}

// apps/miniapp/pages/member/integral.vue
<template>
  <view class="page">
    <view class="summary">
      <text class="sum-num">{{ total }}</text>
      <text class="sum-label">当前积分</text>
    </view>
    <view class="tabs">
      <text class="tab" :class="{ active: type === 'all' }" @tap="type = 'all'; load(true)">全部</text>
      <text class="tab" :class="{ active: type === 'in' }" @tap="type = 'in'; load(true)">收入</text>
      <text class="tab" :class="{ active: type === 'out' }" @tap="type = 'out'; load(true)">支出</text>
    </view>
    <view class="list" v-if="list.length">
      <view class="item" v-for="it in list" :key="it.id">
        <view class="item-body">
          <text class="item-title">{{ it.type }}</text>
          <text class="item-time">{{ it.time }}</text>
        </view>
        <text class="item-amt" :class="{ in: it.amount > 0 }">{{ it.amount > 0 ? '+' : '' }}{{ it.amount }}</text>
      </view>
    </view>
    <view class="empty" v-else-if="!loading"><text>暂无记录</text></view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onReachBottom } from '@dcloudio/uni-app'
import { getIntegral } from '@/api'

const list = ref<Array<{ id: string; type: string; amount: number; time: string }>>([])
const loading = ref(false)
const type = ref<'all' | 'in' | 'out'>('all')
const total = ref(0)
const page = ref(1)
const hasMore = ref(true)

async function load(reset = false) {
  if (loading.value) return
  if (reset) { page.value = 1; hasMore.value = true; list.value = [] }
  if (!hasMore.value) return
  loading.value = true
  try {
    const res = await getIntegral({ page: page.value, pageSize: 20 })
    list.value.push(...(res.list || []))
    hasMore.value = list.value.length < res.total
    page.value++
  } finally { loading.value = false }
}
onReachBottom(() => load())
load()
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.summary { padding: 60rpx 0; text-align: center; background: linear-gradient(135deg, #007aff, #00c6ff); color: #fff; }
.sum-num { display: block; font-size: 60rpx; font-weight: 700; }
.sum-label { display: block; font-size: 24rpx; opacity: .9; margin-top: 8rpx; }
.tabs { display: flex; padding: 24rpx; background: #fff; }
.tab { flex: 1; text-align: center; font-size: 26rpx; color: #666; padding: 12rpx 0; }
.tab.active { color: #007aff; font-weight: 600; }
.list { padding: 0 24rpx; }
.item { display: flex; justify-content: space-between; align-items: center; background: #fff; padding: 32rpx; margin-top: 24rpx; border-radius: 16rpx; }
.item-title { display: block; font-size: 28rpx; color: #333; }
.item-time { display: block; font-size: 22rpx; color: #999; margin-top: 8rpx; }
.item-amt { font-size: 32rpx; color: #dd524d; font-weight: 600; }
.item-amt.in { color: #4caf50; }
.empty { text-align: center; padding: 120rpx 0; color: #999; }
</style>
