// apps/miniapp-taro/src/pages/study/plan.tsx
import { View, Text, Button } from '@tarojs/components'
import Taro, { useDidShow } from '@tarojs/taro'
import { useState, useCallback } from 'react'
import { getStudyPlan } from '@/api'

interface PlanItem {
  id: string
  title: string
  target: number
  progress: number
}

export default function StudyPlan() {
  const [list, setList] = useState<PlanItem[]>([])
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    try {
      const res = await getStudyPlan()
      setList(res.list || [])
    } catch (e) {
      // 统一提示
    } finally {
      setLoading(false)
    }
  }, [])

  const onAdd = useCallback(() => {
    Taro.showToast({ title: '功能开发中', icon: 'none' })
  }, [])

  useDidShow(() => {
    load()
  })

  return (
    <View className="min-h-screen bg-[#f7f8fa] pb-[60px]">
      {list.length > 0 && (
        <View className="p-3">
          {list.map(p => (
            <View key={p.id} className="bg-white rounded-2xl p-3 mb-3">
              <View className="flex justify-between items-center">
                <Text className="text-sm text-[#333] font-semibold">{p.title}</Text>
                <Text className="text-xs text-[#999]">目标{p.target}%</Text>
              </View>
              <View className="h-1.5 bg-[#f5f5f5] rounded mt-2">
                <View
                  className="h-full bg-[#007aff] rounded"
                  style={{ width: `${p.progress}%` }}
                />
              </View>
              <View className="flex justify-between mt-1.5">
                <Text className="text-xs text-[#999]">已完成 {p.progress}%</Text>
                <Text className={`text-xs ${p.progress >= p.target ? 'text-[#4caf50]' : 'text-[#ff9a3c]'}`}>
                  {p.progress >= p.target ? '已完成' : '进行中'}
                </Text>
              </View>
            </View>
          ))}
        </View>
      )}
      {!loading && list.length === 0 && (
        <View className="text-center py-16 text-[#999]">
          <Text>暂无学习计划</Text>
        </View>
      )}
      <Button
        className="fixed bottom-4 left-4 right-4 bg-[#007aff] text-white rounded-full text-sm"
        onClick={onAdd}
      >
        + 新建计划
      </Button>
    </View>
  )
}

// apps/miniapp/pages/study/plan.vue
<template>
  <view class="page">
    <view class="list" v-if="list.length">
      <view class="item" v-for="p in list" :key="p.id">
        <view class="item-top">
          <text class="title">{{ p.title }}</text>
          <text class="target">目标{{ p.target }}%</text>
        </view>
        <view class="progress-bar">
          <view class="progress" :style="{ width: p.progress + '%' }"></view>
        </view>
        <view class="item-bottom">
          <text class="progress-text">已完成 {{ p.progress }}%</text>
          <text class="status" :class="{ done: p.progress >= p.target }">{{ p.progress >= p.target ? '已完成' : '进行中' }}</text>
        </view>
      </view>
    </view>
    <view class="empty" v-if="!loading && !list.length"><text>暂无学习计划</text></view>
    <button class="fab" @tap="onAdd">+ 新建计划</button>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getStudyPlan } from '@/api'

const list = ref<Array<{ id: string; title: string; target: number; progress: number }>>([])
const loading = ref(true)

async function load() {
  try { list.value = (await getStudyPlan()).list || [] } finally { loading.value = false }
}
function onAdd() { uni.showToast({ title: '功能开发中', icon: 'none' }) }
onShow(load)
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; padding-bottom: 120rpx; }
.list { padding: 24rpx; }
.item { background: #fff; border-radius: 16rpx; padding: 24rpx; margin-bottom: 24rpx; }
.item-top { display: flex; justify-content: space-between; align-items: center; }
.title { font-size: 28rpx; color: #333; font-weight: 600; }
.target { font-size: 22rpx; color: #999; }
.progress-bar { height: 12rpx; background: #f5f5f5; border-radius: 6rpx; margin-top: 16rpx; }
.progress { height: 100%; background: #007aff; border-radius: 6rpx; }
.item-bottom { display: flex; justify-content: space-between; margin-top: 12rpx; }
.progress-text { font-size: 22rpx; color: #999; }
.status { font-size: 22rpx; color: #ff9a3c; }
.status.done { color: #4caf50; }
.empty { text-align: center; padding: 120rpx 0; color: #999; }
.fab { position: fixed; bottom: 32rpx; left: 32rpx; right: 32rpx; background: #007aff; color: #fff; border-radius: 40rpx; font-size: 30rpx; }
</style>
