// apps/miniapp-taro/src/pages/study/record.tsx
import { View, Text } from '@tarojs/components'
import Taro, { useReachBottom } from '@tarojs/taro'
import { useState, useEffect, useCallback, useRef } from 'react'
import { getStudyRecords, type StudyRecord } from '@/api'
import { useI18n } from '@/i18n'

export default function StudyRecord() {
  const { t } = useI18n()
  const [list, setList] = useState<StudyRecord[]>([])
  const [loading, setLoading] = useState(false)
  const pageRef = useRef(1)
  const hasMoreRef = useRef(true)
  const loadingRef = useRef(false)
  const lenRef = useRef(0)

  const load = useCallback(async (reset = false) => {
    if (loadingRef.current) return
    if (reset) {
      pageRef.current = 1
      hasMoreRef.current = true
      lenRef.current = 0
      setList([])
    }
    if (!reset && !hasMoreRef.current) return
    loadingRef.current = true
    setLoading(true)
    try {
      const res = await getStudyRecords({ page: pageRef.current, pageSize: 20 })
      const more = res.list || []
      lenRef.current = reset ? more.length : lenRef.current + more.length
      setList((prev) => (reset ? more : [...prev, ...more]))
      hasMoreRef.current = lenRef.current < res.total
      pageRef.current++
    } catch {
      Taro.showToast({ title: t('common.failed'), icon: 'none' })
    } finally {
      loadingRef.current = false
      setLoading(false)
    }
  }, [t])

  const goCourse = useCallback((courseId: string) => {
    if (courseId) Taro.navigateTo({ url: `/pages/course/detail?id=${courseId}` })
  }, [])

  useReachBottom(() => load())

  useEffect(() => {
    load(true)
  }, [load])

  return (
    <View className="min-h-screen bg-background">
      {list.length > 0 && (
        <View className="p-3">
          {list.map((r) => (
            <View key={r.id} className="bg-card rounded-2xl p-3 mb-3" onClick={() => goCourse(r.courseId)}>
              <Text className="text-sm text-foreground font-semibold">{r.courseTitle}</Text>
              <View className="flex justify-between mt-1.5">
                <Text className="text-xs text-primary">
                  {t('study.recordPage.duration', { n: r.duration })}
                </Text>
                <Text className="text-xs text-muted-foreground">{r.time}</Text>
              </View>
              <View className="h-1 bg-muted rounded mt-2">
                <View className="h-full bg-primary rounded" style={{ width: `${r.progress}%` }} />
              </View>
              <Text className="block text-xs text-muted-foreground mt-1">
                {t('study.recordPage.progress', { n: r.progress })}
              </Text>
            </View>
          ))}
        </View>
      )}
      {!loading && list.length === 0 && (
        <View className="text-center py-16 text-muted-foreground text-sm">
          <Text>{t('study.recordPage.empty')}</Text>
        </View>
      )}
      {loading && (
        <View className="text-center py-16 text-muted-foreground text-sm">
          <Text>{t('common.loading')}</Text>
        </View>
      )}
    </View>
  )
}

// apps/miniapp/pages/study/record.vue
<template>
  <view class="page">
    <view class="list" v-if="list.length">
      <view class="item" v-for="r in list" :key="r.id">
        <view class="item-body">
          <text class="title">{{ r.courseTitle }}</text>
          <view class="meta">
            <text class="duration">学习 {{ r.duration }}分钟</text>
            <text class="time">{{ r.time }}</text>
          </view>
          <view class="progress-bar">
            <view class="progress" :style="{ width: r.progress + '%' }"></view>
          </view>
          <text class="progress-text">进度 {{ r.progress }}%</text>
        </view>
      </view>
    </view>
    <view class="empty" v-if="!loading && !list.length"><text>暂无学习记录</text></view>
    <view class="loading" v-if="loading"><text>加载中...</text></view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onReachBottom } from '@dcloudio/uni-app'
import { getStudyRecords, type StudyRecord } from '@/api'

const list = ref<StudyRecord[]>([])
const loading = ref(false)
const page = ref(1)
const hasMore = ref(true)

async function load(reset = false) {
  if (loading.value) return
  if (reset) { page.value = 1; hasMore.value = true; list.value = [] }
  if (!hasMore.value) return
  loading.value = true
  try {
    const res = await getStudyRecords({ page: page.value, pageSize: 20 })
    list.value.push(...(res.list || []))
    hasMore.value = list.value.length < res.total
    page.value++
  } finally { loading.value = false }
}
onReachBottom(() => load())
load()
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.list { padding: 24rpx; }
.item { background: #fff; border-radius: 16rpx; padding: 24rpx; margin-bottom: 24rpx; }
.title { font-size: 28rpx; color: #333; font-weight: 600; }
.meta { display: flex; justify-content: space-between; margin-top: 12rpx; }
.duration { font-size: 22rpx; color: #007aff; }
.time { font-size: 22rpx; color: #999; }
.progress-bar { height: 8rpx; background: #f5f5f5; border-radius: 4rpx; margin-top: 16rpx; }
.progress { height: 100%; background: #007aff; border-radius: 4rpx; }
.progress-text { display: block; font-size: 22rpx; color: #999; margin-top: 8rpx; }
.empty, .loading { text-align: center; padding: 120rpx 0; color: #999; }
</style>
