// apps/miniapp-taro/src/pages/teacher/list.tsx
import { useI18n } from '@/i18n'
import { View, Text, Input, Image } from '@tarojs/components'
import Taro, { useReachBottom } from '@tarojs/taro'
import { useState, useEffect, useCallback, useRef } from 'react'
import { getTeacherList, type Teacher } from '@/api'

export default function TeacherList() {
  const { t } = useI18n()
  const [list, setList] = useState<Teacher[]>([])
  const [loading, setLoading] = useState(false)
  const [keyword, setKeyword] = useState('')
  const pageRef = useRef(1)
  const hasMoreRef = useRef(true)
  const loadingRef = useRef(false)
  const lenRef = useRef(0)
  const keywordRef = useRef('')

  const load = useCallback(async (reset = false) => {
    if (loadingRef.current) return
    if (reset) {
      pageRef.current = 1
      hasMoreRef.current = true
      lenRef.current = 0
      setList([])
    }
    if (!reset && !hasMoreRef.current) return
    loadingRef.current = true
    setLoading(true)
    try {
      const res = await getTeacherList({
        page: pageRef.current,
        pageSize: 10,
        keyword: keywordRef.current,
      })
      const more = res.list || []
      lenRef.current = reset ? more.length : lenRef.current + more.length
      setList((prev) => (reset ? more : [...prev, ...more]))
      hasMoreRef.current = lenRef.current < res.total
      pageRef.current++
    } catch {
      // 统一提示
    } finally {
      loadingRef.current = false
      setLoading(false)
    }
  }, [])

  const onSearch = useCallback(() => {
    keywordRef.current = keyword
    load(true)
  }, [keyword, load])

  const goDetail = useCallback((id: string | number) => {
    Taro.navigateTo({ url: `/pages/teacher/detail?id=${id}` })
  }, [])

  useReachBottom(() => load())

  useEffect(() => {
    load(true)
  }, [load])

  return (
    <View className="min-h-screen bg-background">
      <View className="p-3">
        <Input
          className="h-9 px-3 bg-card rounded-lg text-sm"
          placeholder={t('teacher.list.searchPlaceholder')}
          value={keyword}
          onInput={(e) => setKeyword(e.detail.value)}
          onConfirm={onSearch}
        />
      </View>
      {list.length > 0 && (
        <View className="px-3">
          {list.map((item) => (
            <View
              key={item.id}
              className="flex bg-card rounded-2xl p-3 mb-3"
              onClick={() => goDetail(item.id)}
            >
              <Image
                className="w-[120rpx] h-[120rpx] rounded-md bg-muted flex-shrink-0"
                src={item.avatar || '/static/default-avatar.png'}
                mode="aspectFill"
              />
              <View className="flex-1 ml-3">
                <View className="flex items-center gap-2">
                  <Text className="text-base text-foreground font-semibold">{item.name}</Text>
                  {item.title && (
                    <Text className="text-xs text-primary bg-[var(--color-muted)] px-1.5 py-0.5 rounded">
                      {item.title}
                    </Text>
                  )}
                </View>
                <Text className="block text-xs text-muted-foreground mt-1.5 leading-relaxed">
                  {item.intro}
                </Text>
                <View className="flex gap-3 mt-1.5">
                  <Text className="text-xs text-muted-foreground">
                    {t('teacher.list.courseCount', { n: item.courses || 0 })}
                  </Text>
                  <Text className="text-xs text-muted-foreground">
                    {t('teacher.list.studentCount', { n: item.students || 0 })}
                  </Text>
                </View>
              </View>
            </View>
          ))}
        </View>
      )}
      {!loading && list.length === 0 && (
        <View className="text-center py-16 text-muted-foreground text-sm">
          <Text>{t('teacher.list.empty')}</Text>
        </View>
      )}
      {loading && (
        <View className="text-center py-16 text-muted-foreground text-sm">
          <Text>{t('common.loading')}</Text>
        </View>
      )}
    </View>
  )
}

// apps/miniapp/pages/topic/list.vue
<template>
  <view class="page">
    <view class="list" v-if="list.length">
      <view class="item" v-for="t in list" :key="t.id" @tap="goDetail(t.id)">
        <image class="cover" v-if="t.coverUrl" :src="t.coverUrl" mode="aspectFill" />
        <view class="body">
          <text class="name">#{{ t.name }}</text>
          <text class="count">{{ t.count }}篇内容</text>
        </view>
      </view>
    </view>
    <view class="empty" v-if="!loading && !list.length"><text>暂无话题</text></view>
    <view class="loading" v-if="loading"><text>加载中...</text></view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onReachBottom, onLoad } from '@dcloudio/uni-app'
import { getTopicList } from '@/api'

const list = ref<Array<{ id: string; name: string; count: number; coverUrl?: string }>>([])
const loading = ref(false)
const from = ref('')
const page = ref(1)
const hasMore = ref(true)

async function load(reset = false) {
  if (loading.value) return
  if (reset) { page.value = 1; hasMore.value = true; list.value = [] }
  if (!hasMore.value) return
  loading.value = true
  try {
    const res = await getTopicList({ page: page.value, pageSize: 20 })
    list.value.push(...(res.list || []))
    hasMore.value = list.value.length < res.total
    page.value++
  } finally { loading.value = false }
}
function goDetail(id: string) {
  if (from.value === 'create') {
    const pages = getCurrentPages()
    const prev = pages[pages.length - 2] as any
    prev && (prev.topic = list.value.find(t => t.id === id)?.name)
    uni.navigateBack()
  } else {
    uni.navigateTo({ url: `/pages/topic/detail?id=${id}` })
  }
}
onLoad((q: any) => { from.value = q.from || '' })
onReachBottom(() => load())
load()
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.list { padding: 24rpx; }
.item { display: flex; align-items: center; background: #fff; border-radius: 16rpx; padding: 24rpx; margin-bottom: 24rpx; }
.cover { width: 100rpx; height: 100rpx; border-radius: 12rpx; background: #f5f5f5; }
.body { margin-left: 24rpx; }
.name { display: block; font-size: 30rpx; color: #007aff; font-weight: 600; }
.count { display: block; font-size: 22rpx; color: #999; margin-top: 8rpx; }
.empty, .loading { text-align: center; padding: 120rpx 0; color: #999; }
</style>
