// packages/ui-react/src/components/sidebar.tsx
// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

'use client'

import * as React from 'react'
import { cn } from '../lib/utils'

const SidebarContext = React.createContext<boolean>(false)
const useSidebarCollapsed = () => React.useContext(SidebarContext)

function SidebarScrollHideStyles() {
  return (
    <style>{`
      [data-sidebar] .sidebar-scroll-hide {
        scrollbar-width: none;
        -ms-overflow-style: none;
      }
      [data-sidebar] .sidebar-scroll-hide::-webkit-scrollbar {
        display: none;
        width: 0;
        height: 0;
      }
    `}</style>
  )
}

export interface SidebarProps extends React.HTMLAttributes<HTMLElement> {
  collapsed?: boolean
  onToggle?: () => void
}

export const Sidebar = React.forwardRef<HTMLElement, SidebarProps>(
  ({ collapsed = false, onToggle: _onToggle, children, className, ...props }, ref) => {
    return (
      <SidebarContext.Provider value={collapsed}>
        <aside
          ref={ref}
          data-sidebar=""
          data-collapsed={collapsed || undefined}
          className={cn(
            'flex h-screen flex-col bg-sidebar text-sidebar-foreground transition-[width] duration-300 ease-in-out',
            collapsed ? 'w-[54px]' : 'w-[200px]',
            className,
          )}
          {...props}
        >
          <SidebarScrollHideStyles />
          <nav className="sidebar-scroll-hide flex-1 overflow-y-auto overflow-x-hidden px-1.5 py-2">
            {children}
          </nav>
        </aside>
      </SidebarContext.Provider>
    )
  },
)
Sidebar.displayName = 'Sidebar'

export interface SidebarGroupProps {
  title?: string
  children: React.ReactNode
  className?: string
}

export const SidebarGroup = React.forwardRef<HTMLDivElement, SidebarGroupProps>(
  ({ title, children, className }, ref) => {
    const collapsed = useSidebarCollapsed()
    return (
      <div ref={ref} className={cn('flex flex-col gap-0.5', className)}>
        {title && !collapsed && (
          <div className="px-3 py-1.5 text-xs font-semibold uppercase tracking-wider text-muted-foreground/60">
            {title}
          </div>
        )}
        {children}
      </div>
    )
  },
)
SidebarGroup.displayName = 'SidebarGroup'

export interface SidebarItemProps {
  icon?: React.ReactNode
  label: string
  href?: string
  active?: boolean
  level?: 0 | 1 | 2
  onClick?: () => void
  children?: React.ReactNode
  className?: string
}

const levelPadding = ['pl-3', 'pl-8', 'pl-13']

function setRef<T extends HTMLElement>(ref: React.Ref<T>, element: T | null) {
  if (element === null) return
  if (typeof ref === 'function') ref(element)
  else if (ref && 'current' in ref) ref.current = element
}

export const SidebarItem = React.forwardRef<HTMLElement, SidebarItemProps>(
  ({ icon, label, href, active = false, level = 0, onClick, children, className }, ref) => {
    const collapsed = useSidebarCollapsed()
    const [expanded, setExpanded] = React.useState(false)
    const hasChildren = React.Children.count(children) > 0

    const baseClass = cn(
      'flex h-9 min-w-0 items-center gap-2 rounded-md pr-3 text-sm font-medium whitespace-nowrap transition-colors',
      levelPadding[level] ?? levelPadding[0],
      active
        ? 'bg-sidebar-active text-sidebar-foreground'
        : 'text-sidebar-foreground/70 hover:bg-sidebar-hover hover:text-sidebar-foreground',
      collapsed && 'justify-center px-0',
      className,
    )

    const content = (
      <>
        {icon && <span className="flex h-4 w-4 shrink-0 items-center justify-center">{icon}</span>}
        {!collapsed && <span className="truncate">{label}</span>}
      </>
    )

    if (collapsed) {
      if (href) {
        return (
          <a
            ref={(el) => setRef(ref, el)}
            href={href}
            onClick={onClick}
            title={label}
            aria-label={label}
            aria-current={active ? 'page' : undefined}
            className={baseClass}
          >
            {content}
          </a>
        )
      }
      return (
        <button
          ref={(el) => setRef(ref, el)}
          onClick={onClick}
          title={label}
          aria-label={label}
          aria-current={active ? 'page' : undefined}
          className={baseClass}
        >
          {content}
        </button>
      )
    }

    if (hasChildren) {
      return (
        <div ref={(el) => setRef(ref, el)} className="flex flex-col">
          <button
            type="button"
            onClick={() => setExpanded((e) => !e)}
            aria-expanded={expanded}
            className={cn(baseClass, 'w-full')}
          >
            {content}
            <svg
              className={cn(
                'ml-auto h-3.5 w-3.5 shrink-0 transition-transform',
                expanded && 'rotate-180',
              )}
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <polyline points="6 9 12 15 18 9" />
            </svg>
          </button>
          {expanded && <div className="flex flex-col gap-0.5">{children}</div>}
        </div>
      )
    }

    if (href) {
      return (
        <a
          ref={(el) => setRef(ref, el)}
          href={href}
          onClick={onClick}
          aria-current={active ? 'page' : undefined}
          className={baseClass}
        >
          {content}
        </a>
      )
    }

    return (
      <button
        ref={(el) => setRef(ref, el)}
        type="button"
        onClick={onClick}
        aria-current={active ? 'page' : undefined}
        className={baseClass}
      >
        {content}
      </button>
    )
  },
)
SidebarItem.displayName = 'SidebarItem'
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

// apps/assistant/src/components/Sidebar.tsx
// © 2026 IHUI AI (智汇AI) · 版权所有者: 李春川 (Li Chunchuan) · https://aizhs.top
// Provenance-watermarked. 未授权商用可被溯源追责 (Apache-2.0 须保留本声明与 NOTICE)。
// [IHUI-AI-PROVENANCE]:⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠

import {
  LayoutDashboard,
  Users,
  PlayCircle,
  Coins,
  ScrollText,
  Settings,
  Server,
} from 'lucide-react'
import { useAppStore } from '../store'
import { cn } from '../lib/cn'
import type { ModuleKey, ViewKey } from '../types'

export type { ViewKey }

const TRAE_NAV: { key: ViewKey; label: string; icon: typeof Users }[] = [
  { key: 'dashboard', label: '概览', icon: LayoutDashboard },
  { key: 'accounts', label: '账号管理', icon: Users },
  { key: 'checkin', label: '一键签到', icon: PlayCircle },
  { key: 'credits', label: '积分看板', icon: Coins },
  { key: 'api-service', label: 'API 服务', icon: Server },
]

const WB_NAV: { key: ViewKey; label: string; icon: typeof Users }[] = [
  { key: 'wb-dashboard', label: '概览', icon: LayoutDashboard },
  { key: 'wb-accounts', label: '账号管理', icon: Users },
  { key: 'wb-checkin', label: '一键签到', icon: PlayCircle },
  { key: 'wb-credits', label: '积分概览', icon: Coins },
]

const GLOBAL_NAV: { key: ViewKey; label: string; icon: typeof Users }[] = [
  { key: 'logs', label: '系统日志', icon: ScrollText },
  { key: 'settings', label: '系统设置', icon: Settings },
]

const MODULE_LABELS: { key: ModuleKey; label: string }[] = [
  { key: 'trae', label: 'TRAE' },
  { key: 'workbuddy', label: 'WorkBuddy' },
]

export default function Sidebar({ view, onNav }: { view: ViewKey; onNav: (v: ViewKey) => void }) {
  const module = useAppStore((s) => s.module)
  const setModule = useAppStore((s) => s.setModule)
  const moduleNav = module === 'trae' ? TRAE_NAV : WB_NAV
  return (
    <aside className="flex w-52 shrink-0 flex-col border-r border-slate-200 bg-white dark:border-zinc-800 dark:bg-zinc-950">
      {/* 模块胶囊分段控制器 */}
      <div className="p-3 pb-2">
        <div className="relative flex rounded-full bg-slate-100 p-1 dark:bg-zinc-900">
          <span
            aria-hidden
            className={cn(
              'absolute inset-y-1 left-1 w-[calc(50%-4px)] rounded-full bg-zinc-900 transition-transform duration-300 ease-out dark:bg-zinc-100',
              module === 'workbuddy' && 'translate-x-full',
            )}
          />
          {MODULE_LABELS.map((m) => (
            <button
              key={m.key}
              onClick={() => setModule(m.key)}
              className={cn(
                'relative z-10 flex flex-1 items-center justify-center rounded-full py-1.5 text-xs font-semibold transition-colors',
                module === m.key
                  ? 'text-white dark:text-zinc-900'
                  : 'text-slate-500 hover:text-slate-700 dark:text-zinc-400 dark:hover:text-zinc-200',
              )}
            >
              {m.label}
            </button>
          ))}
        </div>
      </div>

      {/* 模块菜单 */}
      <nav className="flex-1 space-y-1 p-3">
        {moduleNav.map((item) => {
          const Icon = item.icon
          const active = view === item.key
          return (
            <button
              key={item.key}
              onClick={() => onNav(item.key)}
              className={cn(
                'flex w-full items-center gap-3 rounded-sm px-3 py-2 text-sm font-medium transition active:scale-[0.98]',
                active
                  ? 'bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900'
                  : 'text-slate-600 hover:bg-slate-100 dark:text-zinc-400 dark:hover:bg-zinc-800',
              )}
            >
              <Icon size={17} />
              {item.label}
            </button>
          )
        })}
      </nav>

      {/* 底部固定：全局功能 */}
      <div className="relative border-t border-slate-200 p-3 dark:border-zinc-800">
        <nav className="mb-2 space-y-1">
          {GLOBAL_NAV.map((item) => {
            const Icon = item.icon
            const active = view === item.key
            return (
              <button
                key={item.key}
                onClick={() => onNav(item.key)}
                className={cn(
                  'flex w-full items-center gap-3 rounded-sm px-3 py-2 text-sm font-medium transition active:scale-[0.98]',
                  active
                    ? 'bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900'
                    : 'text-slate-600 hover:bg-slate-100 dark:text-zinc-400 dark:hover:bg-zinc-800',
                )}
              >
                <Icon size={17} />
                {item.label}
              </button>
            )
          })}
        </nav>
      </div>
    </aside>
  )
}
// ⁠​‌​​‌​​‌‍‍​‌​​‌​​​‍‍​‌​‌​‌​‌‍‍​‌​​‌​​‌‍‍​​‌​‌‌​‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌​​‌‌‌‌​‌​‍‍‌‌​‌‌​​​‌​​​‌‌‌‍‍​‌​​​​​‌‍‍​‌​​‌​​‌‍‍‌​‌‌​‌‌‌‍‍‌‌​​‌‌‌​‌​​‌‌‌​‍‍‌‌​​‌‌​​​‌​​‌​‌‍‍‌​‌‌‌​‌‌‌​‌‌‌​‌‍‍‌​‌‌​‌‌‌‍‍​‌​​‌‌​​‍‍​‌​​​​‌‌‍‍‌​‌‌​‌‌‌‍‍​‌‌​​​​‌‍‍​‌‌​‌​​‌‍‍​‌‌‌‌​‌​‍‍​‌‌​‌​​​‍‍​‌‌‌​​‌‌‍‍​​‌​‌‌‌​‍‍​‌‌‌​‌​​‍‍​‌‌​‌‌‌‌‍‍​‌‌‌​​​​‍‍‌​‌‌​‌‌‌‍‍​‌​‌​​​​‍‍​‌​‌​​‌​‍‍​‌​​‌‌‌‌‍‍​‌​‌​‌‌​‍‍​‌​​​‌​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​​‌‍‍​‌​​‌‌‌​‍‍​‌​​​​‌‌‍‍​‌​​​‌​‌‍‍​​‌​‌‌​‌‍‍​​‌‌​​‌​‍‍​​‌‌​​​​‍‍​​‌‌​​‌​‍‍​​‌‌​‌‌​⁠
