// apps/miniapp/pages/pay/result.vue
<template>
  <view class="page">
    <view class="result" :class="status">
      <view class="icon">{{ status === 'paid' ? '✓' : status === 'failed' ? '×' : '…' }}</view>
      <text class="title">{{ status === 'paid' ? '支付成功' : status === 'failed' ? '支付失败' : '支付处理中' }}</text>
      <text class="amount" v-if="amount">¥{{ amount }}</text>
    </view>
    <view class="actions" v-if="status !== 'pending'">
      <button class="btn primary" @tap="goHome">返回首页</button>
      <button class="btn" @tap="goOrders">查看订单</button>
    </view>
    <view class="actions" v-else>
      <button class="btn primary" @tap="check">刷新状态</button>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { getPayResult } from '@/api'

const orderNo = ref('')
const status = ref<'pending' | 'paid' | 'failed'>('pending')
const amount = ref(0)

onLoad((q: any) => { orderNo.value = q.orderNo || ''; check() })

async function check() {
  if (!orderNo.value) return
  try {
    const res = await getPayResult(orderNo.value)
    status.value = res.status
    amount.value = res.amount
  } catch (e) {}
}
function goHome() { uni.switchTab({ url: '/pages/index/index' }) }
function goOrders() { uni.navigateTo({ url: '/pages/order/list' }) }
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.result { padding: 120rpx 0; text-align: center; }
.icon { width: 160rpx; height: 160rpx; line-height: 160rpx; margin: 0 auto; border-radius: 50%; font-size: 80rpx; color: #fff; }
.result.paid .icon { background: #4caf50; }
.result.failed .icon { background: #dd524d; }
.result.pending .icon { background: #ff9a3c; }
.title { display: block; font-size: 36rpx; color: #333; font-weight: 600; margin-top: 32rpx; }
.amount { display: block; font-size: 40rpx; color: #dd524d; margin-top: 16rpx; }
.actions { padding: 0 60rpx; }
.btn { margin-top: 32rpx; background: #fff; color: #333; border-radius: 40rpx; font-size: 30rpx; }
.btn.primary { background: #007aff; color: #fff; }
</style>

// apps/miniapp-taro/src/pages/pay/result.tsx
import { View, Text, Button } from '@tarojs/components'
import Taro, { useRouter } from '@tarojs/taro'
import { useState, useRef, useEffect } from 'react'
import { getPayResult } from '@/api'

type PayStatus = 'pending' | 'paid' | 'failed'

const STATUS_TEXT: Record<PayStatus, string> = {
  pending: '支付处理中',
  paid: '支付成功',
  failed: '支付失败',
}

const STATUS_ICON: Record<PayStatus, string> = {
  pending: '…',
  paid: '✓',
  failed: '×',
}

const STATUS_BG: Record<PayStatus, string> = {
  pending: 'bg-[#ff9a3c]',
  paid: 'bg-[#4caf50]',
  failed: 'bg-[#dd524d]',
}

export default function PayResult() {
  const router = useRouter()
  const [status, setStatus] = useState<PayStatus>('pending')
  const [amount, setAmount] = useState(0)
  const orderNoRef = useRef('')

  useEffect(() => {
    orderNoRef.current = router.params.orderNo || ''
    check()
  }, [router.params.orderNo])

  async function check() {
    if (!orderNoRef.current) return
    try {
      const res = await getPayResult(orderNoRef.current)
      setStatus(res.status)
      setAmount(res.amount)
    } catch {
      // ignore
    }
  }

  const goHome = () => {
    Taro.switchTab({ url: '/pages/index/index' })
  }

  const goOrders = () => {
    Taro.navigateTo({ url: '/pages/order/list' })
  }

  return (
    <View className="min-h-screen bg-[#f7f8fa]">
      <View className="pt-[120rpx] pb-[120rpx] text-center">
        <View
          className={`w-[160rpx] h-[160rpx] leading-[160rpx] mx-auto rounded-full text-[80rpx] text-white ${STATUS_BG[status]}`}
        >
          {STATUS_ICON[status]}
        </View>
        <Text className="block text-[36rpx] text-[#333] font-semibold mt-[32rpx]">
          {STATUS_TEXT[status]}
        </Text>
        {amount > 0 && (
          <Text className="block text-[40rpx] text-[#dd524d] mt-[16rpx]">¥{amount}</Text>
        )}
      </View>
      {status !== 'pending' ? (
        <View className="px-[60rpx]">
          <Button
            className="mt-[32rpx] bg-[#007aff] text-white rounded-[40rpx] text-[30rpx]"
            onClick={goHome}
          >
            返回首页
          </Button>
          <Button
            className="mt-[32rpx] bg-white text-[#333] rounded-[40rpx] text-[30rpx]"
            onClick={goOrders}
          >
            查看订单
          </Button>
        </View>
      ) : (
        <View className="px-[60rpx]">
          <Button
            className="mt-[32rpx] bg-[#007aff] text-white rounded-[40rpx] text-[30rpx]"
            onClick={check}
          >
            刷新状态
          </Button>
        </View>
      )}
    </View>
  )
}
