// apps/miniapp-taro/src/pages/index/index.tsx
import { View, Text, Image, Swiper, SwiperItem, ScrollView } from '@tarojs/components'
import Taro, { useDidShow, useShareAppMessage, useShareTimeline } from '@tarojs/taro'
import { useState, useEffect, useCallback } from 'react'
import { isLoggedIn, getUserInfo, type UserInfo } from '@/utils/auth'
import { getHomePage, getCourseList, getLiveList, getStudyInfo, getBannerList, getCircleList, type Banner, type Course, type Live } from '@/api'
import { useI18n } from '@/i18n'

const defaultAvatar =
  'https://mp-aab956eb-2e97-4b81-823e-69195b354e49.cdn.bspapp.com/tabbar/tabbar/home.png'

// 教育快捷入口
const entries = [
  { icon: '📚', key: 'home.entry.course', path: '/pages/course/list' },
  { icon: '📺', key: 'home.entry.live', path: '/pages/live/list' },
  { icon: '🤖', key: 'home.entry.ai', path: '/pages/ai/chat' },
  { icon: '📋', key: 'home.entry.order', path: '/pages/user/orders' },
  { icon: '⚙️', key: 'home.entry.setting', path: '/pages/user/settings' },
]

// AI 应用入口(融合原项目 AI 应用商店概念)
const aiEntries = [
  { icon: '💬', key: 'home.aiEntries.aiChat', path: '/pages/ai/chat' },
  { icon: '🎨', key: 'home.aiEntries.aiImage', path: '/pages/ai/image' },
  { icon: '🎙️', key: 'home.aiEntries.aiVoice', path: '/pages/ai/voice' },
  { icon: '🎬', key: 'home.aiEntries.aiVideo', path: '/pages/ai/video' },
  { icon: '⚡', key: 'home.aiEntries.agent', path: '/pages/ai/agent' },
  { icon: '🏛️', key: 'home.aiEntries.modelPlaza', path: '/pages/model-plaza/index' },
]

interface StudyStats {
  todayMinutes: number
  totalMinutes: number
  continuousDays: number
  courses: number
}

export default function Index() {
  const { t } = useI18n()
  const [isLogin, setIsLogin] = useState(false)
  const [userInfo, setUserInfo] = useState<UserInfo | null>(null)
  const [bannerList, setBannerList] = useState<Banner[]>([])
  const [courseList, setCourseList] = useState<Course[]>([])
  const [livePreview, setLivePreview] = useState<Live[]>([])
  const [study, setStudy] = useState<StudyStats | null>(null)
  const [circlePreview, setCirclePreview] = useState<Record<string, unknown>[]>([])

  function refreshUser() {
    setIsLogin(isLoggedIn())
    setUserInfo(getUserInfo())
  }

  function goLogin() {
    Taro.navigateTo({ url: '/pages/login/login' })
  }

  function goPage(path: string) {
    Taro.switchTab({ url: path, fail: () => Taro.navigateTo({ url: path }) })
  }

  function goCourseDetail(id: string | number) {
    Taro.navigateTo({ url: `/pages/course/detail?id=${id}` })
  }

  function goLiveDetail(id: string | number) {
    Taro.navigateTo({ url: `/pages/live/detail?id=${id}` })
  }

  function onBannerClick(item: Banner) {
    if (item.link) Taro.navigateTo({ url: item.link })
  }

  const loadData = useCallback(async () => {
    try {
      const [banners, courses, lives, studyRes, home, circles] = await Promise.all([
        // 运营 banner 独立接口优先(支持精细化运营配置)
        getBannerList({ position: 'home', status: 1 })
          .then((res) => res.list || [])
          .catch(() => null),
        getCourseList({ page: 1, pageSize: 6 }).catch(() => ({ list: [] as Course[], total: 0 })),
        getLiveList({ page: 1, pageSize: 4, status: 'upcoming' }).catch(
          () => ({ list: [] as Live[], total: 0 }),
        ),
        getStudyInfo().catch(
          () => ({ todayMinutes: 0, totalMinutes: 0, continuousDays: 0, courses: 0 }),
        ),
        // 兜底:home 聚合接口里的 banner
        getHomePage().catch(() => null),
        // 智汇社区动态预览
        getCircleList({ page: 1, pageSize: 3 })
          .then((res) => (res?.list as unknown as Record<string, unknown>[]) || [])
          .catch(() => [] as Record<string, unknown>[]),
      ])
      const list =
        banners ?? (home?.banner as Banner[] | undefined) ?? []
      setBannerList(list)
      setCourseList(courses.list || [])
      setLivePreview(lives.list || [])
      setStudy(studyRes as StudyStats)
      setCirclePreview(circles)
    } catch {
      // 静默处理,首页可离线展示
    }
  }, [])

  useEffect(() => {
    loadData()
  }, [loadData])
  useDidShow(() => {
    refreshUser()
  })

  // 微信分享配置(转发给好友/朋友圈)
  useShareAppMessage(() => ({
    title: t('share.appTitle'),
    path: '/pages/index/index',
    imageUrl: '/static/share.png',
  }))
  useShareTimeline(() => ({
    title: t('share.timelineTitle'),
    query: '',
  }))

  const showLearningSection = isLogin && study && study.courses > 0

  return (
    <View className="min-h-screen pb-[20px]">
      {/* 顶部用户信息条 — 青→紫赛博朋克渐变 + 科技网格 */}
      <View
        className="flex items-center pt-[60px] px-[16px] pb-[16px] tech-grid"
        style={{ background: 'linear-gradient(135deg, #00f2ff, #8b5cf6)' }}
      >
        <Image
          className="w-[40px] h-[40px] rounded-md border-[1px] border-solid border-white"
          src={userInfo?.avatar || defaultAvatar}
          mode="aspectFill"
        />
        <View className="ml-[10px] flex flex-col">
          <Text className="text-white text-[15px] font-semibold">
            {userInfo?.userName || userInfo?.nickname || (isLogin ? t('common.user') : t('home.tapLogin'))}
          </Text>
          {isLogin ? (
            <Text className="text-white text-[11px] opacity-90">
              {study
                ? `${t('home.todayMinutes', { n: study.todayMinutes })} · ${t('home.continuousDays', { n: study.continuousDays })}`
                : t('home.slogan')}
            </Text>
          ) : (
            <Text className="text-white text-[11px] opacity-90" onClick={goLogin}>
              {t('home.slogan')}
            </Text>
          )}
        </View>
      </View>

      {/* 轮播图 — 渐变描边(对标原项目 custom-carousel-wrapper + gradient-border)*/}
      <View className="mx-[16px] my-[12px] carousel-cyber">
        <Swiper
          className="h-[140px] carousel-cyber-inner"
          indicatorDots
          autoplay
          interval={4000}
          circular
        >
          {bannerList.map((item) => (
            <SwiperItem key={item.id} onClick={() => onBannerClick(item)}>
              <Image className="w-full h-full" src={item.coverUrl} mode="aspectFill" />
            </SwiperItem>
          ))}
          {bannerList.length === 0 ? (
            <SwiperItem>
              <View className="w-full h-full flex items-center justify-center text-[15px]">
                <Text className="text-neon">{t('home.slogan')}</Text>
              </View>
            </SwiperItem>
          ) : null}
        </Swiper>
      </View>

      {/* 学习进度(登录后)— 玻璃拟态卡片 */}
      {showLearningSection && study ? (
        <View className="mx-[16px] mb-[12px] glass px-[12px] py-[12px]">
          <View className="flex justify-between items-center">
            <Text className="text-[15px] text-white font-semibold">
              {t('home.learningProgress')}
            </Text>
            <Text
              className="text-[12px] text-muted-foreground"
              onClick={() => Taro.navigateTo({ url: '/pages/study/my-study/index' })}
            >
              {t('home.more')} {'>'}
            </Text>
          </View>
          <View className="flex mt-[10px]">
            <View className="flex-1 text-center">
              <Text className="block text-[18px] text-neon font-bold">
                {study.todayMinutes}
              </Text>
              <Text className="text-[11px] text-muted-foreground mt-[2px]">
                {t('home.todayMinutes', { n: '' })}
              </Text>
            </View>
            <View className="flex-1 text-center">
              <Text className="block text-[18px] text-neon font-bold">
                {study.totalMinutes}
              </Text>
              <Text className="text-[11px] text-muted-foreground mt-[2px]">
                {t('home.totalMinutes', { n: '' })}
              </Text>
            </View>
            <View className="flex-1 text-center">
              <Text className="block text-[18px] text-neon font-bold">
                {study.continuousDays}
              </Text>
              <Text className="text-[11px] text-muted-foreground mt-[2px]">
                {t('home.continuousDays', { n: '' })}
              </Text>
            </View>
            <View className="flex-1 text-center">
              <Text className="block text-[18px] text-neon font-bold">{study.courses}</Text>
              <Text className="text-[11px] text-muted-foreground mt-[2px]">
                {t('home.coursesCount', { n: '' })}
              </Text>
            </View>
          </View>
        </View>
      ) : null}

      {/* AI 应用入口(融合原项目 AI 应用商店概念)— 赛博朋克网格 */}
      <View className="mx-[16px] my-[12px] tech-card p-[12px]">
        <View className="flex justify-between items-center mb-[10px]">
          <Text className="text-[15px] font-semibold text-neon">{t('home.aiAppTitle')}</Text>
          <Text
            className="text-[12px] text-muted-foreground"
            onClick={() => goPage('/pages/ai/agent')}
          >
            {t('home.more')} {'>'}
          </Text>
        </View>
        <View className="flex flex-wrap">
          {aiEntries.map((entry) => (
            <View
              key={entry.path}
              className="w-1/3 flex flex-col items-center py-[10px]"
              onClick={() => goPage(entry.path)}
            >
              <View className="w-[44px] h-[44px] rounded-[10px] gradient-cyber flex items-center justify-center mb-[4px]">
                <Text className="text-[22px]">{entry.icon}</Text>
              </View>
              <Text className="text-[11px] text-white">{t(entry.key)}</Text>
            </View>
          ))}
        </View>
      </View>

      {/* 智汇社区动态预览 — 点击进入智汇社区 tab */}
      {circlePreview.length > 0 ? (
        <View className="mx-[16px] my-[12px]">
          <View className="flex justify-between items-center mb-[10px]">
            <Text className="text-[15px] font-semibold text-neon">{t('community.title')}</Text>
            <Text
              className="text-[12px] text-muted-foreground"
              onClick={() => Taro.switchTab({ url: '/pages/community/index' })}
            >
              {t('home.more')} {'>'}
            </Text>
          </View>
          {circlePreview.map((item) => (
            <View
              key={item.id as string}
              className="tech-card px-[12px] py-[10px] mb-[8px]"
              onClick={() => Taro.navigateTo({ url: `/pages/circle/detail?id=${item.id}` })}
            >
              <View className="flex items-center mb-[4px]">
                <Image
                  className="w-[20px] h-[20px] rounded-md bg-muted"
                  src={(item.authorAvatar as string) || defaultAvatar}
                  mode="aspectFill"
                />
                <Text className="ml-[6px] text-[11px] text-muted-foreground">
                  {(item.authorName as string) || t('common.user')}
                </Text>
              </View>
              <Text className="block text-[13px] text-white font-semibold truncate">
                {(item.title as string) || t('aiCircle.post')}
              </Text>
            </View>
          ))}
        </View>
      ) : null}

      {/* 直播预告 */}
      {livePreview.length > 0 ? (
        <View className="mx-[16px] my-[12px] tech-card px-[12px] py-[12px]">
          <View className="flex justify-between items-center">
            <Text className="text-[15px] text-white font-semibold">{t('home.livePreview')}</Text>
            <Text className="text-[12px] text-muted-foreground" onClick={() => goPage('/pages/live/list')}>
              {t('home.more')} {'>'}
            </Text>
          </View>
          <ScrollView scrollX className="mt-[10px]">
            <View className="flex">
              {livePreview.map((live) => (
                <View
                  key={live.id}
                  className="inline-block w-[160px] mr-[10px] flex-shrink-0"
                  onClick={() => goLiveDetail(live.id)}
                >
                  <View className="relative w-[160px] h-[90px] rounded-[8px] overflow-hidden">
                    <Image className="w-full h-full" src={live.coverUrl} mode="aspectFill" />
                    <View className="absolute top-1 right-1 px-[4px] py-[1px] bg-[#f59e0b] text-white text-[10px] rounded-[3px]">
                      <Text>{t('live.preview')}</Text>
                    </View>
                  </View>
                  <Text className="block mt-[6px] text-[12px] text-white truncate">
                    {live.title}
                  </Text>
                  <Text className="block text-[10px] text-muted-foreground truncate">
                    {live.startTime ? `${t('home.startTime')}: ${live.startTime}` : ''}
                  </Text>
                </View>
              ))}
            </View>
          </ScrollView>
        </View>
      ) : null}

      {/* 教育快捷入口 */}
      <View className="flex flex-wrap px-[16px] py-[10px] tech-card mx-[16px] rounded-[12px]">
        {entries.map((entry) => (
          <View
            key={entry.path}
            className="w-1/5 flex flex-col items-center py-[8px]"
            onClick={() => goPage(entry.path)}
          >
            <Text className="text-[22px]">{entry.icon}</Text>
            <Text className="mt-[3px] text-[11px] text-white">{t(entry.key)}</Text>
          </View>
        ))}
      </View>

      {/* 推荐课程 */}
      <View className="mx-[16px] my-[12px]">
        <View className="flex justify-between items-center mb-[10px]">
          <Text className="text-[15px] font-semibold text-neon">{t('home.hotCourses')}</Text>
          <Text className="text-[12px] text-muted-foreground" onClick={() => goPage('/pages/course/list')}>
            {t('home.more')} {'>'}
          </Text>
        </View>
        <ScrollView scrollX>
          <View className="flex">
            {courseList.map((c) => (
              <View
                key={c.id}
                className="inline-block w-[140px] mr-[10px] tech-card rounded-[12px] overflow-hidden flex-shrink-0"
                onClick={() => goCourseDetail(c.id)}
              >
                <Image className="w-full h-[80px]" src={c.coverUrl} mode="aspectFill" />
                <Text className="block px-[6px] pt-[6px] text-[12px] text-white truncate">
                  {c.title}
                </Text>
                <Text className="block px-[6px] pb-[6px] text-[13px] text-neon font-semibold">
                  ¥{c.price ?? 0}
                </Text>
              </View>
            ))}
          </View>
        </ScrollView>
      </View>
    </View>
  )
}

// apps/miniapp/pages/index/index.vue
<template>
  <view class="page">
    <!-- 顶部用户信息条 -->
    <view v-if="isLogin && userInfo" class="user-bar">
      <image class="avatar" :src="userInfo.avatar || defaultAvatar" mode="aspectFill" />
      <view class="user-meta">
        <text class="name">{{ userInfo.userName || userInfo.nickname || '用户' }}</text>
        <text v-if="userInfo.isVip" class="vip-tag">VIP</text>
      </view>
      <text class="login-entry" v-else @tap="goLogin">去登录</text>
    </view>
    <view v-else class="user-bar">
      <image class="avatar" :src="defaultAvatar" mode="aspectFill" />
      <text class="name" @tap="goLogin">点击登录</text>
    </view>

    <!-- 轮播图 -->
    <swiper class="banner" :indicator-dots="true" :autoplay="true" :interval="4000" circular>
      <swiper-item v-for="item in bannerList" :key="item.id" @tap="onBannerClick(item)">
        <image class="banner-img" :src="item.coverUrl" mode="aspectFill" />
      </swiper-item>
      <swiper-item v-if="bannerList.length === 0">
        <view class="banner-empty"><text>智汇社区 · AI 赋能学习</text></view>
      </swiper-item>
    </swiper>

    <!-- 功能入口 -->
    <view class="entry-grid">
      <view class="entry-item" v-for="entry in entries" :key="entry.path" @tap="goPage(entry.path)">
        <text class="entry-icon">{{ entry.icon }}</text>
        <text class="entry-text">{{ entry.text }}</text>
      </view>
    </view>

    <!-- 推荐课程 -->
    <view class="section">
      <view class="section-head">
        <text class="section-title">热门课程</text>
        <text class="section-more" @tap="goPage('/pages/course/list')">更多 ></text>
      </view>
      <scroll-view scroll-x class="course-scroll" :show-scrollbar="false">
        <view class="course-card" v-for="c in courseList" :key="c.id" @tap="goCourseDetail(c.id)">
          <image class="course-cover" :src="c.coverUrl" mode="aspectFill" />
          <text class="course-title">{{ c.title }}</text>
          <text class="course-price">¥{{ c.price ?? 0 }}</text>
        </view>
      </scroll-view>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { isLoggedIn, getUserInfo, type UserInfo } from '@/utils/auth'
import { getHomePage, getCourseList, type Banner, type Course } from '@/api'

const defaultAvatar = 'https://mp-aab956eb-2e97-4b81-823e-69195b354e49.cdn.bspapp.com/tabbar/tabbar/home.png'

const isLogin = ref(false)
const userInfo = ref<UserInfo | null>(null)
const bannerList = ref<Banner[]>([])
const courseList = ref<Course[]>([])

const entries = [
  { icon: '📚', text: '课程', path: '/pages/course/list' },
  { icon: '📺', text: '直播', path: '/pages/live/list' },
  { icon: '🤖', text: 'AI', path: '/pages/ai/chat' },
  { icon: '📋', text: '订单', path: '/pages/user/orders' },
  { icon: '⚙️', text: '设置', path: '/pages/user/settings' },
]

function refreshUser() {
  isLogin.value = isLoggedIn()
  userInfo.value = getUserInfo()
}

function goLogin() {
  uni.navigateTo({ url: '/pages/login/login' })
}

function goPage(path: string) {
  uni.switchTab({ url: path, fail: () => uni.navigateTo({ url: path }) })
}

function goCourseDetail(id: string | number) {
  uni.navigateTo({ url: `/pages/course/detail?id=${id}` })
}

function onBannerClick(item: Banner) {
  if (item.link) uni.navigateTo({ url: item.link })
}

async function loadData() {
  try {
    const [home, courses] = await Promise.all([
      getHomePage().catch(() => ({ banner: [] })),
      getCourseList({ page: 1, pageSize: 6 }).catch(() => ({ list: [], total: 0 })),
    ])
    bannerList.value = home.banner || []
    courseList.value = courses.list || []
  } catch (e) {
    // 静默处理，首页可离线展示
  }
}

onMounted(loadData)
onShow(refreshUser)
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; padding-bottom: 40rpx; }

.user-bar {
  display: flex; align-items: center; padding: 120rpx 32rpx 24rpx;
  background: linear-gradient(135deg, #007aff, #00c6ff);
  .avatar { width: 72rpx; height: 72rpx; border-radius: 50%; border: 2rpx solid #fff; }
  .user-meta { margin-left: 20rpx; display: flex; align-items: center; }
  .name { color: #fff; font-size: 30rpx; font-weight: 600; }
  .vip-tag { margin-left: 12rpx; padding: 2rpx 12rpx; background: #f0ad4e; color: #fff; font-size: 20rpx; border-radius: 20rpx; }
  .login-entry { margin-left: auto; color: #fff; font-size: 26rpx; }
}

.banner { height: 280rpx; margin: 24rpx 32rpx; border-radius: 16rpx; overflow: hidden; }
.banner-img { width: 100%; height: 100%; }
.banner-empty { width: 100%; height: 100%; display: flex; align-items: center; justify-content: center; background: #fff; color: #007aff; font-size: 30rpx; }

.entry-grid {
  display: flex; flex-wrap: wrap; padding: 16rpx 32rpx; background: #fff; margin: 0 32rpx; border-radius: 16rpx;
  .entry-item { width: 20%; display: flex; flex-direction: column; align-items: center; padding: 24rpx 0; }
  .entry-icon { font-size: 48rpx; }
  .entry-text { margin-top: 8rpx; font-size: 24rpx; color: #333; }
}

.section { margin: 32rpx; }
.section-head { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20rpx; }
.section-title { font-size: 32rpx; font-weight: 600; color: #333; }
.section-more { font-size: 24rpx; color: #999; }

.course-scroll { white-space: nowrap; }
.course-card {
  display: inline-block; width: 280rpx; margin-right: 20rpx; background: #fff; border-radius: 16rpx; overflow: hidden;
  .course-cover { width: 100%; height: 160rpx; }
  .course-title { display: block; padding: 12rpx; font-size: 26rpx; color: #333; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .course-price { display: block; padding: 0 12rpx 12rpx; font-size: 28rpx; color: #dd524d; font-weight: 600; }
}
</style>
