// apps/miniapp-taro/src/pages/order/list.tsx
import { View, Text } from '@tarojs/components'
import Taro, { useDidShow, useReachBottom, usePullDownRefresh } from '@tarojs/taro'
import { useState, useRef } from 'react'
import { getOrderList, type Order } from '@/api'

const STATUS_TEXT: Record<string, string> = {
  pending: '待支付',
  paid: '已支付',
  cancelled: '已取消',
  refunded: '已退款',
}

const STATUS_COLOR: Record<string, string> = {
  paid: 'text-[#4caf50]',
  pending: 'text-[#ff9a3c]',
  refunded: 'text-[#999]',
}

const TABS = [
  { value: '', label: '全部' },
  { value: 'pending', label: '待支付' },
  { value: 'paid', label: '已支付' },
  { value: 'refunded', label: '已退款' },
]

const PAGE_SIZE = 10

export default function OrderList() {
  const [list, setList] = useState<Order[]>([])
  const [loading, setLoading] = useState(false)
  const [status, setStatus] = useState('')
  const statusRef = useRef('')
  const pageRef = useRef(1)
  const hasMoreRef = useRef(true)
  const loadingRef = useRef(false)

  const load = async (reset = false) => {
    if (loadingRef.current) return
    if (reset) {
      pageRef.current = 1
      hasMoreRef.current = true
      setList([])
    }
    if (!hasMoreRef.current) return
    loadingRef.current = true
    setLoading(true)
    try {
      const res = await getOrderList({
        page: pageRef.current,
        pageSize: PAGE_SIZE,
        status: statusRef.current || undefined,
      })
      const items = res.list || []
      setList(prev => (reset ? items : [...prev, ...items]))
      hasMoreRef.current = pageRef.current * PAGE_SIZE < res.total
      pageRef.current++
    } catch {
      // ignore
    } finally {
      loadingRef.current = false
      setLoading(false)
    }
  }

  const switchTab = (s: string) => {
    statusRef.current = s
    setStatus(s)
    load(true)
  }

  const goDetail = (id: string | number) => {
    Taro.navigateTo({ url: `/pages/order/detail?id=${id}` })
  }

  const goRefund = (o: Order) => {
    Taro.navigateTo({ url: `/pages/order/refund?orderNo=${o.orderNo}` })
  }

  useDidShow(() => {
    load(true)
  })
  useReachBottom(() => {
    load()
  })
  usePullDownRefresh(() => {
    load(true).finally(() => Taro.stopPullDownRefresh())
  })

  return (
    <View className="min-h-screen bg-[#f7f8fa]">
      <View className="flex bg-white sticky top-0 z-10">
        {TABS.map(tab => (
          <Text
            key={tab.value}
            className={`flex-1 text-center text-[26rpx] py-[24rpx] ${status === tab.value ? 'text-[#007aff] font-semibold' : 'text-[#666]'}`}
            onClick={() => switchTab(tab.value)}
          >
            {tab.label}
          </Text>
        ))}
      </View>
      {list.length > 0 && (
        <View className="p-[24rpx]">
          {list.map(o => (
            <View
              key={o.id}
              className="bg-white rounded-[16rpx] p-[32rpx] mb-[24rpx]"
              onClick={() => goDetail(o.id)}
            >
              <View className="flex justify-between items-center">
                <Text className="text-[30rpx] text-[#333] font-semibold">{o.title}</Text>
                <Text className={`text-[24rpx] ${STATUS_COLOR[o.status] || ''}`}>
                  {STATUS_TEXT[o.status] || o.status}
                </Text>
              </View>
              <Text className="block text-[22rpx] text-[#999] mt-[12rpx]">订单号：{o.orderNo}</Text>
              <View className="flex justify-between mt-[16rpx]">
                <Text className="text-[24rpx] text-[#999]">{o.createTime}</Text>
                <Text className="text-[32rpx] text-[#dd524d] font-semibold">¥{o.amount}</Text>
              </View>
              {o.status === 'paid' && (
                <View className="mt-[24rpx] text-right">
                  <Text
                    className="inline-block text-[24rpx] text-[#007aff] px-[24rpx] py-[8rpx] border-[2rpx] border-[#007aff] rounded-[24rpx]"
                    onClick={e => {
                      e.stopPropagation()
                      goRefund(o)
                    }}
                  >
                    申请退款
                  </Text>
                </View>
              )}
            </View>
          ))}
        </View>
      )}
      {list.length === 0 && !loading && (
        <View className="text-center py-[120rpx] text-[#999]">
          <Text>暂无订单</Text>
        </View>
      )}
      {loading && (
        <View className="text-center py-[120rpx] text-[#999]">
          <Text>加载中...</Text>
        </View>
      )}
    </View>
  )
}

// apps/miniapp/pages/exam/list.vue
<template>
  <view class="page">
    <view class="tabs">
      <text class="tab" :class="{ active: status === '' }" @tap="switchTab('')">全部</text>
      <text class="tab" :class="{ active: status === 'pending' }" @tap="switchTab('pending')">待考试</text>
      <text class="tab" :class="{ active: status === 'done' }" @tap="switchTab('done')">已完成</text>
    </view>
    <view class="list" v-if="list.length">
      <view class="item" v-for="e in list" :key="e.id" @tap="goDetail(e)">
        <view class="item-top">
          <text class="title">{{ e.title }}</text>
          <text class="status" :class="e.status">{{ statusText(e.status) }}</text>
        </view>
        <view class="meta">
          <text>{{ e.questions }}题</text>
          <text>{{ e.duration }}分钟</text>
          <text>及格{{ e.passScore }}分</text>
        </view>
        <view class="time" v-if="e.startTime">时间：{{ e.startTime }} - {{ e.endTime }}</view>
      </view>
    </view>
    <view class="empty" v-if="!loading && !list.length"><text>暂无考试</text></view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow, onReachBottom } from '@dcloudio/uni-app'
import { getExamList, type Exam } from '@/api'

const list = ref<Exam[]>([])
const loading = ref(false)
const status = ref('')
const page = ref(1)
const hasMore = ref(true)

async function load(reset = false) {
  if (loading.value) return
  if (reset) { page.value = 1; hasMore.value = true; list.value = [] }
  if (!hasMore.value) return
  loading.value = true
  try {
    const res = await getExamList({ page: page.value, pageSize: 20 })
    list.value.push(...(res.list || []))
    hasMore.value = list.value.length < res.total
    page.value++
  } finally { loading.value = false }
}
function switchTab(s: string) { status.value = s; load(true) }
function statusText(s?: string) { return ({ pending: '待考', done: '已完成', expired: '已过期' } as any)[s || ''] || '待考' }
function goDetail(e: Exam) {
  if (e.status === 'done') uni.navigateTo({ url: `/pages/exam/result?id=${e.id}` })
  else uni.navigateTo({ url: `/pages/exam/detail?id=${e.id}` })
}
onShow(() => load(true))
onReachBottom(() => load())
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.tabs { display: flex; background: #fff; }
.tab { flex: 1; text-align: center; font-size: 26rpx; color: #666; padding: 24rpx 0; }
.tab.active { color: #007aff; font-weight: 600; }
.list { padding: 24rpx; }
.item { background: #fff; border-radius: 16rpx; padding: 32rpx; margin-bottom: 24rpx; }
.item-top { display: flex; justify-content: space-between; align-items: center; }
.title { font-size: 30rpx; color: #333; font-weight: 600; }
.status { font-size: 24rpx; }
.status.pending { color: #ff9a3c; }
.status.done { color: #4caf50; }
.status.expired { color: #999; }
.meta { display: flex; gap: 24rpx; margin-top: 16rpx; }
.meta text { font-size: 24rpx; color: #666; }
.time { display: block; font-size: 22rpx; color: #999; margin-top: 12rpx; }
.empty { text-align: center; padding: 120rpx 0; color: #999; }
</style>
