// apps/miniapp-taro/src/pages/user/avatar.tsx
import { View, Text, Button, Image } from '@tarojs/components'
import Taro, { useDidShow } from '@tarojs/taro'
import { useState } from 'react'
import { getProfile, updateUserAvatar } from '@/api'

export default function Avatar() {
  const [avatar, setAvatar] = useState('')

  useDidShow(async () => {
    try { setAvatar((await getProfile()).avatar || '') } catch {}
  })

  function chooseImg() {
    Taro.chooseImage({
      count: 1,
      sizeType: ['compressed'],
      success: async (res) => {
        const path = res.tempFilePaths[0]!
        try {
          setAvatar(path)
          await updateUserAvatar(path)
          Taro.showToast({ title: '更新成功', icon: 'success' })
        } catch {}
      },
    })
  }

  return (
    <View className="min-h-screen bg-[#f7f8fa] px-[16px] pt-[30px]">
      <View
        className="w-[100px] h-[100px] mx-auto rounded-full overflow-hidden"
        style={{ boxShadow: '0 2px 10px rgba(0,0,0,.1)' }}
      >
        <Image
          className="w-full h-full"
          src={avatar || '/static/default-avatar.png'}
          mode="aspectFill"
        />
      </View>
      <Button
        className="mt-[30px] mb-[16px] bg-[#007aff] text-white rounded-[20px] text-[15px]"
        onClick={chooseImg}
      >
        选择头像
      </Button>
      <View className="text-center">
        <Text className="block text-[11px] text-[#999] leading-[1.8]">支持 JPG、PNG 格式</Text>
        <Text className="block text-[11px] text-[#999] leading-[1.8]">建议尺寸 200×200</Text>
      </View>
    </View>
  )
}

// apps/miniapp/pages/user/avatar.vue
<template>
  <view class="page">
    <view class="preview">
      <image class="avatar" :src="avatar || '/static/default-avatar.png'" mode="aspectFill" />
    </view>
    <button class="btn" @tap="chooseImg">选择头像</button>
    <view class="tips">
      <text>支持 JPG、PNG 格式</text>
      <text>建议尺寸 200×200</text>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getProfile, updateUserAvatar } from '@/api'

const avatar = ref('')

onShow(async () => { try { avatar.value = (await getProfile()).avatar || '' } catch (e) {} })

function chooseImg() {
  uni.chooseImage({
    count: 1,
    sizeType: ['compressed'],
    success: async (res) => {
      const path = res.tempFilePaths[0]
      try {
        // 上传头像(此处简化为直接提交URL，实际应上传到OSS)
        avatar.value = path
        await updateUserAvatar(path)
        uni.showToast({ title: '更新成功', icon: 'success' })
      } catch (e) {}
    }
  })
}
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; padding: 60rpx 32rpx; }
.preview { width: 200rpx; height: 200rpx; margin: 0 auto; border-radius: 50%; overflow: hidden; box-shadow: 0 4rpx 20rpx rgba(0,0,0,.1); }
.avatar { width: 100%; height: 100%; }
.btn { margin: 60rpx 0 32rpx; background: #007aff; color: #fff; border-radius: 40rpx; font-size: 30rpx; }
.tips { text-align: center; }
.tips text { display: block; font-size: 22rpx; color: #999; line-height: 1.8; }
</style>
