// apps/miniapp-taro/src/pages/user/index.tsx
import { View, Text, Image } from '@tarojs/components'
import Taro, { useDidShow, useShareAppMessage, useShareTimeline } from '@tarojs/taro'
import { useState, useMemo, useCallback } from 'react'
import { isLoggedIn, getUserInfo, clearAuth, type UserInfo } from '@/utils/auth'
import { logout } from '@/api'
import { useI18n } from '@/i18n'
import { icon } from '@/constants/remote-icons'
import dingdanIcon from '@/assets/remote/images/dingdan.jpg'
import gerenIcon from '@/assets/remote/images/geren-icon.png'
import shezhiIcon from '@/assets/remote/images/shezhi.png'
import gonggaoIcon from '@/assets/remote/images/gonggao.png'
import xianLabelIcon from '@/assets/remote/images/xian_label.png'

const defaultAvatar =
  'https://mp-aab956eb-2e97-4b81-823e-69195b354e49.cdn.bspapp.com/tabbar/tabbar/home.png'

// 判断 icon 是否为图片路径(http(s):// 远程 URL 或 / 开头本地路径),非图片视为 emoji
function isImagePath(icon: string): boolean {
  return /^(https?:)?\/\//.test(icon) || icon.startsWith('/')
}

// 统一渲染 icon:图片路径 → <Image>,emoji → <Text>
function renderIcon(iconStr: string, emojiClass: string, imgClass: string) {
  if (isImagePath(iconStr)) {
    return <Image src={iconStr} className={imgClass} mode="aspectFit" />
  }
  return <Text className={emojiClass}>{iconStr}</Text>
}

const quickEntries = [
  { icon: dingdanIcon, key: 'user.menu.orders', path: '/pages/user/orders' },
  { icon: icon('shoucang'), key: 'user.menu.favorites', path: '/pages/favorites/index' },
  { icon: gerenIcon, key: 'user.menu.following', path: '/pages/following/index' },
  { icon: gonggaoIcon, key: 'user.menu.subscriptions', path: '/pages/subscriptions/index' },
]

const menus = [
  { icon: icon('courseIcon'), key: 'user.menu.courses', path: '/pages/course/list' },
  { icon: icon('aiIcon'), key: 'user.menu.ai', path: '/pages/ai/chat' },
  { icon: shezhiIcon, key: 'user.menu.settings', path: '/pages/user/settings' },
]

// 会员权益项:i18n key 不存在时用中文 fallback(后续补 key 后自动切换)
const membershipBenefits: ReadonlyArray<{ icon: string; key: string; fallback: string }> = [
  { icon: icon('aiIcon'), key: 'user.benefits.exclusiveModel', fallback: '专属模型' },
  { icon: icon('zuan'), key: 'user.benefits.pointsBoost', fallback: '积分加倍' },
  { icon: icon('addKf'), key: 'user.benefits.prioritySupport', fallback: '优先客服' },
  { icon: icon('uservipAct'), key: 'user.benefits.vipZone', fallback: '会员专区' },
  { icon: xianLabelIcon, key: 'user.benefits.discount', fallback: '折扣优惠' },
  { icon: icon('act'), key: 'user.benefits.exclusiveEvents', fallback: '专属活动' },
]

export default function UserIndex() {
  const { t } = useI18n()
  const [userInfo, setUserInfo] = useState<UserInfo | null>(null)
  const [showBenefits, setShowBenefits] = useState<boolean>(false)
  const isLogin = useMemo(() => !!userInfo, [userInfo])

  const refresh = useCallback(() => {
    setUserInfo(isLoggedIn() ? getUserInfo() : null)
  }, [])

  const maskPhone = useCallback((phone: string) => {
    return phone.replace(/(\d{3})\d{4}(\d{4})/, '$1****$2')
  }, [])

  const toggleBenefits = useCallback(() => setShowBenefits((v) => !v), [])

  // i18n key 不存在时(t 返回 key 本身)回退到中文文案
  const tf = useCallback(
    (key: string, fallback: string): string => {
      const v = t(key)
      return v === key ? fallback : v
    },
    [t],
  )

  function goLogin() {
    Taro.navigateTo({ url: '/pages/login/login' })
  }

  function goPage(path: string) {
    Taro.navigateTo({ url: path })
  }

  function handleLogout() {
    Taro.showModal({
      title: t('common.hint'),
      content: t('user.logoutConfirm'),
      success: async (res) => {
        if (res.confirm) {
          try {
            await logout()
          } catch {
            // 忽略退出接口错误
          }
          clearAuth()
          setUserInfo(null)
          Taro.showToast({ title: t('user.loggedOut'), icon: 'success' })
        }
      },
    })
  }

  useDidShow(() => {
    refresh()
  })

  useShareAppMessage(() => ({
    title: t('share.appTitle'),
    path: '/pages/index/index',
    imageUrl: '/static/share.png',
  }))
  useShareTimeline(() => ({
    title: t('share.timelineTitle'),
    query: '',
  }))

  return (
    <View className="min-h-screen pb-[40rpx]">
      {/* 用户信息头部 — primary 实色背景 */}
      <View
        className="pt-[120rpx] px-[32rpx] pb-[48rpx]"
        style={{ background: 'var(--color-primary)' }}
      >
        {userInfo ? (
          <View className="flex items-center">
            <Image
              className="w-[120rpx] h-[120rpx] rounded-md border-[4rpx] border-solid border-primary-foreground"
              src={userInfo.avatar || defaultAvatar}
              mode="aspectFill"
            />
            <View className="ml-[24rpx]">
              <Text className="block text-primary-foreground text-[36rpx] font-semibold">
                {userInfo.userName || userInfo.nickname || t('common.user')}
              </Text>
              {userInfo.phone ? (
                <Text className="block mt-[8rpx] text-primary-foreground text-[24rpx] opacity-85">
                  {maskPhone(userInfo.phone)}
                </Text>
              ) : null}
              {userInfo.isVip ? (
                <Text className="inline-block mt-[12rpx] px-[16rpx] py-[4rpx] bg-accent text-accent-foreground text-[20rpx] rounded-[20rpx]">
                  {t('user.vipMember')}
                </Text>
              ) : null}
            </View>
          </View>
        ) : (
          <View className="flex items-center" onClick={goLogin}>
            <Image
              className="w-[120rpx] h-[120rpx] rounded-md border-[4rpx] border-solid border-primary-foreground"
              src={defaultAvatar}
              mode="aspectFill"
            />
            <View className="ml-[24rpx]">
              <Text className="block text-primary-foreground text-[36rpx] font-semibold">
                {t('user.tapLogin')}
              </Text>
              <Text className="block mt-[8rpx] text-primary-foreground text-[24rpx] opacity-85">
                {t('user.loginHint')}
              </Text>
            </View>
          </View>
        )}
      </View>

      {/* 会员权益卡片 — 展开/收起 */}
      <View className="mx-[32rpx] my-[24rpx] bg-card border border-border rounded-lg overflow-hidden">
        <View
          className="flex items-center justify-between px-[32rpx] py-[28rpx]"
          onClick={toggleBenefits}
        >
          <Text className="text-[28rpx] font-semibold text-foreground">
            {tf('user.benefits.title', '会员权益')}
          </Text>
          <Text
            className={`text-[24rpx] text-muted-foreground transition-transform duration-300 ${
              showBenefits ? 'rotate-180' : ''
            }`}
          >
            ▼
          </Text>
        </View>
        {showBenefits ? (
          <View className="flex flex-wrap px-[8rpx] pb-[16rpx]">
            {membershipBenefits.map((b) => (
              <View key={b.key} className="w-1/3 flex flex-col items-center py-[16rpx]">
                {renderIcon(b.icon, 'text-[44rpx]', 'w-[44rpx] h-[44rpx]')}
                <Text className="mt-[8rpx] text-[24rpx] text-foreground text-center">
                  {tf(b.key, b.fallback)}
                </Text>
              </View>
            ))}
          </View>
        ) : null}
      </View>

      {/* 快捷入口(订单/收藏/关注/订阅)— */}
      <View className="mx-[32rpx] my-[24rpx] py-[28rpx]">
        <View className="flex">
          {quickEntries.map((entry) => (
            <View
              key={entry.path}
              className="flex-1 flex flex-col items-center"
              onClick={() => goPage(entry.path)}
            >
              {renderIcon(entry.icon, 'text-[44rpx]', 'w-[44rpx] h-[44rpx]')}
              <Text className="mt-[6rpx] text-[24rpx] text-foreground">{t(entry.key)}</Text>
            </View>
          ))}
        </View>
      </View>

      {/* 功能列表 */}
      <View className="mx-[32rpx] my-[24rpx] overflow-hidden">
        {menus.map((item, idx) => (
          <View
            key={item.path}
            className={`flex items-center px-[32rpx] py-[32rpx] ${
              idx < menus.length - 1 ? 'mb-[8rpx]' : ''
            }`}
            onClick={() => goPage(item.path)}
          >
            {renderIcon(item.icon, 'text-[40rpx]', 'w-[40rpx] h-[40rpx]')}
            <Text className="flex-1 ml-[20rpx] text-[30rpx] text-foreground">{t(item.key)}</Text>
            <Text className="text-[26rpx] text-[var(--color-primary)]">{'>'}</Text>
          </View>
        ))}
      </View>

      {/* 退出登录 */}
      {isLogin ? (
        <View
          className="mx-[32rpx] my-[48rpx] h-[96rpx] leading-[96rpx] text-center border border-primary text-primary rounded-lg text-[30rpx]"
          onClick={handleLogout}
        >
          <Text>{t('user.logout')}</Text>
        </View>
      ) : null}
    </View>
  )
}

// apps/miniapp/pages/user/index.vue
<template>
  <view class="page">
    <!-- 用户信息头部 -->
    <view class="header">
      <view class="user-info" v-if="userInfo">
        <image class="avatar" :src="userInfo.avatar || defaultAvatar" mode="aspectFill" />
        <view class="meta">
          <text class="name">{{ userInfo.userName || userInfo.nickname || '用户' }}</text>
          <text class="phone" v-if="userInfo.phone">{{ maskPhone(userInfo.phone) }}</text>
          <text class="vip-tag" v-if="userInfo.isVip">VIP 会员</text>
        </view>
      </view>
      <view class="user-info" v-else @tap="goLogin">
        <image class="avatar" :src="defaultAvatar" mode="aspectFill" />
        <view class="meta">
          <text class="name">点击登录</text>
          <text class="phone">登录后享受更多服务</text>
        </view>
      </view>
    </view>

    <!-- 功能列表 -->
    <view class="menu">
      <view class="menu-item" v-for="item in menus" :key="item.path" @tap="goPage(item.path)">
        <text class="menu-icon">{{ item.icon }}</text>
        <text class="menu-text">{{ item.text }}</text>
        <text class="menu-arrow">></text>
      </view>
    </view>

    <!-- 退出登录 -->
    <view class="logout-btn" v-if="isLogin" @tap="handleLogout">
      <text>退出登录</text>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { isLoggedIn, getUserInfo, clearAuth, type UserInfo } from '@/utils/auth'
import { logout } from '@/api'

const defaultAvatar = 'https://mp-aab956eb-2e97-4b81-823e-69195b354e49.cdn.bspapp.com/tabbar/tabbar/home.png'

const userInfo = ref<UserInfo | null>(null)
const isLogin = computed(() => !!userInfo.value)

const menus = [
  { icon: '📋', text: '我的订单', path: '/pages/user/orders' },
  { icon: '⚙️', text: '设置', path: '/pages/user/settings' },
  { icon: '📚', text: '我的课程', path: '/pages/course/list' },
  { icon: '🤖', text: 'AI 对话', path: '/pages/ai/chat' },
]

function refresh() {
  userInfo.value = isLoggedIn() ? getUserInfo() : null
}

function maskPhone(phone: string) {
  return phone.replace(/(\d{3})\d{4}(\d{4})/, '$1****$2')
}

function goLogin() {
  uni.navigateTo({ url: '/pages/login/login' })
}

function goPage(path: string) {
  uni.navigateTo({ url: path })
}

async function handleLogout() {
  uni.showModal({
    title: '提示',
    content: '确定退出登录吗？',
    success: async (res) => {
      if (res.confirm) {
        try {
          await logout()
        } catch (e) {
          // 忽略退出接口错误
        }
        clearAuth()
        userInfo.value = null
        uni.showToast({ title: '已退出登录', icon: 'success' })
      }
    },
  })
}

onShow(refresh)
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; }

.header { padding: 120rpx 32rpx 48rpx; background: linear-gradient(135deg, #007aff, #00c6ff); }
.user-info { display: flex; align-items: center; }
.avatar { width: 120rpx; height: 120rpx; border-radius: 50%; border: 4rpx solid #fff; }
.meta { margin-left: 24rpx; }
.name { display: block; color: #fff; font-size: 36rpx; font-weight: 600; }
.phone { display: block; margin-top: 8rpx; color: rgba(255,255,255,0.85); font-size: 24rpx; }
.vip-tag { display: inline-block; margin-top: 12rpx; padding: 4rpx 16rpx; background: #f0ad4e; color: #fff; font-size: 20rpx; border-radius: 20rpx; }

.menu { margin: 24rpx 32rpx; background: #fff; border-radius: 16rpx; overflow: hidden; }
.menu-item { display: flex; align-items: center; padding: 32rpx; border-bottom: 1rpx solid #f5f5f5; }
.menu-item:last-child { border-bottom: none; }
.menu-icon { font-size: 40rpx; }
.menu-text { flex: 1; margin-left: 20rpx; font-size: 30rpx; color: #333; }
.menu-arrow { font-size: 26rpx; color: #ccc; }

.logout-btn { margin: 48rpx 32rpx; height: 96rpx; line-height: 96rpx; text-align: center; background: #fff; border-radius: 48rpx; color: #dd524d; font-size: 30rpx; }
</style>
