// apps/miniapp-taro/src/pages/ask/list.tsx
import { View, Text, Input, Image } from '@tarojs/components'
import Taro, { useReachBottom } from '@tarojs/taro'
import { useState, useCallback, useEffect } from 'react'
import { getAskList, type Ask } from '@/api'
import './list.css'

export default function AskListPage() {
  const [list, setList] = useState<Ask[]>([])
  const [loading, setLoading] = useState(false)
  const [keyword, setKeyword] = useState('')
  const [tab, setTab] = useState('new')
  const [page, setPage] = useState(1)
  const [hasMore, setHasMore] = useState(true)

  const load = useCallback(async (reset = false) => {
    if (loading) return
    let curPage = page
    if (reset) { curPage = 1; setHasMore(true); setList([]); setPage(1) }
    if (!hasMore && !reset) return
    setLoading(true)
    try {
      const res = await getAskList({ page: curPage, pageSize: 10, keyword })
      const newList = res.list || []
      setList(prev => reset ? newList : [...prev, ...newList])
      setHasMore((reset ? newList.length : list.length + newList.length) < res.total)
      setPage(curPage + 1)
    } finally {
      setLoading(false)
    }
  }, [loading, page, hasMore, keyword, list.length])

  const switchTab = useCallback((t: string) => {
    setTab(t)
    load(true)
  }, [load])

  const goDetail = useCallback((id: string | number) => {
    Taro.navigateTo({ url: `/pages/ask/detail?id=${id}` })
  }, [])

  const goCreate = useCallback(() => {
    Taro.navigateTo({ url: '/pages/ask/create' })
  }, [])

  const onSearchConfirm = useCallback(() => {
    load(true)
  }, [load])

  useReachBottom(() => load())

  useEffect(() => {
    load(true)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return (
    <View className="page">
      <View className="search-bar">
        <Input
          className="search-input"
          placeholder="搜索问题"
          value={keyword}
          onInput={e => setKeyword(e.detail.value)}
          onConfirm={onSearchConfirm}
        />
      </View>

      <View className="tabs">
        <Text className={`tab${tab === 'new' ? ' active' : ''}`} onClick={() => switchTab('new')}>最新</Text>
        <Text className={`tab${tab === 'hot' ? ' active' : ''}`} onClick={() => switchTab('hot')}>热门</Text>
        <Text className={`tab${tab === 'unanswered' ? ' active' : ''}`} onClick={() => switchTab('unanswered')}>待回答</Text>
      </View>

      {list.length ? (
        <View className="list">
          {list.map(a => (
            <View key={a.id} className="item" onClick={() => goDetail(a.id)}>
              <Text className="title">{a.title}</Text>
              <Text className="content">{a.content}</Text>
              <View className="meta">
                <Image className="avatar" src={a.avatar || '/static/default-avatar.png'} mode="aspectFill" />
                <Text className="author">{a.author}</Text>
                <Text className="time">{a.createTime}</Text>
                <Text className={`answers${a.adopted ? ' adopted' : ''}`}>{a.answers || 0}回答</Text>
              </View>
            </View>
          ))}
        </View>
      ) : null}

      {!loading && !list.length ? (
        <View className="empty"><Text>暂无问题</Text></View>
      ) : null}

      <View className="fab" onClick={goCreate}>+</View>
    </View>
  )
}

// apps/miniapp/pages/ask/list.vue
<template>
  <view class="page">
    <view class="search-bar">
      <input class="search-input" placeholder="搜索问题" v-model="keyword" @confirm="load(true)" />
    </view>
    <view class="tabs">
      <text class="tab" :class="{ active: tab === 'new' }" @tap="switchTab('new')">最新</text>
      <text class="tab" :class="{ active: tab === 'hot' }" @tap="switchTab('hot')">热门</text>
      <text class="tab" :class="{ active: tab === 'unanswered' }" @tap="switchTab('unanswered')">待回答</text>
    </view>
    <view class="list" v-if="list.length">
      <view class="item" v-for="a in list" :key="a.id" @tap="goDetail(a.id)">
        <text class="title">{{ a.title }}</text>
        <text class="content">{{ a.content }}</text>
        <view class="meta">
          <image class="avatar" :src="a.avatar || '/static/default-avatar.png'" mode="aspectFill" />
          <text class="author">{{ a.author }}</text>
          <text class="time">{{ a.createTime }}</text>
          <text class="answers" :class="{ adopted: a.adopted }">{{ a.answers || 0 }}回答</text>
        </view>
      </view>
    </view>
    <view class="empty" v-if="!loading && !list.length"><text>暂无问题</text></view>
    <view class="fab" @tap="goCreate">+</view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onReachBottom } from '@dcloudio/uni-app'
import { getAskList, type Ask } from '@/api'

const list = ref<Ask[]>([])
const loading = ref(false)
const keyword = ref('')
const tab = ref('new')
const page = ref(1)
const hasMore = ref(true)

async function load(reset = false) {
  if (loading.value) return
  if (reset) { page.value = 1; hasMore.value = true; list.value = [] }
  if (!hasMore.value) return
  loading.value = true
  try {
    const res = await getAskList({ page: page.value, pageSize: 10, keyword: keyword.value })
    list.value.push(...(res.list || []))
    hasMore.value = list.value.length < res.total
    page.value++
  } finally { loading.value = false }
}
function switchTab(t: string) { tab.value = t; load(true) }
function goDetail(id: string | number) { uni.navigateTo({ url: `/pages/ask/detail?id=${id}` }) }
function goCreate() { uni.navigateTo({ url: '/pages/ask/create' }) }
onReachBottom(() => load())
load()
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; padding-bottom: 120rpx; }
.search-bar { padding: 24rpx 32rpx; }
.search-input { height: 72rpx; padding: 0 24rpx; background: #fff; border-radius: 36rpx; font-size: 26rpx; }
.tabs { display: flex; background: #fff; }
.tab { flex: 1; text-align: center; font-size: 26rpx; color: #666; padding: 24rpx 0; }
.tab.active { color: #007aff; font-weight: 600; }
.list { padding: 24rpx; }
.item { background: #fff; border-radius: 16rpx; padding: 24rpx; margin-bottom: 24rpx; }
.title { font-size: 30rpx; color: #333; font-weight: 600; }
.content { display: block; font-size: 26rpx; color: #666; margin-top: 12rpx; line-height: 1.5; }
.meta { display: flex; align-items: center; margin-top: 16rpx; padding-top: 16rpx; border-top: 2rpx solid #f5f5f5; }
.avatar { width: 40rpx; height: 40rpx; border-radius: 50%; background: #f5f5f5; }
.author { margin-left: 12rpx; font-size: 22rpx; color: #666; }
.time { margin-left: auto; font-size: 22rpx; color: #999; }
.answers { margin-left: 16rpx; font-size: 22rpx; color: #007aff; }
.answers.adopted { color: #4caf50; }
.empty { text-align: center; padding: 120rpx 0; color: #999; }
.fab { position: fixed; right: 40rpx; bottom: 60rpx; width: 100rpx; height: 100rpx; line-height: 100rpx; text-align: center; background: #007aff; color: #fff; border-radius: 50%; font-size: 60rpx; box-shadow: 0 4rpx 20rpx rgba(0,122,255,.4); }
</style>
