// apps/miniapp/pages/user/email.vue
<template>
  <view class="page">
    <view class="card">
      <view class="row">
        <text class="label">邮箱</text>
        <input class="input" type="text" v-model="email" placeholder="请输入邮箱地址" />
      </view>
      <view class="row">
        <text class="label">验证码</text>
        <view class="code-box">
          <input class="input" type="number" v-model="code" placeholder="请输入验证码" maxlength="6" />
          <text class="code-btn" :class="{ disabled: counting }" @tap="sendCode">{{ counting ? `${count}s` : '获取验证码' }}</text>
        </view>
      </view>
    </view>
    <button class="btn" @tap="onSubmit" :disabled="!email || !code">绑定邮箱</button>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getProfile, bindEmail } from '@/api'

const email = ref('')
const code = ref('')
const counting = ref(false)
const count = ref(60)

onShow(async () => { try { email.value = (await getProfile()).email || '' } catch (e) {} })

function sendCode() {
  if (counting.value) return
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value)) return uni.showToast({ title: '邮箱格式错误', icon: 'none' })
  // 复用短信发送逻辑（实际应调用邮箱验证码接口）
  counting.value = true
  const timer = setInterval(() => {
    count.value--
    if (count.value <= 0) { clearInterval(timer); counting.value = false; count.value = 60 }
  }, 1000)
}

async function onSubmit() {
  try {
    await bindEmail(email.value, code.value)
    uni.showToast({ title: '绑定成功', icon: 'success' })
    setTimeout(() => uni.navigateBack(), 1000)
  } catch (e) {}
}
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.card { margin: 24rpx; padding: 0 32rpx; background: #fff; border-radius: 16rpx; }
.row { display: flex; align-items: center; padding: 32rpx 0; border-bottom: 2rpx solid #f5f5f5; }
.label { width: 140rpx; font-size: 28rpx; color: #333; }
.input { flex: 1; font-size: 28rpx; }
.code-box { flex: 1; display: flex; align-items: center; }
.code-btn { color: #007aff; font-size: 24rpx; white-space: nowrap; }
.code-btn.disabled { color: #ccc; }
.btn { margin: 60rpx 32rpx; background: #007aff; color: #fff; border-radius: 40rpx; font-size: 32rpx; }
.btn[disabled] { background: #ccc; }
</style>

// apps/miniapp-taro/src/pages/user/email.tsx
import { View, Text, Input, Button } from '@tarojs/components'
import Taro, { useDidShow } from '@tarojs/taro'
import { useState, useRef } from 'react'
import { getProfile, bindEmail } from '@/api'

export default function Email() {
  const [email, setEmail] = useState('')
  const [code, setCode] = useState('')
  const [counting, setCounting] = useState(false)
  const [count, setCount] = useState(60)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)

  useDidShow(async () => {
    try { setEmail((await getProfile()).email || '') } catch (e) {}
  })

  function sendCode() {
    if (counting) return
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return Taro.showToast({ title: '邮箱格式错误', icon: 'none' })
    }
    // 复用短信发送逻辑（实际应调用邮箱验证码接口）
    setCounting(true)
    timerRef.current = setInterval(() => {
      setCount(prev => {
        if (prev <= 1) {
          if (timerRef.current) clearInterval(timerRef.current)
          setCounting(false)
          return 60
        }
        return prev - 1
      })
    }, 1000)
  }

  async function onSubmit() {
    try {
      await bindEmail(email, code)
      Taro.showToast({ title: '绑定成功', icon: 'success' })
      setTimeout(() => Taro.navigateBack(), 1000)
    } catch (e) {}
  }

  return (
    <View className="min-h-screen bg-[#f7f8fa]">
      <View className="mx-[12px] px-[16px] bg-white rounded-[8px]">
        <View className="flex items-center py-[16px] border-b-[1px] border-solid border-[#f5f5f5]">
          <Text className="w-[70px] text-[14px] text-[#333]">邮箱</Text>
          <Input
            className="flex-1 text-[14px]"
            type="text"
            placeholder="请输入邮箱地址"
            value={email}
            onInput={e => setEmail(e.detail.value)}
          />
        </View>
        <View className="flex items-center py-[16px]">
          <Text className="w-[70px] text-[14px] text-[#333]">验证码</Text>
          <View className="flex-1 flex items-center">
            <Input
              className="flex-1 text-[14px]"
              type="number"
              placeholder="请输入验证码"
              maxlength={6}
              value={code}
              onInput={e => setCode(e.detail.value)}
            />
            <Text
              className={`text-[12px] whitespace-nowrap ${counting ? 'text-[#ccc]' : 'text-[#007aff]'}`}
              onClick={sendCode}
            >
              {counting ? `${count}s` : '获取验证码'}
            </Text>
          </View>
        </View>
      </View>
      <Button
        className={`mx-[16px] mt-[30px] rounded-[20px] text-[16px] ${
          email && code ? 'bg-[#007aff] text-white' : 'bg-[#ccc] text-white'
        }`}
        disabled={!email || !code}
        onClick={onSubmit}
      >
        绑定邮箱
      </Button>
    </View>
  )
}
