// apps/miniapp/pages/user/feedback.vue
<template>
  <view class="page">
    <view class="card">
      <text class="label">反馈类型</text>
      <view class="types">
        <text class="type" v-for="t in types" :key="t" :class="{ active: type === t }" @tap="type = t">{{ t }}</text>
      </view>
      <text class="label">反馈内容</text>
      <textarea class="textarea" v-model="content" placeholder="请详细描述您遇到的问题或建议（10-500字）" maxlength="500" />
      <text class="counter">{{ content.length }}/500</text>
      <text class="label">联系方式（可选）</text>
      <input class="input" v-model="contact" placeholder="手机号/邮箱，方便我们联系您" />
    </view>
    <button class="btn" @tap="onSubmit" :disabled="content.length < 10">提交反馈</button>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { submitFeedback } from '@/api'

const types = ['功能建议', '问题反馈', '体验问题', '其他']
const type = ref('功能建议')
const content = ref('')
const contact = ref('')

async function onSubmit() {
  if (content.value.length < 10) return uni.showToast({ title: '至少输入10字', icon: 'none' })
  try {
    await submitFeedback({ content: `[${type.value}]${content.value}`, contact: contact.value })
    uni.showToast({ title: '提交成功', icon: 'success' })
    setTimeout(() => uni.navigateBack(), 1500)
  } catch (e) {}
}
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; padding-bottom: 120rpx; }
.card { margin: 24rpx; padding: 32rpx; background: #fff; border-radius: 16rpx; }
.label { display: block; font-size: 26rpx; color: #333; margin: 16rpx 0; }
.types { display: flex; flex-wrap: wrap; gap: 16rpx; }
.type { padding: 12rpx 24rpx; border: 2rpx solid #eee; border-radius: 24rpx; font-size: 24rpx; color: #666; }
.type.active { border-color: #007aff; color: #007aff; background: #e6f0ff; }
.textarea { width: 100%; min-height: 240rpx; padding: 20rpx; background: #f7f8fa; border-radius: 12rpx; font-size: 28rpx; box-sizing: border-box; }
.counter { display: block; text-align: right; font-size: 22rpx; color: #999; margin-top: 8rpx; }
.input { width: 100%; padding: 20rpx; background: #f7f8fa; border-radius: 12rpx; font-size: 28rpx; box-sizing: border-box; }
.btn { margin: 32rpx; background: #007aff; color: #fff; border-radius: 40rpx; font-size: 32rpx; }
.btn[disabled] { background: #ccc; }
</style>

// apps/miniapp-taro/src/pages/user/feedback.tsx
import { View, Text, Input, Button, Textarea } from '@tarojs/components'
import Taro from '@tarojs/taro'
import { useState } from 'react'
import { submitFeedback } from '@/api'

const types = ['投诉', '建议', 'bug', '其他']

export default function Feedback() {
  const [content, setContent] = useState('')
  const [contact, setContact] = useState('')
  const [activeType, setActiveType] = useState('建议')

  async function onSubmit() {
    if (!content.trim()) {
      return Taro.showToast({ title: '请输入反馈内容', icon: 'none' })
    }
    try {
      await submitFeedback({ content: content.trim(), contact: contact.trim() || undefined })
      Taro.showToast({ title: '提交成功', icon: 'success' })
      setTimeout(() => Taro.navigateBack(), 1000)
    } catch (e) {}
  }

  return (
    <View className="min-h-screen bg-[#f7f8fa]">
      <View className="mx-[12px] mt-[12px] px-[16px] py-[16px] bg-white rounded-[8px]">
        <Text className="block text-[14px] text-[#333] mb-[12px]">反馈类型</Text>
        <View className="flex flex-wrap gap-[8px]">
          {types.map(t => (
            <View
              key={t}
              className={`px-[16px] py-[6px] rounded-[16px] text-[13px] ${
                activeType === t ? 'bg-[#007aff] text-white' : 'bg-[#f5f5f5] text-[#666]'
              }`}
              onClick={() => setActiveType(t)}
            >
              <Text>{t}</Text>
            </View>
          ))}
        </View>
      </View>
      <View className="mx-[12px] mt-[12px] px-[16px] py-[16px] bg-white rounded-[8px]">
        <Text className="block text-[14px] text-[#333] mb-[12px]">反馈内容</Text>
        <Textarea
          className="w-full text-[14px] min-h-[120px]"
          placeholder="请输入反馈内容"
          value={content}
          onInput={e => setContent(e.detail.value)}
          maxlength={500}
        />
      </View>
      <View className="mx-[12px] mt-[12px] px-[16px] py-[16px] bg-white rounded-[8px]">
        <Text className="block text-[14px] text-[#333] mb-[12px]">联系方式（选填）</Text>
        <Input
          className="w-full text-[14px]"
          type="text"
          placeholder="请输入手机号或邮箱"
          value={contact}
          onInput={e => setContact(e.detail.value)}
        />
      </View>
      <Button
        className={`mx-[16px] mt-[30px] rounded-[20px] text-[16px] ${
          content.trim() ? 'bg-[#007aff] text-white' : 'bg-[#ccc] text-white'
        }`}
        disabled={!content.trim()}
        onClick={onSubmit}
      >
        提交反馈
      </Button>
    </View>
  )
}
