// apps/miniapp/pages/user/nickname.vue
<template>
  <view class="page">
    <view class="card">
      <text class="label">新昵称</text>
      <input class="input" v-model="nickname" placeholder="请输入新昵称" maxlength="20" />
    </view>
    <button class="btn" @tap="onSave" :disabled="!nickname">保存</button>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getProfile, updateUserNickname } from '@/api'

const nickname = ref('')

onShow(async () => { try { nickname.value = (await getProfile()).nickname || '' } catch (e) {} })

async function onSave() {
  if (!nickname.value) return
  try {
    await updateUserNickname(nickname.value)
    uni.showToast({ title: '保存成功', icon: 'success' })
    setTimeout(() => uni.navigateBack(), 1000)
  } catch (e) {}
}
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.card { margin: 24rpx; padding: 32rpx; background: #fff; border-radius: 16rpx; }
.label { font-size: 26rpx; color: #999; }
.input { width: 100%; margin-top: 16rpx; padding: 16rpx 0; font-size: 30rpx; border-bottom: 2rpx solid #f5f5f5; }
.btn { margin: 60rpx 32rpx; background: #007aff; color: #fff; border-radius: 40rpx; font-size: 32rpx; }
.btn[disabled] { background: #ccc; }
</style>

// apps/miniapp-taro/src/pages/user/nickname.tsx
import { View, Text, Input, Button } from '@tarojs/components'
import Taro, { useDidShow } from '@tarojs/taro'
import { useState, useCallback } from 'react'
import { updateUserNickname, getProfile } from '@/api'

export default function Nickname() {
  const [nickname, setNickname] = useState('')
  const [original, setOriginal] = useState('')

  const load = useCallback(async () => {
    try {
      const profile = await getProfile()
      const name = profile.nickname || ''
      setNickname(name)
      setOriginal(name)
    } catch (e) {}
  }, [])

  useDidShow(() => { load() })

  async function onSubmit() {
    if (!nickname.trim()) {
      return Taro.showToast({ title: '请输入昵称', icon: 'none' })
    }
    try {
      await updateUserNickname(nickname.trim())
      Taro.showToast({ title: '修改成功', icon: 'success' })
      setTimeout(() => Taro.navigateBack(), 1000)
    } catch (e) {}
  }

  return (
    <View className="min-h-screen bg-[#f7f8fa]">
      <View className="mx-[12px] mt-[12px] px-[16px] bg-white rounded-[8px]">
        <View className="flex items-center py-[16px] border-b-[1px] border-solid border-[#f5f5f5]">
          <Text className="w-[80px] text-[14px] text-[#333]">当前昵称</Text>
          <Text className="flex-1 text-[14px] text-[#999]">{original || '未设置'}</Text>
        </View>
        <View className="flex items-center py-[16px]">
          <Text className="w-[80px] text-[14px] text-[#333]">新昵称</Text>
          <Input
            className="flex-1 text-[14px]"
            type="text"
            placeholder="请输入昵称"
            value={nickname}
            onInput={e => setNickname(e.detail.value)}
          />
        </View>
      </View>
      <Button
        className={`mx-[16px] mt-[30px] rounded-[20px] text-[16px] ${
          nickname.trim() ? 'bg-[#007aff] text-white' : 'bg-[#ccc] text-white'
        }`}
        disabled={!nickname.trim()}
        onClick={onSubmit}
      >
        保存
      </Button>
    </View>
  )
}
