// apps/miniapp/pages/order/refund-list.vue
<template>
  <view class="page">
    <view class="list" v-if="list.length">
      <view class="item" v-for="o in list" :key="o.id">
        <view class="item-top">
          <text class="o-title">{{ o.title }}</text>
          <text class="o-status refunded">{{ statusText(o.status) }}</text>
        </view>
        <text class="o-no">订单号：{{ o.orderNo }}</text>
        <view class="item-bottom">
          <text class="o-time">{{ o.createTime }}</text>
          <text class="o-amount">¥{{ o.amount }}</text>
        </view>
      </view>
    </view>
    <view class="empty" v-else-if="!loading"><text>暂无退款记录</text></view>
    <view class="loading" v-if="loading"><text>加载中...</text></view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow, onReachBottom } from '@dcloudio/uni-app'
import { getRefundList, type Order } from '@/api'

const list = ref<Order[]>([])
const loading = ref(false)
const page = ref(1)
const hasMore = ref(true)

async function load(reset = false) {
  if (loading.value) return
  if (reset) { page.value = 1; hasMore.value = true; list.value = [] }
  if (!hasMore.value) return
  loading.value = true
  try {
    const res = await getRefundList({ page: page.value, pageSize: 10 })
    list.value.push(...(res.list || []))
    hasMore.value = list.value.length < res.total
    page.value++
  } finally { loading.value = false }
}
function statusText(s: string) { return ({ pending: '处理中', paid: '已支付', cancelled: '已取消', refunded: '已退款' } as any)[s] }
onShow(() => load(true))
onReachBottom(() => load())
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.list { padding: 24rpx; }
.item { background: #fff; border-radius: 16rpx; padding: 32rpx; margin-bottom: 24rpx; }
.item-top { display: flex; justify-content: space-between; }
.o-title { font-size: 30rpx; color: #333; font-weight: 600; }
.o-status { font-size: 24rpx; }
.o-status.refunded { color: #999; }
.o-no { display: block; font-size: 22rpx; color: #999; margin-top: 12rpx; }
.item-bottom { display: flex; justify-content: space-between; margin-top: 16rpx; }
.o-time { font-size: 24rpx; color: #999; }
.o-amount { font-size: 32rpx; color: #dd524d; font-weight: 600; }
.empty, .loading { text-align: center; padding: 120rpx 0; color: #999; }
</style>

// apps/miniapp-taro/src/pages/order/refund-list.tsx
import { View, Text } from '@tarojs/components'
import Taro, { useDidShow, useReachBottom } from '@tarojs/taro'
import { useState, useRef } from 'react'
import { getRefundList, type Order } from '@/api'

const STATUS_TEXT: Record<string, string> = {
  pending: '处理中',
  refunded: '已退款',
}

const STATUS_COLOR: Record<string, string> = {
  pending: 'text-[#ff9a3c]',
  refunded: 'text-[#f44336]',
}

const PAGE_SIZE = 10

export default function RefundList() {
  const [list, setList] = useState<Order[]>([])
  const [loading, setLoading] = useState(false)
  const pageRef = useRef(1)
  const hasMoreRef = useRef(true)
  const loadingRef = useRef(false)

  const load = async (reset = false) => {
    if (loadingRef.current) return
    if (reset) {
      pageRef.current = 1
      hasMoreRef.current = true
      setList([])
    }
    if (!hasMoreRef.current) return
    loadingRef.current = true
    setLoading(true)
    try {
      const res = await getRefundList({ page: pageRef.current, pageSize: PAGE_SIZE })
      const items = res.list || []
      setList(prev => (reset ? items : [...prev, ...items]))
      hasMoreRef.current = pageRef.current * PAGE_SIZE < res.total
      pageRef.current++
    } catch (e) {
      // ignore
    } finally {
      loadingRef.current = false
      setLoading(false)
    }
  }

  const goRefund = (o: Order) => {
    Taro.navigateTo({ url: `/pages/order/refund?id=${o.id}` })
  }

  useDidShow(() => {
    load(true)
  })
  useReachBottom(() => {
    load()
  })

  return (
    <View className="min-h-screen bg-[#f7f8fa]">
      {list.length > 0 && (
        <View className="p-[24rpx]">
          {list.map(o => (
            <View
              key={o.id}
              className="bg-white rounded-[16rpx] p-[32rpx] mb-[24rpx]"
              onClick={() => goRefund(o)}
            >
              <View className="flex justify-between items-center">
                <Text className="text-[30rpx] text-[#333] font-semibold">{o.title}</Text>
                <Text className={`text-[24rpx] ${STATUS_COLOR[o.status] || 'text-[#999]'}`}>
                  {STATUS_TEXT[o.status] || o.status}
                </Text>
              </View>
              <Text className="block text-[22rpx] text-[#999] mt-[12rpx]">订单号：{o.orderNo}</Text>
              <View className="flex justify-between mt-[16rpx]">
                <Text className="text-[24rpx] text-[#999]">{o.createTime}</Text>
                <Text className="text-[32rpx] text-[#dd524d] font-semibold">¥{o.amount}</Text>
              </View>
            </View>
          ))}
        </View>
      )}
      {list.length === 0 && !loading && (
        <View className="text-center py-[120rpx] text-[#999]">
          <Text>暂无退款记录</Text>
        </View>
      )}
      {loading && (
        <View className="text-center py-[120rpx] text-[#999]">
          <Text>加载中...</Text>
        </View>
      )}
    </View>
  )
}
