// apps/web/src/components/form/Select.tsx
'use client'

import * as React from 'react'
import { ChevronDown, Check, Search } from 'lucide-react'
import { cn } from '@/lib/utils'

export interface Option {
  label: string
  value: string | number
  disabled?: boolean
}

interface SelectProps {
  options: Option[]
  value?: string | number | (string | number)[]
  onChange?: (value: string | number | (string | number)[]) => void
  multiple?: boolean
  searchable?: boolean
  placeholder?: string
  label?: string
  error?: string
  disabled?: boolean
  className?: string
}

export function Select({
  options,
  value,
  onChange,
  multiple = false,
  searchable = false,
  placeholder = '请选择',
  label,
  error,
  disabled = false,
  className,
}: SelectProps) {
  const [open, setOpen] = React.useState(false)
  const [query, setQuery] = React.useState('')
  const ref = React.useRef<HTMLDivElement>(null)

  const selected = React.useMemo(() => {
    if (multiple) {
      return Array.isArray(value) ? value : value !== undefined ? [value] : []
    }
    return value
  }, [value, multiple])

  const filtered = React.useMemo(() => {
    if (!searchable || !query) return options
    return options.filter((o) => o.label.toLowerCase().includes(query.toLowerCase()))
  }, [options, query, searchable])

  const displayLabel = React.useMemo(() => {
    if (multiple) {
      const arr = selected as (string | number)[]
      if (!arr.length) return placeholder
      const labels = arr
        .map((v) => options.find((o) => o.value === v)?.label)
        .filter(Boolean)
      return labels.length > 2 ? `已选 ${labels.length} 项` : labels.join(', ')
    }
    const v = selected as string | number | undefined
    return v !== undefined ? options.find((o) => o.value === v)?.label ?? placeholder : placeholder
  }, [selected, options, multiple, placeholder])

  const handleSelect = (val: string | number) => {
    if (multiple) {
      const arr = selected as (string | number)[]
      const next = arr.includes(val) ? arr.filter((v) => v !== val) : [...arr, val]
      onChange?.(next)
    } else {
      onChange?.(val)
      setOpen(false)
    }
  }

  React.useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [])

  const isSelected = (val: string | number) =>
    multiple ? (selected as (string | number)[]).includes(val) : selected === val

  return (
    <div className={cn('w-full space-y-1.5', className)}>
      {label && <label className="text-sm font-medium leading-none">{label}</label>}
      <div ref={ref} className="relative">
        <button
          type="button"
          disabled={disabled}
          onClick={() => setOpen(!open)}
          className={cn(
            'flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm',
            'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
            'disabled:cursor-not-allowed disabled:opacity-50',
            error && 'border-destructive',
          )}
        >
          <span className={cn('truncate', !selected || (multiple && !(selected as []).length) ? 'text-muted-foreground' : '')}>
            {displayLabel}
          </span>
          <ChevronDown className={cn('h-4 w-4 shrink-0 text-muted-foreground transition-transform', open && 'rotate-180')} />
        </button>
        {open && (
          <div className="absolute z-50 mt-1 max-h-60 w-full overflow-auto rounded-md border bg-popover p-1 text-popover-foreground shadow-md">
            {searchable && (
              <div className="relative mb-1">
                <Search className="pointer-events-none absolute left-2 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <input
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder="搜索..."
                  className="h-8 w-full rounded-sm bg-transparent pl-8 pr-2 text-sm outline-none"
                />
              </div>
            )}
            {filtered.length === 0 ? (
              <div className="py-4 text-center text-sm text-muted-foreground">无匹配项</div>
            ) : (
              filtered.map((opt) => (
                <button
                  key={opt.value}
                  type="button"
                  disabled={opt.disabled}
                  onClick={() => handleSelect(opt.value)}
                  className={cn(
                    'flex w-full items-center justify-between rounded-sm px-2 py-1.5 text-sm',
                    'hover:bg-accent hover:text-accent-foreground',
                    opt.disabled && 'cursor-not-allowed opacity-50',
                  )}
                >
                  {opt.label}
                  {isSelected(opt.value) && <Check className="h-4 w-4 text-primary" />}
                </button>
              ))
            )}
          </div>
        )}
      </div>
      {error && <p className="text-xs text-destructive">{error}</p>}
    </div>
  )
}

// client/src/components/ui/select/Select.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { ref, watch, provide, computed } from 'vue'
import { cn } from '@/lib/utils'
import { SELECT_KEY } from './selectContext'

const props = withDefaults(
  defineProps<{
    modelValue?: string | number | boolean | Array<string | number | boolean>
    placeholder?: string
    disabled?: boolean
    clearable?: boolean
    multiple?: boolean
    size?: 'default' | 'small' | 'large'
    class?: HTMLAttributes['class']
  }>(),
  {
    disabled: false,
    clearable: false,
    multiple: false,
    size: 'default',
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: any]
  change: [value: any]
  visibleChange: [visible: boolean]
}>()

const isOpen = ref(false)
const selectedLabel = ref('')

const toggle = () => {
  if (props.disabled) return
  isOpen.value = !isOpen.value
  emit('visibleChange', isOpen.value)
}

const close = () => {
  isOpen.value = false
  emit('visibleChange', false)
}

const selectOption = (value: any, label: string) => {
  if (props.multiple) {
    const currentValues = Array.isArray(props.modelValue) ? [...props.modelValue] : []
    const idx = currentValues.indexOf(value)
    if (idx > -1) {
      currentValues.splice(idx, 1)
    } else {
      currentValues.push(value)
    }
    emit('update:modelValue', currentValues)
    emit('change', currentValues)
  } else {
    emit('update:modelValue', value)
    emit('change', value)
    selectedLabel.value = label
    close()
  }
}

const clearValue = (e: Event) => {
  e.stopPropagation()
  emit('update:modelValue', props.multiple ? [] : '')
  emit('change', props.multiple ? [] : '')
  selectedLabel.value = ''
}

const sizeClass = computed(() => {
  if (props.size === 'small') return 'h-8 text-xs'
  if (props.size === 'large') return 'h-12 text-base'
  return 'h-10 text-sm'
})

provide(SELECT_KEY, {
  modelValue: computed(() => props.modelValue),
  multiple: props.multiple,
  selectOption,
  close,
})

const handleClickOutside = (e: MouseEvent) => {
  const target = e.target as HTMLElement
  if (!target.closest('.select-container')) {
    close()
  }
}

watch(isOpen, (val) => {
  if (val) {
    document.addEventListener('click', handleClickOutside)
  } else {
    document.removeEventListener('click', handleClickOutside)
  }
})
</script>

<template>
  <div :class="cn('select-container relative inline-flex w-full', props.class)">
    <div
      :class="
        cn(
          'flex w-full cursor-pointer items-center justify-between rounded-md border border-input bg-background px-3 py-0 ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
          sizeClass,
          disabled && 'cursor-not-allowed opacity-50',
        )
      "
      @click="toggle"
    >
      <span :class="cn('flex-1 truncate', !selectedLabel && !modelValue && 'text-muted-foreground')">
        {{ selectedLabel || placeholder || '' }}
      </span>
      <span v-if="clearable && modelValue && !disabled" class="ml-2 text-muted-foreground hover:text-foreground" @click="clearValue">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="18" y1="6" x2="6" y2="18" />
          <line x1="6" y1="6" x2="18" y2="18" />
        </svg>
      </span>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        :class="cn('ml-2 transition-transform', isOpen && 'rotate-180')"
      >
        <polyline points="6 9 12 15 18 9" />
      </svg>
    </div>
    <div
      v-if="isOpen"
      class="absolute left-0 top-full z-50 mt-1 max-h-60 w-full overflow-auto rounded-md border bg-popover p-1 text-popover-foreground shadow-md"
    >
      <slot />
    </div>
  </div>
</template>
