// apps/miniapp-taro/src/pages/setting/cache.tsx
import { logger } from '@/utils/logger'
import { View, Text, Button } from '@tarojs/components'
import Taro, { useDidShow } from '@tarojs/taro'
import { useState, useCallback } from 'react'
import { clearCacheSize, clearCache } from '@/api'
import { useI18n } from '@/i18n'
import './cache.css'

export default function CachePage() {
  const { t } = useI18n()
  const [size, setSize] = useState('0KB')

  const load = useCallback(async () => {
    try {
      setSize((await clearCacheSize()).size)
    } catch (e) {
      logger.error('setting/cache', '获取缓存大小', e)
      Taro.showToast({ title: t('setting.cache.failed'), icon: 'none' })
    }
  }, [t])

  const onClear = useCallback(async () => {
    try {
      await clearCache()
      Taro.showToast({ title: t('setting.cache.cleared'), icon: 'success' })
      load()
    } catch (e) {
      logger.error('setting/cache', '清理缓存', e)
      Taro.showToast({ title: t('setting.cache.failed'), icon: 'none' })
    }
  }, [load, t])

  const onClearAll = useCallback(() => {
    onClear()
  }, [onClear])

  useDidShow(() => load())

  return (
    <View className="page">
      <View className="card">
        <View className="row" onClick={onClear}>
          <Text className="label">{t('setting.cache.current')}</Text>
          <Text className="value">{size}</Text>
        </View>
        <View className="row" onClick={onClear}>
          <Text className="label">{t('setting.cache.clearImage')}</Text>
          <Text className="arrow">›</Text>
        </View>
        <View className="row" onClick={onClear}>
          <Text className="label">{t('setting.cache.clearFile')}</Text>
          <Text className="arrow">›</Text>
        </View>
      </View>

      <Button className="btn" onClick={onClearAll}>
        {t('setting.cache.clearAll')}
      </Button>

      <View className="tips">
        <Text>{t('setting.cache.tip1')}</Text>
        <Text>{t('setting.cache.tip2')}</Text>
      </View>
    </View>
  )
}

// apps/miniapp/pages/setting/cache.vue
<template>
  <view class="page">
    <view class="card">
      <view class="row" @tap="onClear">
        <text class="label">当前缓存</text>
        <text class="value">{{ size }}</text>
      </view>
      <view class="row" @tap="onClear">
        <text class="label">清除图片缓存</text>
        <text class="arrow">›</text>
      </view>
      <view class="row" @tap="onClear">
        <text class="label">清除文件缓存</text>
        <text class="arrow">›</text>
      </view>
    </view>
    <button class="btn" @tap="onClearAll">一键清理</button>
    <view class="tips">
      <text>清理缓存不会影响您的账号数据</text>
      <text>清理后已下载的内容需重新加载</text>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { clearCacheSize, clearCache } from '@/api'

const size = ref('0KB')

async function load() {
  try { size.value = (await clearCacheSize()).size } catch (e) {}
}
async function onClear() {
  try {
    await clearCache()
    uni.showToast({ title: '清理成功', icon: 'success' })
    load()
  } catch (e) {}
}
function onClearAll() { onClear() }
onShow(load)
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.card { margin: 24rpx; background: #fff; border-radius: 16rpx; overflow: hidden; }
.row { display: flex; justify-content: space-between; align-items: center; padding: 32rpx; border-bottom: 2rpx solid #f5f5f5; }
.label { font-size: 28rpx; color: #333; }
.value { font-size: 28rpx; color: #007aff; }
.arrow { color: #ccc; }
.btn { margin: 60rpx 32rpx; background: #007aff; color: #fff; border-radius: 40rpx; font-size: 32rpx; }
.tips { padding: 0 32rpx; }
.tips text { display: block; font-size: 22rpx; color: #999; line-height: 1.8; }
</style>
