// apps/miniapp/pages/distribution/rank.vue
<template>
  <view class="page">
    <view class="header">
      <text class="title">分销佣金排行榜</text>
    </view>
    <view class="top3" v-if="list.length >= 3">
      <view class="top-item top2">
        <image class="avatar" :src="list[1].avatar || '/static/default-avatar.png'" mode="aspectFill" />
        <text class="name">{{ list[1].nickname }}</text>
        <text class="commission">¥{{ list[1].commission }}</text>
        <text class="rank">2</text>
      </view>
      <view class="top-item top1">
        <image class="avatar" :src="list[0].avatar || '/static/default-avatar.png'" mode="aspectFill" />
        <text class="name">{{ list[0].nickname }}</text>
        <text class="commission">¥{{ list[0].commission }}</text>
        <text class="rank">1</text>
      </view>
      <view class="top-item top3">
        <image class="avatar" :src="list[2].avatar || '/static/default-avatar.png'" mode="aspectFill" />
        <text class="name">{{ list[2].nickname }}</text>
        <text class="commission">¥{{ list[2].commission }}</text>
        <text class="rank">3</text>
      </view>
    </view>
    <view class="list">
      <view class="item" v-for="(u, i) in list.slice(3)" :key="u.id">
        <text class="rank-num">{{ i + 4 }}</text>
        <image class="avatar" :src="u.avatar || '/static/default-avatar.png'" mode="aspectFill" />
        <text class="name">{{ u.nickname }}</text>
        <text class="commission">¥{{ u.commission }}</text>
      </view>
    </view>
    <view class="empty" v-if="!loading && !list.length"><text>暂无排行数据</text></view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getDistributionRank } from '@/api'

const list = ref<Array<{ id: string; nickname: string; avatar?: string; commission: number }>>([])
const loading = ref(true)

async function load() {
  try { list.value = (await getDistributionRank()).list || [] } finally { loading.value = false }
}
onShow(load)
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; }
.header { padding: 60rpx 0; text-align: center; background: linear-gradient(135deg, #ff6e3c, #ff9a3c); }
.title { color: #fff; font-size: 36rpx; font-weight: 700; }
.top3 { display: flex; align-items: flex-end; justify-content: center; padding: 32rpx 0; background: #fff; }
.top-item { display: flex; flex-direction: column; align-items: center; margin: 0 16rpx; position: relative; }
.top1 .avatar { width: 140rpx; height: 140rpx; border: 6rpx solid #ffd700; }
.top2 .avatar, .top3 .avatar { width: 110rpx; height: 110rpx; border: 4rpx solid #c0c0c0; }
.top3 .avatar { border-color: #cd7f32; }
.avatar { border-radius: 50%; background: #f5f5f5; }
.name { font-size: 24rpx; color: #333; margin-top: 12rpx; }
.commission { font-size: 26rpx; color: #ff6e3c; font-weight: 600; margin-top: 4rpx; }
.rank { position: absolute; top: -16rpx; width: 40rpx; height: 40rpx; line-height: 40rpx; text-align: center; border-radius: 50%; color: #fff; font-size: 22rpx; }
.top1 .rank { background: #ffd700; }
.top2 .rank { background: #c0c0c0; }
.top3 .rank { background: #cd7f32; }
.list { margin: 24rpx; background: #fff; border-radius: 16rpx; overflow: hidden; }
.item { display: flex; align-items: center; padding: 24rpx 32rpx; border-bottom: 2rpx solid #f5f5f5; }
.rank-num { width: 60rpx; font-size: 28rpx; color: #999; }
.avatar { width: 60rpx; height: 60rpx; border-radius: 50%; background: #f5f5f5; }
.name { flex: 1; margin-left: 24rpx; font-size: 28rpx; color: #333; }
.commission { font-size: 28rpx; color: #ff6e3c; font-weight: 600; }
.empty { text-align: center; padding: 120rpx 0; color: #999; }
</style>

// apps/miniapp-taro/src/pages/distribution/rank.tsx
import { View, Text, Image } from '@tarojs/components'
import { useDidShow } from '@tarojs/taro'
import { useState, useCallback } from 'react'
import { getDistributionRank } from '@/api'

interface RankUser {
  id: string
  nickname: string
  avatar?: string
  commission: number
}

const RANK_BG: Record<string, string> = {
  '1': 'bg-[#FFD700]',
  '2': 'bg-[#C0C0C0]',
  '3': 'bg-[#CD7F32]',
}

const RANK_BORDER: Record<string, string> = {
  '1': 'border-[#FFD700]',
  '2': 'border-[#C0C0C0]',
  '3': 'border-[#CD7F32]',
}

export default function DistributionRank() {
  const [list, setList] = useState<RankUser[]>([])
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    try {
      const res = await getDistributionRank()
      setList(res.list || [])
    } catch {
      // ignore
    } finally {
      setLoading(false)
    }
  }, [])

  useDidShow(() => {
    load()
  })

  const top3 = list.slice(0, 3)
  const rest = list.slice(3)

  return (
    <View className="min-h-screen bg-[#f7f8fa]">
      <View className="py-[20px] text-center bg-gradient-to-b from-[#ff6b35] to-[#ff8e53]">
        <Text className="text-white text-[18px] font-bold">分销排行榜</Text>
      </View>
      {top3.length >= 3 && (
        <View className="flex items-end justify-center py-[24px] bg-white">
          {/* 2nd */}
          <View className="flex flex-col items-center mx-[12px] relative">
            <Image
              className="w-[55px] h-[55px] rounded-md bg-[#f5f5f5] border-2 ${RANK_BORDER['2']}"
              src={top3[1]!.avatar || '/static/default-avatar.png'}
              mode="aspectFill"
            />
            <Text className="text-[12px] text-[#333] mt-[8px]">{top3[1]!.nickname}</Text>
            <Text className="text-[14px] text-[#ff6b35] font-semibold mt-[2px]">
              ¥{top3[1]!.commission}
            </Text>
            <Text
              className={`absolute -top-[12px] w-[24px] h-[24px] leading-[24px] text-center rounded-md text-white text-[12px] ${RANK_BG['2']}`}
            >
              2
            </Text>
          </View>
          {/* 1st */}
          <View className="flex flex-col items-center mx-[12px] relative">
            <Image
              className="w-[70px] h-[70px] rounded-md bg-[#f5f5f5] border-2 ${RANK_BORDER['1']}"
              src={top3[0]!.avatar || '/static/default-avatar.png'}
              mode="aspectFill"
            />
            <Text className="text-[12px] text-[#333] mt-[8px]">{top3[0]!.nickname}</Text>
            <Text className="text-[14px] text-[#ff6b35] font-semibold mt-[2px]">
              ¥{top3[0]!.commission}
            </Text>
            <Text
              className={`absolute -top-[12px] w-[24px] h-[24px] leading-[24px] text-center rounded-md text-white text-[12px] ${RANK_BG['1']}`}
            >
              1
            </Text>
          </View>
          {/* 3rd */}
          <View className="flex flex-col items-center mx-[12px] relative">
            <Image
              className={`w-[55px] h-[55px] rounded-md bg-[#f5f5f5] border-2 ${RANK_BORDER['3']}`}
              src={top3[2]!.avatar || '/static/default-avatar.png'}
              mode="aspectFill"
            />
            <Text className="text-[12px] text-[#333] mt-[8px]">{top3[2]!.nickname}</Text>
            <Text className="text-[14px] text-[#ff6b35] font-semibold mt-[2px]">
              ¥{top3[2]!.commission}
            </Text>
            <Text
              className={`absolute -top-[12px] w-[24px] h-[24px] leading-[24px] text-center rounded-md text-white text-[12px] ${RANK_BG['3']}`}
            >
              3
            </Text>
          </View>
        </View>
      )}
      {rest.length > 0 && (
        <View className="m-[12px] bg-white rounded-[8px] overflow-hidden">
          {rest.map((u, i) => (
            <View key={u.id} className="flex items-center p-[12px] border-b-[1px] border-[#f5f5f5]">
              <Text className="w-[30px] text-[14px] text-[#999]">{i + 4}</Text>
              <Image
                className="w-[32px] h-[32px] rounded-md bg-[#f5f5f5]"
                src={u.avatar || '/static/default-avatar.png'}
                mode="aspectFill"
              />
              <Text className="flex-1 ml-[12px] text-[14px] text-[#333]">{u.nickname}</Text>
              <Text className="text-[14px] text-[#ff6b35] font-semibold">¥{u.commission}</Text>
            </View>
          ))}
        </View>
      )}
      {!loading && list.length === 0 && (
        <View className="text-center py-[60px] text-[#999]">
          <Text>暂无排行数据</Text>
        </View>
      )}
    </View>
  )
}
