// apps/miniapp/pages/distribution/withdraw.vue
<template>
  <view class="page">
    <view class="card">
      <text class="label">可提现金额</text>
      <text class="amount">¥{{ available }}</text>
      <view class="input-box">
        <text class="unit">¥</text>
        <input class="input" type="digit" v-model="amount" placeholder="请输入提现金额" />
      </view>
      <view class="types">
        <text class="tlabel">提现方式</text>
        <view class="type-row">
          <view class="type" v-for="t in types" :key="t.value" :class="{ active: payType === t.value }" @tap="payType = t.value">
            <text>{{ t.name }}</text>
          </view>
        </view>
      </view>
    </view>
    <button class="btn" @tap="onSubmit">立即提现</button>
    <view class="tips">
      <text>提现说明：</text>
      <text>1. 最低提现金额 ¥10</text>
      <text>2. 提现申请将在1-3个工作日内审核</text>
      <text>3. 工作日17:00前申请当日到账</text>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { getDistributionInfo, withdraw } from '@/api'

const available = ref(0)
const amount = ref('')
const payType = ref('wechat')
const types = [
  { value: 'wechat', name: '微信' },
  { value: 'alipay', name: '支付宝' },
  { value: 'bank', name: '银行卡' },
]

async function load() {
  try { available.value = (await getDistributionInfo()).available } catch (e) {}
}
async function onSubmit() {
  const amt = Number(amount.value)
  if (!amt || amt < 10) return uni.showToast({ title: '最低提现¥10', icon: 'none' })
  if (amt > available.value) return uni.showToast({ title: '余额不足', icon: 'none' })
  try {
    await withdraw({ amount: amt, type: payType.value })
    uni.showToast({ title: '提现申请已提交', icon: 'success' })
    amount.value = ''
    load()
  } catch (e) {}
}
onShow(load)
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: #f7f8fa; padding-bottom: 40rpx; }
.card { margin: 24rpx; padding: 32rpx; background: #fff; border-radius: 16rpx; }
.label { font-size: 26rpx; color: #999; }
.amount { display: block; font-size: 60rpx; color: #333; font-weight: 700; margin: 16rpx 0 32rpx; }
.input-box { display: flex; align-items: center; padding: 24rpx 0; border-top: 2rpx solid #f5f5f5; }
.unit { font-size: 40rpx; color: #333; font-weight: 600; }
.input { flex: 1; margin-left: 16rpx; font-size: 40rpx; }
.types { margin-top: 32rpx; }
.tlabel { font-size: 26rpx; color: #999; }
.type-row { display: flex; margin-top: 16rpx; gap: 16rpx; }
.type { flex: 1; padding: 20rpx 0; text-align: center; border: 2rpx solid #eee; border-radius: 12rpx; font-size: 26rpx; color: #333; }
.type.active { border-color: #ff6e3c; color: #ff6e3c; }
.btn { margin: 32rpx; background: #ff6e3c; color: #fff; border-radius: 40rpx; font-size: 32rpx; }
.tips { padding: 0 32rpx; }
.tips text { display: block; font-size: 22rpx; color: #999; line-height: 1.8; }
</style>

// apps/miniapp-taro/src/pages/distribution/withdraw.tsx
import { View, Text, Input, Button } from '@tarojs/components'
import Taro, { useDidShow } from '@tarojs/taro'
import { useState, useRef } from 'react'
import { getDistributionInfo, withdraw } from '@/api'

const PAY_TYPES = [
  { value: 'wechat', label: '微信' },
  { value: 'alipay', label: '支付宝' },
]

export default function DistributionWithdraw() {
  const [available, setAvailable] = useState(0)
  const [amount, setAmount] = useState('')
  const [payType, setPayType] = useState('wechat')
  const [submitting, setSubmitting] = useState(false)
  const availableRef = useRef(0)

  const load = async () => {
    try {
      const info = await getDistributionInfo()
      setAvailable(info.available)
      availableRef.current = info.available
    } catch (e) {
      // ignore
    }
  }

  const fillAll = () => {
    setAmount(String(availableRef.current))
  }

  const onSubmit = async () => {
    const amt = Number(amount)
    if (!amt || amt <= 0) {
      Taro.showToast({ title: '请输入有效金额', icon: 'none' })
      return
    }
    if (amt > availableRef.current) {
      Taro.showToast({ title: '余额不足', icon: 'none' })
      return
    }
    setSubmitting(true)
    try {
      await withdraw({ amount: amt, type: payType })
      Taro.showToast({ title: '提现申请已提交', icon: 'success' })
      setTimeout(() => {
        Taro.navigateBack()
      }, 800)
    } catch (e) {
      // ignore
    } finally {
      setSubmitting(false)
    }
  }

  useDidShow(() => {
    load()
  })

  return (
    <View className="min-h-screen bg-[#f7f8fa]">
      <View className="mx-[12px] mt-[12px] bg-white rounded-[8px] p-[16px]">
        <Text className="text-[12px] text-[#999]">可提现余额</Text>
        <Text className="block text-[40px] text-[#333] font-bold mt-[4px]">¥{available}</Text>
        <View className="flex items-center py-[12px] mt-[8px] border-t-[1px] border-[#f5f5f5]">
          <Text className="text-[24px] text-[#333] font-semibold">¥</Text>
          <Input
            className="flex-1 ml-[8px] text-[24px]"
            type="digit"
            value={amount}
            onInput={e => setAmount(e.detail.value)}
            placeholder="请输入提现金额"
          />
          <Button
            className="text-[12px] text-[#ff6b35] bg-transparent border-none leading-[24px]"
            onClick={fillAll}
          >
            全部提现
          </Button>
        </View>
        <View className="mt-[16px]">
          <Text className="text-[12px] text-[#999]">提现方式</Text>
          <View className="flex mt-[8px] gap-[12px]">
            {PAY_TYPES.map(t => (
              <View
                key={t.value}
                className={`flex-1 py-[10px] text-center rounded-[8px] text-[14px] ${payType === t.value ? 'bg-[#ff6b35] text-white' : 'bg-[#f5f5f5] text-[#333]'}`}
                onClick={() => setPayType(t.value)}
              >
                <Text>{t.label}</Text>
              </View>
            ))}
          </View>
        </View>
      </View>
      <Button
        className="mx-[12px] mt-[24px] bg-[#ff6b35] text-white rounded-[8px] text-[16px]"
        disabled={submitting}
        onClick={onSubmit}
      >
        立即提现
      </Button>
    </View>
  )
}
